### PR TITLE
Add support for "login with Facebook" and MS live

### PR DESCRIPTION
**Pull request by apmon**
Annoyingly Facebook and MS Live accounts do not implement OpenID which is the correct way to do authentication. Therefore they are not covered by the existing implementation of third party authentication. Imho they are, however, important enough to (reluctantly) warrant some special casing to support them and make it easier for new users to create an OpenStreetMap account.

This implementation uses the OAuth2 standard to retrieve user information from either Facebook or a Windows Live account that can then be used for authentication. It reuses a lot of the openID infrastructure to simplify the code and minimize the special casing.

As it uses OAuth2 and OAuth requires applications to register with the provider, the website needs to be
registered with Facebook and MS Live to use this feature. The oauth app id and app secret are stored
in application.yml

### CODE REVIEW

**Comment by ppawel** [comment]
What is the current status? @apmon Are you working on this? If not then I could possibly try to take a stab at rebasing and dealing with Google phasing out OpenID.

**Comment by pnorman** [comment]
I don't believe anyone is actively working on this.

**Comment by mvexel** [comment]
Vaguely related, is [this](https://github.com/openstreetmap/openstreetmap-website/issues/894#issuecomment-74115310) an OSM web site bug?

**Comment by mvexel** [comment]
It looks like Google is [retiring OpenID 2.0 support](https://developers.google.com/accounts/docs/OpenID#shutdown-timetable), moving everything to something called [OpenID Connect](https://developers.google.com/accounts/docs/OpenIDConnect) which seems to be based on the OAuth 2.0 flow. More info [here](http://openid.net/2014/02/26/the-openid-foundation-launches-the-openid-connect-standard/) - is this something we're already supporting, or looking to support? (potentially related to #894)

**Comment by tomhughes** [comment]
Oh for crying out loud, can we please stop this splattering comments across any bug vaguely related to your current personal bugbear.

The google issue is being dealt with in #897 not here...

**Comment by mvexel** [comment]
Thanks for pointing that out @tomhughes !

**Comment by tomhughes** [comment]
Support for Facebook and Windows Live has now been added via #960 and is live.

Thanks for your work on this @apmon even if we didn't wind up using this version in the end, and apologies that it all took so long to get resolved.

**Pull request closed without merging**
