### PR TITLE
Responsive HTML mails

### PR DESCRIPTION
**Pull request by saintamh**
A few tweaks to the HTML/CSS code of the email notifications to make messages more responsive on narrow displays, which should improve the viewing experience on mobile. Also a handful of minor tweaks to fonts.

There are no changes to content, only implementation.

https://wiki.openstreetmap.org/wiki/Dressed-up_Notification_Mails is up to date with screenshots of what this PR produces.

### CODE REVIEW

**Comment by Zverik** [comment]
Could you please add a before/after image to push this forward?

**Comment by saintamh** [comment]
Hi Ilya, 

The screenshots at https://wiki.openstreetmap.org/wiki/Dressed-up_Notification_Mails all show the "after". Every image there that has a version older than Feb 9th is a "before" shot, but there's no easy way to get a single page with all of them. I'll generate one later today.

Here's a quick sample:
- gmail/ie8:
  - [before](https://wiki.openstreetmap.org/w/images/archive/b/bb/20170209231903%21Gmail-ie8--changeset-comment-long.png) (notice project name)
  - [after](https://wiki.openstreetmap.org/w/images/b/bb/Gmail-ie8--changeset-comment-long.png)
- iOS mail
  - [before](https://wiki.openstreetmap.org/w/images/archive/4/4e/20170212203755%21Ios-mail--changeset-comment-long.png) (tries to fit full width message on phone screen)
  - [after](https://wiki.openstreetmap.org/w/images/4/4e/Ios-mail--changeset-comment-long.png)
- Windows Mail
  - [before](https://wiki.openstreetmap.org/w/images/archive/a/a8/20170209232836%21Windows-mail--changeset-comment-long.png) (fonts are wrong, project name misaligned)
  - [after](https://wiki.openstreetmap.org/w/images/a/a8/Windows-mail--changeset-comment-long.png)

**Comment by Zverik** [comment]
Thanks! I like that the text is no longer in italic.

@tomhughes is there anything blocking this PR?

**Comment by saintamh** [comment]
Here's side-by-side before/after shots: http://52.56.34.44:8080/static/pr1436-before-after.html

There's a good number of screenshots on the wiki page that didn't have a "before" counterpart, and which aren't included here.

**Comment by tomhughes** [comment]
Oh sorry I completely missed this PR somehow.

**Comment by tomhughes** [comment]
It doesn't look very responsive though - a lot of those screenshots seem to show the content now being narrower, with bigger sidebars. I'd expect the opposite if it was responsive?

**Comment by saintamh** [comment]
I think the varying conditions under which the screenshots are taken might give that impression. The (white) sidebars are actually a tad thinner, but otherwise are unchanged. In a lot of the screenshots there's a sea of (grey) empty space around the message, but that was there before. I just took the screenshots on a bigger screen the 2nd time. 

Basically, in prod at the moment the width is fixed at around ~600px, where with this PR that's only a maximum value, and if available space is less than that the table will squish. And mobile browsers won't force the table to use the full width of their tiny screen.

You can try them out at http://52.56.34.44:8080/

**Comment by tomhughes** [comment]
Yes it was the "sea of gray" that I as referring to so it sounds like it's just down to different browser window sizes.

**Comment by Firefishy** [comment]
@saintamh awesome contribution, looks great! 👍

**Pull request merged**
