### PR TITLE
Test Nominatim.describe_location

### PR DESCRIPTION
**Pull request by AntonKhorev**
Tests for #4957

### CODE REVIEW

**Comment by AntonKhorev** [comment]
`with_settings(:server_url ...)` seems to be ignored by Tests / Ubuntu but not by Docker

**Comment by tomhughes** [comment]
Thanks - looks good and I verified that it catches the mistake I made in my PR the other day ;-)

**Comment by AntonKhorev** [comment]
But it doesn't work correctly on github. It sends 'User-Agent'=>'test.host' instead of what I'm trying to substitute.

**Comment by tomhughes** [comment]
Sorry I misunderstood what you were saying... I thought you had worked around it.

The problem is that `OSM.http_client` only creates the client once, the first time it is called, so what user agent is used depends on what order the tests run in.

I think we can just make the test check that the user agent is `test.host` instead of trying to change it.

**Comment by tomhughes** [comment]
Made that change in 63f0b9257d62818d435ef6510340b9681efe547b.

**Pull request merged**
