### PR TITLE
Implemented diary submit label changing depending on if new or editing

### PR DESCRIPTION
**Pull request by fad4470**
Saw this listed as TODO and thought it'd be something to try.

### CODE REVIEW

**Comment by tomhughes** [comment]
Hmm... I'm not sure where that TODO came from, or if I agree with it...

I can see that "Save" might not be the best label for the button, but do the labels really need to be different for the two cases? Would "Publish" not work fine for both? Conditioning anything in a view on the action is not something I like doing if it can be avoided.

**Comment by tomhughes** [comment]
Looks like Harry added that comment in 152cb13a02dfcb2966b8a9b29382f84a99a23a69.

**Comment by Zverik** [comment]
I like it. The button really says what it does.

**Comment by fad4470** [comment]
It is a small thing, but it's good practice to make a difference clear. Though not wanting those kinds of conditionals is fair too.

**Comment by harry-wood** [comment]
For a user, publishing a new diary entry feels quite a lot different than saving an edit to a diary entry, even though it's the same thing happening behind the scenes. That was was my thinking when I stuck a TODO in there ...back in 2008!

**Pull request merged**
