### PR TITLE
Update Docker documentation and Dockerfile

### PR DESCRIPTION
**Pull request by SlowMo24**
This PR updates the Docker documentation to the latest version of docker, where `docker compose` is bundled and no longer uses a hyphen (https://docs.docker.com/compose/migrate/).

It also solves #4100 in the docker build phase.

### CODE REVIEW

**Review by gravitystorm — CHANGES_REQUESTED** [review]
A few things need addressing here:

* If compose v2 comes bundled with docker, then the installation instructions at the top of DOCKER.md need to be updated too.
* We want to keep the manual instructions and the CI docker tests in sync. So that means `.github/workflows/docker.yml` needs the same change from `docker-compose` to `docker compose`
* It might be worth removing the unrelated `ca-certificates` change from this PR, and resolve that separately.

**Comment by Firefishy** [comment]
I am happy to pick this PR up if desired? @SlowMo24 

`docker-compose` (v1) is no longer supported. `docker compose` (v2) is confirmed available on [GitHub Actions](https://github.com/Firefishy/gha-docker-compose-test/actions/runs/6038820008/job/16386018616)

The DOCKER.md instructions still function, but likely should be clearer about making sure to install Docker Compose (v2) on Ubuntu this can be done by running: `sudo apt-get install docker-compose-plugin`

**Comment by Firefishy** [comment]
`ca-certificates` I think is a worthwhile package to install. Without it a system does not have a default CA root trust store, which likely could lead to certificate errors or undefined behaviour.

**Comment by tomhughes** [comment]
Yes I just didn't realise the base image would be missing that but if it is then fine.

**Comment by gravitystorm** [comment]
> `ca-certificates` I think is a worthwhile package to install. Without it a system does not have a default CA root trust store, which likely could lead to certificate errors or undefined behaviour.

In theory, perhaps? But it's not actually necessary, otherwise our CI build would already be failing, right?

In any case, as per my original review, it's unrelated to updating the documentation.

**Comment by mmd-osm** [comment]
Our CI build installs `ca-certificates` already. Probably it's being pulled in via some dependency. For reference check the raw logs of a recent Docker build: https://github.com/openstreetmap/openstreetmap-website/actions/runs/6036092209/job/16377726247

Quoting a few relevant lines form the logs:

```
[...]
2023-08-31T10:23:53.6007897Z #6 57.00 Selecting previously unselected package ca-certificates.
2023-08-31T10:23:53.7095643Z #6 57.00 Preparing to unpack .../178-ca-certificates_20230311ubuntu0.22.04.1_all.deb ...
2023-08-31T10:23:53.7098764Z #6 57.00 Unpacking ca-certificates (20230311ubuntu0.22.04.1) ...
[...]
2023-08-31T10:24:12.5385253Z #6 75.86 Setting up ca-certificates (20230311ubuntu0.22.04.1) ...
[...]
2023-08-31T10:24:26.7721153Z #6 90.16 Processing triggers for ca-certificates (20230311ubuntu0.22.04.1) ...
2023-08-31T10:24:26.7721468Z #6 90.17 Updating certificates in /etc/ssl/certs...
2023-08-31T10:24:27.3749501Z #6 90.63 0 added, 0 removed; done.
2023-08-31T10:24:27.3750329Z #6 90.63 Running hooks in /etc/ca-certificates/update.d...
2023-08-31T10:24:27.3750741Z #6 90.63 
2023-08-31T10:24:27.6407812Z #6 90.89 done.
[...]
```

**Comment by gravitystorm** [comment]
Superseded by #4257

**Pull request closed without merging**
