### PR TITLE
Add banner for FOSSGIS 2017 conference

### PR DESCRIPTION
**Pull request by PedaB**
FOSSGIS is a not-yet-official local OSM chapter and its conference is a big OSM event for the German-speaking part of the world. Would be nice to get this on the main page to advertise our event. On the same go I cleaned up the list of banners and removed past events.

### CODE REVIEW

**Comment by tomhughes** [comment]
I know I added this last year but I kind of wish I hadn't and I think I only did so because it was very short notice and there wasn't time to get a policy in place.

We really need a proper policy on who is allowed to have a banner as I'm not really comfortable making that decision myself on an ad-hoc basis.

**Comment by PedaB** [comment]
I think I don't fully understand why you are reconsidering now as we had a banner for kind of every local OSM conference.

Does this stem from the fact that FOSSGIS is not (yet) an official local chapter, is there a problem with the banner design or is it by accident just now that we need a policy first?

Where would be an appropriate place to start a policy discussion? The Issue tracker?

**Comment by pnorman** [comment]
>I think I don't fully understand why you are reconsidering now

The need for a policy isn't new, it goes back to at least OSM PLUS.

**Comment by tomhughes** [comment]
Well the kind of questions a policy would address are (a) who gets a banner (b) how often can they have one and (c) how long in advance of an event.

Obviously "affiliated chapters get a banner" would be one possible answer to the first question but it's by no means the only one.

The point is currently I get to make those decisions entirely by myself, and it seems easy while things are normal and there is an obvious group in a country, but what happens if a rival group springs up in a country? Do they both get a banner?

**Comment by mmd-osm** [comment]
@PedaB : I guess you could close this one by now?

**Comment by PedaB** [comment]
The event's over for a long time.

**Pull request closed without merging**
