### PR TITLE
add a step to vagrant setup to migrate the test db

### PR DESCRIPTION
**Pull request by harry-wood**
Following the VAGRANT.md instructions we get a 'pending migrations' error. We could add another manual step to the instructions, but this way it's set up automatically.

### CODE REVIEW

**Comment by tomhughes** [comment]
No, this is just wrong as I have explained several times. In particular as of today the tests will fail if run against a DB migrated like that.

Use `rake test:db` the first time you run the tests to properly initialise the database.

**Comment by tomhughes** [comment]
To explain a bit more https://travis-ci.org/openstreetmap/openstreetmap-website/builds/170800818 is what (since yesterday) will happen if you migrate the test database. The fix was https://github.com/openstreetmap/openstreetmap-website/commit/15395bb94403bd5f2ecb2d9887573cca58801b1f which makes sure to reinitialise the test database.

The reason for the difference is that the migrations populate the `languages` table, but the tests expect it to be empty. That is achieved by `rake test:db` because it dumps the schema (without any data) from the dev database and then uses that to recreate the test database.

Because travis only has one database the migrate there was migrating the test database, and changing the rake target made it then dump and recreate that database losing the data in the process.

**Comment by harry-wood** [comment]
hmm I saw that commit https://github.com/openstreetmap/openstreetmap-website/commit/15395bb94403bd5f2ecb2d9887573cca58801b1f but thought it was just a coincidence that you were tackling a similar issue with the travis config...  but no that has actually fixed the vagrant set-up too. The tests just run now. 

...which confuses me. I _was_ I imagining travis is not involved in a vagrant provision & test run. Thought it was just to do with the automated test runs which get displayed on github.

**Comment by tomhughes** [comment]
It shouldn't have any effect on vagrant. Did you retest from scratch or was it reusing a previously built VM image?

**Comment by harry-wood** [comment]
I was doing vagrant destroy beforehand (before & after) but maybe my repo was out of sync with the latest code for some other reason. All refreshed and it's working now. ...or at least I'm onto the next failure.

**Comment by harry-wood** [comment]
no actually I was wrong about being wrong. (With a fresh vagrant box on the right branch this time) _"Migrations are pending. To resolve this issue, run: bin/rake db:migrate RAILS_ENV=test"_

Note the error message telling us to do the wrong thing, because...  yes I see `bundle exec rake test:db` works better than `bundle exec rake db:migrate RAILS_ENV=test` because of the languages table as you described.

So... add `bundle exec rake test:db` to provision.sh?

**Comment by tomhughes** [comment]
Well we don't really want to run the tests as part of the provision do we?

There might be some way to run the `db:setup` task in the test environment or something...

**Comment by harry-wood** [comment]
Should a vagrant provision run tests? I don't know. Interesting philosophical question. I would've thought getting it _ready_ to run tests would be a good idea. Or we just add the `bundle exec rake test:db` line to https://github.com/openstreetmap/openstreetmap-website/blob/master/VAGRANT.md

**Comment by harry-wood** [comment]
_"some way to run the db:setup task"_ I came across people mentioning a [new thing](http://stackoverflow.com/a/23351832/338265) you can do with rails 4.1+ `ActiveRecord::Migration.maintain_test_schema!`. Maybe _that's_ the best way. But haven't tried it.

**Pull request closed without merging**
