### PR TITLE
Vagrant deploy works

### PR DESCRIPTION
**Pull request by wilfoa**
Fixed failed migrations and creating extension btree_gist for test DB 'osm_test'

### CODE REVIEW

**Comment by tomhughes** [comment]
The failed migrations are already fixed in #868 which will be merged shortly.

**Comment by tomhughes** [comment]
Why do you need to install `btree_gist` in the test database explicitly? Doesn't rails clone that from the main database anyway?

**Comment by wilfoa** [comment]
It didn't work for me until I did. What happened was when I tried running the test by `rake test`, I got an message telling me to migrate the `TEST` environment and so I did. The migrations ran until failing on `db/migrate/028_add_more_changeset_indexes.rb` because of a `GIST` method not existing. That got sorted out after installing `btree_gist`

**Comment by tomhughes** [comment]
Yeah I'm genuinely confused about how rails creates and populates the test database - when I was working on the 4.2 update over the weekend it just seemed to do random things...

**Comment by wilfoa** [comment]
Yeah :-)
So do you want me to revert the migration fixes and just leave the vagrant provision script addition?

**Comment by tomhughes** [comment]
I've merged #868 now if you want to rebase this to get rid of the migration fixes that should now be in master.

**Comment by wilfoa** [comment]
Tried rebasing and it was getting messy for some reason. I want to remove this pull request and open another. Is that ok with you?

**Comment by tomhughes** [comment]
Sure, or you can just recreate your branch and force push it and this PR will update.

**Comment by wilfoa** [comment]
That was indeed simpler :) thanks!

It's all in place now

**Comment by tomhughes** [comment]
Thanks. I've merged that now.

**Comment by wilfamir** [comment]
When will this be available in master?

**Comment by tomhughes** [comment]
It already is on git.osm.org but it might take a few minutes for the mirror to push it to github.

**Comment by wilfamir** [comment]
cool - thanks!

**Pull request closed without merging**
