### PR TITLE
Switch to using kramdown for markdown formatting

### PR DESCRIPTION
**Pull request by tomhughes**
As suggested by @gravitystorm in #2103 this switches our markdown formatting to use kramdown instead of redcarpet.

As kramdown doesn't have the builtin sanitisation features of redcarpet I have passed the resulting HTML through the sanitiser used for other formats and have also added a few extra restrictions to links in user generated content.

Note that this doesn't fix all the issues in #2103 as bullet lists nested in numbered lists still don't seem to work as the reporter there is expecting.

Also I noticed that redcarpet was turning thinks which look like links but have no link markup into links which kramdown doesn't - we could fix that by running our autolinker if we wanted.

### CODE REVIEW

**Comment by tomhughes** [comment]
I've added in the auto linkification for now - if we decide to remove it then some tests would need to be fixed.

**Comment by gravitystorm** [comment]
OK, looks good to me!

> Note that this doesn't fix all the issues in #2103 as bullet lists nested in numbered lists still don't seem to work as the reporter there is expecting.

That's a problem with our stylesheets - the html outputted by kramdown seems correct as it's outputting `<ul>` tags for the bullet lists. But [in our stylesheets](https://github.com/openstreetmap/openstreetmap-website/blob/fbbabeff1e3bc473720e6eaece83825a9c349ba8/app/assets/stylesheets/common.scss#L2349-L2351) we have:

```
ol li {
  list-style: decimal;
}
```
... and as far as I can tell, that means that any `<ul>` instead of a `<ol><li>` will inherit the decimal list style. Perhaps we could fix that as a followup.

**Comment by tomhughes** [comment]
Good spot! Added a fix for that in 81b37f9263ec0d76b60b3273e5f9d9a4345bfbfe.

**Comment by mmd-osm** [comment]
There's an ongoing discussion in a diary post about kramdown causing some regressions for some people. More specifically it seems that images with links to other sites somehow get rendered in a different way, and in some cases no longer work, see https://www.openstreetmap.org/user/MKnight/diary/40702 as an example.

Using the following style (http://www.disturbancesinthewash.net/journal/2012/8/11/how-to-add-an-image-with-link-in-markdown.html) seems to be ok, though.

**Comment by tomhughes** [comment]
If you want anybody to investigate then you'll have to provide some actual details of what doesn't work, rather than what does work, which isn't very interesting.

**Comment by tomhughes** [comment]
Sorry I assumed that the "discussion" you referred to (which I didn't try and translate) had come some conclusion ;-)

Some of the other ones are worse in that they do `alt text (link url)` with no proper link syntax at all - that was never valid.

**Comment by tomhughes** [comment]
I think I've fixed them all now.

**Comment by mmd-osm** [comment]
>  I assumed that the "discussion" you referred to (which I didn't try and translate) had come some conclusion I think there was no real conclusion, other than the previous syntax didn't work anymore. 

> I think I've fixed them all now.

**Pull request merged**
