### PR TITLE
Add locale selector

### PR DESCRIPTION
**Pull request by nertc**
This PR addresses "Language switcher on the homepage" issue mentioned in https://github.com/openstreetmap/openstreetmap-website/issues/1115

The code is based on @tomhughes 's PR https://github.com/openstreetmap/openstreetmap-website/pull/3618, which, as Tom mentioned in the [comment](https://github.com/openstreetmap/openstreetmap-website/pull/4461#issuecomment-1879660419), after rebasing had some styling issues. Most of the functional part of this PR was written by @tomhughes.

Language selector button, to be consistent, now is not hidden when the user is logged in. Instead, it redirects to the "My Preferences" page, where user can change language preferences. When the user is logged out, it still works like in https://github.com/openstreetmap/openstreetmap-website/pull/3618 _ shows "jquery uls" language selector popup / dropdown.

The reason for logged in user redirection instead of any complex functionality of preferred language change while clicking language selector, was compatibility with the PR https://github.com/openstreetmap/openstreetmap-website/pull/4461. After both PRs will be merged, there will be one smooth simple UX flow for logged in users.

In addition to these, this PR also adds:
- Tests for checking if redirection works correctly
- Both LTR and RTL language supported icon
- Language selector icon with the same default and hover colors as other menu items

Default view of the language selector:

image

This PR has many different visual impacts, so to make description shorter instead of directly adding images, I'll add links to them.

LTR screenshots:
- [Opened language selector](https://github.com/user-attachments/assets/0ee30d22-734d-491a-8355-acc7c0f51dba)
- [Medium resolution menu](https://github.com/user-attachments/assets/772b883a-7911-4f34-a81f-90a0c46a5f68)
- [Medium resolution menu hover](https://github.com/user-attachments/assets/cede63b4-447c-430e-b23a-28904dbdc3a2)
- [Small resolution menu](https://github.com/user-attachments/assets/18daace0-c617-4483-b7b0-9137906603bd)

RTL screenshots:
- [Default view](https://github.com/user-attachments/assets/6cc3b52d-09a6-4795-ab6c-6c56d2f361c2)
- [Medium resolution menu](https://github.com/user-attachments/assets/cb5306c5-96fa-418e-836e-71ef965f7fc5)
- [Small resolution menu](https://github.com/user-attachments/assets/7a0e913f-e59d-47a2-85c3-8db9e0e1c3e3)

### CODE REVIEW

**Comment by tomhughes** [comment]
Hmm I wish you'd asked before working on this... I'm not at all sure the wikimedia selector is a good way to go.

**Comment by nertc** [comment]
@tomhughes functionality of Wikimedia selector worked well from your PR, so I didn't touch any code of it. I can change it if we have any more lightweight or visually appealing solution idea. If solution of the PR https://github.com/openstreetmap/openstreetmap-website/pull/4461 is good for us, I can merge @AntonKhorev 's solution and use same dropdown but with current icon on the homepage.

**Comment by AntonKhorev** [comment]
Wikimedia selector has its own layout css. Imagine judging it by the same standards #3620 was judged where I added two css properties and changed another two css properties...

**Comment by nertc** [comment]
@AntonKhorev Thanks for mentioning your PR. I'll take a look at it and try to fix as much CSS related issues as possible according to comments.

**Comment by AntonKhorev** [comment]
> Recommendations provided in the https://github.com/openstreetmap/openstreetmap-website/pull/3620 were about using less custom CSS.

Yes, if you ignore this part of the recommendations:

> We're using Bootstrap for all of our layouts now, and this PR should do the same.

**Comment by nertc** [comment]
@AntonKhorev Can you provide me with more details? Current solution doesn't use any custom CSS code which is not in accordance with the current state of application coding style. Bootstrap is used for most of the visual part and only two occurrences of custom CSS are icons and visibility change when printing. Both of them are based on the current code and standard of the application. If you mean styles provided by the library, it means we shouldn't use any library that uses its own CSS and if this is our standard, I can write a custom selector and dropdown for language selection.

**Comment by nertc** [comment]
I am closing this PR. Instead, new PR https://github.com/openstreetmap/openstreetmap-website/pull/5201 is opened, which doesn't use Wikimedia selector and, therefore, adds much less code of JS and CSS.

**Pull request closed without merging**
