### PR TITLE
Switch vagrant to use Debian 12

### PR DESCRIPTION
**Pull request by tomhughes**
Similar to #5157 this switches the vagrant configuration to use Debian 12 instead of Ubuntu.

Only tested with the libvirt provider at the moment.

### CODE REVIEW

**Comment by nenad-vujicic** [comment]
Wouldn't be safer to stick to specific Debian version (e.g. 12.7) instead of using the latest v12?  Similarly for #5157

**Comment by tomhughes** [comment]
I don't know enough about Debian to be able to answer that but the minor versions are just updated installers that include the latest updates aren't they?

**Comment by tomhughes** [comment]
As far as I can tell there aren't any images for specific releases anyway - the [list](https://app.vagrantup.com/debian) just contains one image for each major version which looks like it is regularly updated with the latest packages.

**Comment by mmd-osm** [comment]
Test completed with status "ok" on VirtualBox 6.1 w/ virtualbox provider:

```
Finished in 449.210410s, 4.0671 runs/s, 2230.1976 assertions/s.
1827 runs, 1001828 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Minitest, Minitest-0, Minitest-1 to /srv/openstreetmap-website/coverage. 6287 / 6679 LOC (94.13%) covered.
Lcov style coverage report generated for Minitest, Minitest-0, Minitest-1 to coverage/lcov.info

```

**Comment by gravitystorm** [comment]
Needs rebasing, since it conflicts with the change in image to jammy that was merged as part of #5070

**Comment by tomhughes** [comment]
Rebased now.

**Comment by gravitystorm** [comment]
Merged, thanks!

**Pull request merged**
