### PR TITLE
iD 2.2.2 related additions

### PR DESCRIPTION
**Pull request by bhousel**
* Remove traffico from the asset pipeline - this is Mapillary's legacy traffic sign library that is no longer included or used
* Disable `removeUselessStrokeAndFill` svgo plugin (see openstreetmap/iD#4105) - I think it is removing the `#000000` fill on an icon.

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @tomhughes!  I think you might also need to recompile the assets.  Not sure....

**Comment by tomhughes** [comment]
@bhousel what do you mean? assets are precompiled as part of the deployment.

**Comment by bhousel** [comment]
> assets are precompiled as part of the deployment.

I still see the old iD-sprite that's missing the color, but not sure whether that is because it is cached or because rails asset pipeline didn't precompile it (because the sprite itself didn't change, only the options to svgo did)

screenshot 2017-06-12 20 31 47

**Comment by tomhughes** [comment]
Oh it will only recompile things that have changed yes, and there is likely no dependency on the options.

**Pull request merged**
