### PR TITLE
Refactor social sharing helper

### PR DESCRIPTION
**Pull request by tomhughes**
This implements the refactorings suggested in #5415 and also improves the testing of the generated HTML to ensure that all the buttons are generated and reference the correct URL and title.

### CODE REVIEW

**Comment by AntonKhorev** [comment]
Are you sure you escape things correctly?
image

**Review by kcne — APPROVED** [review]
Everything works well on my side. Thank you.

**Comment by kcne** [comment]
> Are you sure you escape things correctly? image

This only happens on [Mastodon Share](https://mastodonshare.com/) links. Must be something related to their implementation. I'm not sure if the code is opensource since i could not find the github repo. On the web site about page there is only this information:

> MastodonShare is 100% private, 100% free, and 100% secure. It does not store or track anything about the visitors, usernames, instances, links or content. It does not require Mastodon API access.

> If you have any questions, please ask me [alex@barredo.es](mailto:alex@barredo.es) or [@barredo@mastodon.social](https://mastodon.social/@barredo).

**Comment by AntonKhorev** [comment]
Looks like `&` gets unescaped in mastodonshare.com's redirect location.

Request headers:
```
GET /?text=A%26B&url=http%3A%2F%2F127.0.0.1%3A3000%2Fuser%2Ffakeuser1%2Fdiary%2F86 HTTP/1.1
Host: mastodonshare.com
...
```

Response headers:
```
HTTP/1.1 302 Found
...
Location: https://en.osm.town/share?text=A&B%0A%0Ahttp://127.0.0.1:3000/user/fakeuser1/diary/86
```

**Comment by gravitystorm** [comment]
Thanks for the refactoring!

**Pull request merged**
