### PR TITLE
Correct defninition of `Public` trace and make the definitions clearer.

### PR DESCRIPTION
**Pull request by GoodClover**
I have made the definition of trace visibilities clearer and corrected the definition of a `Public` trace.
See #2308

### CODE REVIEW

**Comment by tomhughes** [comment]
As I have just explained in #2308 your conclusion appears to be wrong - if you think that the tracepoints API is exposing that information then I believe it's an critical bug that should be fixed rather than changing the documentation but you have not as yet provided any evidence to support your claim.

**Comment by tomhughes** [comment]
I've pushed 786b8cce651d31afc9a3ae920f25f0d13b0314c0 now which extends the tests to verify that no identifying information is returned.

**Comment by Firefishy** [comment]
Typo in PR: `Reccomended`

**Comment by tomhughes** [comment]
It doesn't really matter any way - we shouldn't be marking any particular option as recommended. That's a decision for the user.

Marking public as deprecated might be reasonable but I don't think we should make any other value judgements here.

**Comment by tomhughes** [comment]
There are also practical limits to how much text you can reasonably show in an option list drop down...

**Comment by GoodClover** [comment]
Oh sorry about the spelling, I must have just mistyped.

I copied the bracketed things from what the wiki said about each option, it says it's the recommended option on there.

About the limits of text, maybe just remove the long explanation altogether and leave that for the user to go to the wiki?

**Comment by tomhughes** [comment]
I think there is a link to the wiki isn't there? Though I'm not very keen on that because people can make changes that might not be accurate and it might not be noticed.

**Comment by tomhughes** [comment]
Yes - there is a "what does this mean" link under the control that links to the wiki page.

**Comment by GoodClover** [comment]
I think having it marked as the "Full" option would be good if it's not marked as recommended.
To a new person, if just the names were shown, it's confusing as to what they mean.

Should I remove the notes in brackets then and leave the long text?
Or what else should be done?

**Comment by GoodClover** [comment]
As Tom said, the text is impractical; it barely fits for Identifiable.
image

Maybe showing descriptions separately on the page would be better?

That's beyond my ability though as RoR/`.erb` is not my thing.

**Pull request closed without merging**
