### PR TITLE
Update to iD v1.6.3

### PR DESCRIPTION
**Pull request by bhousel**
[changelog v1.6.3](https://github.com/openstreetmap/iD/blob/master/CHANGELOG.md#163)

### CODE REVIEW

**Comment by jfirebaugh** [comment]
:shipit:! Nice work @bhousel.

**Comment by tomhughes** [comment]
Something seems to be very wrong. When I start iD all I get is a black square where the map should be. No javascript errors at that point, but lots if I try and pan or zoom in the space where the map should be.

First error is:

```
TypeError: source.validZoom is not a function
render(selection=[[div.layer-layer.background-layer]])iD-e8d8...?body=1 (line 25527)
background(selection=[[div.layer-layer.background-layer]])iD-e8d8...?body=1 (line 25518)
d3_selectionPrototype.call(callback=background(selection))iD-e8d8...?body=1 (line 1372)
background(selection=[[div#supersurface]])iD-e8d8...?body=1 (line 24026)
d3_selectionPrototype.call(callback=background(selection))iD-e8d8...?body=1 (line 1372)
map(selection=[[div#map]])iD-e8d8...?body=1 (line 24935)
d3_selectionPrototype.call(callback=map(selection))iD-e8d8...?body=1 (line 1372)
render(container=[[div#id-container.id-container]])
```

**Comment by bhousel** [comment]
I think I'm stumped.. 
The `iD.js` and `iD.min.js` in [openstreetmap/iD](https://github.com/openstreetmap/iD/tree/release/dist) both work ok as far as I can tell, and match exactly the `iD.js` that got vendored into [osmlab/openstreetmap-website](https://github.com/osmlab/openstreetmap-website/tree/iD-1.6.3/vendor/assets/iD)

**Comment by bhousel** [comment]
Maybe it only shows up for certain background imagery sources?   @tomhughes can you send me the url that you are trying this so that I can see the background / zoom / lng / lat?

Can you also try it here and see if you get the same error?
http://openstreetmap.us/iD/master

Thanks!

**Comment by tomhughes** [comment]
So I've put my merged branch up at http://tomh.apis.dev.openstreetmap.org/edit and that seems to be failing in the same way as my machine at home was. Test URL is http://tomh.apis.dev.openstreetmap.org/edit#map=16/51.7659/0.0043

**Comment by tomhughes** [comment]
The http://openstreetmap.us/iD/master version is working for me though.

**Comment by bhousel** [comment]
Thanks @tomhughes...
It looks like the imagery sources weren't set...  Looking at our own code, it seems like they need to get set before starting the ui.

@jfirebaugh : does [this change](https://github.com/openstreetmap/iD/commit/dd0e08b244b6f36659f15a29fa26ebe6321bc664#diff-f3c8e37dd0a73713fe739364dd4bcd98R68)  necessitate an upstream change too for embedded iD?

**Comment by bhousel** [comment]
Needs to go [here](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/site/id.html.erb#L21) right?

If so, we should probably redo this as 1.7, since it's an api breaker..

**Comment by tomhughes** [comment]
I think it's more like https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/site/id.html.erb#L7 isn't it? To add the two new includes after the iD one? Then call the methods in the place you mentioned.

You'll also need to include the two new files and them to https://github.com/openstreetmap/openstreetmap-website/blob/master/config/initializers/assets.rb so that they get precompiled.

There may be an argument for creating a new "meta" js file that requires all three though, so that they become one asset for the client?

**Comment by jfirebaugh** [comment]
I should have remembered that this was necessary, sorry about that.

Three things need to be set: [presets, imagery, and taginfo](https://github.com/openstreetmap/iD/blob/5bff37f11b775af3d22e0b583ef6ff414d722fdf/dist/index.html#L68-L70). And the presets.js and imagery.js files need to be included. :+1: for making a meta include file for all three. That's probably best done on the osm-website side using the asset pipeline.

:+1: for 1.7.0.

**Comment by tomhughes** [comment]
I've added https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/id.js now as a wrapper, so you can require the other two javascript files there and then add the function calls to the html view file.

**Comment by bhousel** [comment]
Thanks Tom, I'll finish this up tonight and resubmit the PR

**Comment by bhousel** [comment]
continued at #898

**Pull request closed without merging**
