### PR TITLE
add banner for SotM 2017

### PR DESCRIPTION
**Pull request by althio**
thank you @bhousel for the detailed instructions @ https://github.com/openstreetmap/openstreetmap-website/pull/1580

### CODE REVIEW

**Comment by tomhughes** [comment]
That image looks very big, as in much bigger than previous banners?

**Comment by tomhughes** [comment]
Confirmed - previous banners have been roughly square at 350x350 while that is 376x586 so it's both too wide (that column is only 350 pixels wide) and also a lot taller than normal.

Also if you're going to remove banner.yml entries please remove the referenced images as well.

**Comment by tomhughes** [comment]
So it's actually being scaled (because of the column width) to 350x545 currently.

**Comment by althio** [comment]
376 wide was an error, thank you for reviewing.
The image is now natively 350x554.

Please add to https://github.com/openstreetmap/openstreetmap-website/pull/1580 the requirement about recommended height.

**Comment by althio** [comment]
The image is now 350x350.

**Comment by bhousel** [comment]
Nice, sorry for the confusion on image size - I will update #1580 with some more info.

**Pull request merged**
