### PR TITLE
Groups sketch

### PR DESCRIPTION
**Pull request by tmcw**
/cc @emacsen @samanpwbb @mvexel 

This is not functional yet. I don't think this is a good use of sprint time since it's not day-doable.

* [ ] Get the Model to actually work
* [ ] Finish the form

### CODE REVIEW

**Comment by tmcw** [comment]
I think we should close this. It's very stale and nobody's working on it.

**Comment by mikelmaron** [comment]
yea, not active. would be good to pick this up again sometime, but not in my view near term. moabi made quite a lot of additions on groups in the mean time too.

**Comment by systemed** [comment]
I'm still very keen to get this live, and we're pretty close. It'd be a huge boon to OSM.

I haven't been able to take it forward as a number of outstanding issues (notably the pagination) are beyond my rails-fu, though I've tried a couple of times. But with a bit of help I don't see why we couldn't get this live within the month.

**Comment by timwaters** [comment]
The moabi / crowdcover groups work I contributed to is at https://github.com/crowdcover/openstreetmap-website in the groups-sketch branch. The key difference is that groups have a lead, and are invite only, with invites occurring via the messaging / email system. Group diaries are included as well as a group picture, and the group map now makes sense. No group changeset / history view was developed however.  (The Moabi system also has a fair bit of other stuff with groups, including custom iD presets etc)

**Comment by kiselev-dv** [comment]
Can somebody restore the branch? Want to get that functionality onto osm.org.

**Comment by tomhughes** [comment]
As far as I know https://github.com/openstreetmap/openstreetmap-website/pull/297/commits/f034ac589285c61643bf20a41916598b5104888d was the tip of the branch when it was deleted so if you can fetch than and create a local branch from it then that should work.

It's about five years old though so I suspect that it may be of minimal use...

**Comment by tomhughes** [comment]
There are also some things (like something to do with editor presets) that don't seem to be anything to do with this branch so you might need to tidy up the history somewhat.

**Pull request closed without merging**
