### PR TITLE
Remove SotM Africa 2023 and SotM Asia x FOSS4G 2023,  add SotM 2024

### PR DESCRIPTION
**Pull request by enockseth**
This PR adds a banner for State of the Map 2024 https://2024.stateofthemap.org and cleans up older banners.
>The pull request must indicate when the banner should start being shown, which must be at least 7 days after the pull request was created.

It would be great if it can start sooner or at the specified start date until end date i.e. a day before the event starts (2024-sep-05). Thank you.

_On behalf of SotM WG_

### CODE REVIEW

**Comment by tomhughes** [comment]
As an OSMF run event you're entitled to three months so running the requested time span is no problem.

Please remove the merge commit, in line with https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md#pull-requests.

**Review by tomhughes — CHANGES_REQUESTED** [review]
Can you squash those commits together please - we don't need two versions of the image in the history. Then I can get this merged.

**Review by enockseth — COMMENTED** [review]
I have updated this now, thank you.

**Comment by tomhughes** [comment]
Thanks. I'll merge this now.

**Pull request merged**
