### PR TITLE
Mention error message in OAuth setup for iD

### PR DESCRIPTION
**Pull request by zerebubuth**
My usual workflow for trying to fix errors that I don't understand is to paste the error message into a search engine, and I think many other people do the same. Putting the error message here would help me, and other people, find the step missed during setup.

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
Perhaps this situation can be detected on runtime and handled with a clear error info.

**Comment by gravitystorm** [comment]
> Perhaps this situation can be detected on runtime and handled with a clear error info.

Sounds good - @HolgerJeromin could you try making a pr for that?

**Comment by HolgerJeromin** [comment]
I have no idea how integration of the website code and iD works. Analyzing the correct place for this warning (and learning ruby along the way) is not possible for me right now 8-/

**Comment by mmd-osm** [comment]
Mapping a non existing ID_KEY to a blank value would show the following error popup when starting iD:

grafik


```ruby
diff --git a/app/views/site/_id.html.erb b/app/views/site/_id.html.erb
index 867b148..57a8967 100644
--- a/app/views/site/_id.html.erb
+++ b/app/views/site/_id.html.erb
@@ -1,7 +1,7 @@
 <%= javascript_include_tag "edit/id" %>
 
 <div id="map">
-  <% data = { :key => ID_KEY } -%>
+  <% data = { :key => defined?(ID_KEY) ? ID_KEY : "" } -%>
   <% data[:lat] = @lat if @lat -%>
   <% data[:lon] = @lon if @lon -%>
   <% data[:gpx] = trace_data_url(params[:gpx], :format => :xml) if params[:gpx] -%>


```

**Pull request closed without merging**
