### PR TITLE
Use Bootstrap toggle buttons for layers menu

### PR DESCRIPTION
**Pull request by AntonKhorev**
Enables keyboard controls for base layers section of layers sidebar.

What I didn't bother doing is making colors exactly the same as before. There was a green border on active button but every other control in the sidebar had blue active color which is also the default for bootstrap's primary buttons. So I kept the default color.

Updated version:
image

The update was done to eliminate pixel values from css at the expense of having wider borders.

Version using only the first two commits:
VirtualBox_ubuntu1_01_09_2022_18_16_56

### CODE REVIEW

**Comment by mmd-osm** [comment]
I currently don't see a difference in the text color for the map layers. On your screenshot "ÖPNVKarte" and "Humanitarian" are shown in blue, while "Standard" and "CyclOSM" are in black. Is this somehow related this change?

grafik

**Comment by tomhughes** [comment]
The blue is actually the standard bootstrap colour for a "primary" button and the black is then an override for the selected button, again from the bootstrap styles.

**Comment by AntonKhorev** [comment]
On my screenshot one button is currently enabled layer, one is focused button, and two are neither enabled not focused.

**Comment by HolgerJeromin** [comment]
can be closed?

**Pull request closed without merging**
