### PR TITLE
Added links to the relevant OSMF sites and some additional text 

### PR DESCRIPTION
**Pull request by simonpoole**
Previously the copyright page had no indication as to who was the actual licensor of the OSM data. iirc this was mainly to downplay the role of the OSMF in OSMspace. This however is causing more trouble than it is worth. 

I was considering adding " .... on behalf of the OpenStreetMap contributors" however this would seem to again create uncertanity as to the legal situation.

This is likely the first of a small number of PRs with the aim of making somethings easier to find (contact address etc).

Please do not merge before the LWG and the CWG have had a quick look.

### CODE REVIEW

**Comment by simonpoole** [comment]
The 2 commit add links to to various useful resources to the help page.  IIRC the mailing lists and forums where left oft due to convolulted arguments that beginners might be offended by the contents.

**Comment by simonpoole** [comment]
The 3rd commit adds a "Legal" section to the "About" page, this still needs its own icon, but it seems as if the source code (SVG) / original bitmap files for the icons on the page are missing from the repo. Further note: adding a further section increases the layout issues the page already has.

**Comment by tomhughes** [comment]
It looks @jfirebaugh created the about page, so maybe he knows what the source of those images is?

**Comment by jfirebaugh** [comment]
An SVG can be found [here](https://github.com/osmlab/attribution-mark/blob/gh-pages/design/sprite.svg).

**Comment by simonpoole** [comment]
Thanks @jfirebaugh

**Comment by simonpoole** [comment]
Added an icon for legal now, all changes where tested on desktop and mobile FF and Chrome.

**Comment by simonpoole** [comment]
Pro memoria: add some text on OpenStreetMap being a TM owned by the OSMF to the page. Needs to refer to either the trademark policy or some text roughly outlining permissable use.

**Comment by tomhughes** [comment]
Merged.

**Pull request closed without merging**
