### PR TITLE
Remove both Potlatch versions

### LINKED ISSUE #2622: Sunset web based Potlatch by end of 2020
I'm creating this issue as placeholder for follow up activities for https://wiki.openstreetmap.org/wiki/Talk:Microgrants/Microgrants_2020/Proposal/Potlatch_2_for_desktop

Activitites:

-  [ ] Maybe let mappers know ahead of time so they can switch to another editor
- [ ] *Revisit the "undelete" API topic** 
- [ ] Removal of ActionScript artefacts
- [ ] Removal of AMF controller on Rails port

### PR DESCRIPTION
**Pull request by tomhughes**
Fixes #2622

### CODE REVIEW

**Review by pnorman — APPROVED** [review]

**Comment by gravitystorm** [comment]
Looks good to me. 

There's a small UI issue when you have your preferred editors set to P2 and then visit the settings page, since the dropdown will say "Preferred Editor: Default (currently iD)" when it's actually P2 until the next time you save your changes. But I'm not proposing spending time on that, unless we see any complaints.

**Review by gravitystorm — APPROVED** [review]

**Comment by mmd-osm** [comment]
While testing I've noticed a tiny bit that might be missing: https://github.com/openstreetmap/openstreetmap-website/blob/1303ba8c7d11b71c0366af4791af1e95f89b0211/config/locales/en.yml#L1784

To be in line with the other text, the error message should probably also include Potlatch?

**Comment by SK53** [comment]
> 
> 
> Looks good to me.
> 
> There's a small UI issue when you have your preferred editors set to P2 and then visit the settings page, since the dropdown will say "Preferred Editor: Default (currently iD)" when it's actually P2 until the next time you save your changes. But I'm not proposing spending time on that, unless we see any complaints.

Was just coming to report this! Shame I only noticed too late for weeklyOSM to link to the above comment.

**Comment by pierzen** [comment]
@SK53 Are you asking for a link to weeklyOSM  in the list of preferred editors ;) ?

**Pull request merged**
