### PR TITLE
Update attribution for Australia

### PR DESCRIPTION
**Pull request by andrewharvey**
Per request from the copyright holder to DWG updated to match requested attribution per https://data.gov.au/data/dataset/bdcf5b09-89bc-47ec-9281-6b8e9ee147aa

### CODE REVIEW

**Comment by tomhughes** [comment]
Has this been cleared by LWG?

**Comment by andrewharvey** [comment]
The original request went to legal-questions, which I got forwarded since I organised the original waiver, so I've asked legal-questions if they can review here.

**Comment by andrewharvey** [comment]
@tomhughes I asked legal-questions if they could review, but haven't heard anything yet. The copyright holder has just asked if this could be updated again, so I don't see how this would be an issue given it's per their request. Thanks.

**Comment by simonpoole** [comment]
@andrewharvey I don't believe that the legal-questions OTRS queue is actively being worked through, at least not for multiple months. I know and then point out stuff that could have real legal consequences (as in this case), but that's the limit of my involvement. You probably should contact the LWG directly (legal@osmfoundation.org), or @mackerski

**Comment by mackerski** [comment]
Hi folks,

As Simon notes, LWG is rather backlogged in OTRS, a situation we hope to
resolve. I've identified the ticket in question and I have added this topic
to tomorrow's LWG agenda. We will be back in touch once we have reviewed
things.

Thanks,
Dermot

**Comment by andrewharvey** [comment]
@mackerski was this fine? I can't see any issues with updating the attribution, the data provider is asking for this to be updated.

**Comment by openstreetmap-website** [comment]
Hi Andrew, and sorry for the delay.

Yes, the LWG is happy that this change be made where we provide this kind
of attribution. But we also recognised that this same change of name means
that the existing CC waiver we have (which refers to the old name) should
also be refreshed. So as part of our communication that we are making our
change, we would like you to ask that they in return endorse a revised
version of the waiver (perhaps that's easiest if you update the text of the
existing one as appropriate for their approval).

Thanks!
Dermot

**Comment by andrewharvey** [comment]
Thanks @mackerski, I'll request an updated waiver with the new attribution.

**Pull request merged**
