### PR TITLE
add some notes about importing data to INSTALL.md

### PR DESCRIPTION
**Pull request by saerdnaer**
relates to #282

### CODE REVIEW

**Comment by mmd-osm** [comment]
I think this has been documented elsewhere already: https://github.com/openstreetmap/openstreetmap-website/blob/master/DOCKER.md#loading-an-osm-extract

Maybe it would be good to consolidate this a bit?

**Comment by danieldegroot2** [comment]
(also at [CONFIGURE.md#populating-the-database](https://github.com/openstreetmap/openstreetmap-website/blob/b8d83738158e3efc0792ef2c66bb41e846ed28ec/CONFIGURE.md#populating-the-database) )

**Comment by saerdnaer** [comment]
For now I just cross-linked the other pages, the link to `CONFIGURE.md` was on really visible to me.

**Comment by tomhughes** [comment]
Well I think the idea is to separate core things that everybody needs from detailing every obscurity of interest only to a few people.

**Comment by tomhughes** [comment]
Note that I at least don't recommend trying to load data into an API database because it's very hard to do right and there aren't really the tools to do it well.

**Comment by gravitystorm** [comment]
The documentation is deliberately separated into INSTALL.md and CONFIGURE.md, so things like populating the database should appear in the CONFIGURE.md - which it already does!

I would recommend that any changes you want to make should be put there, rather than being duplicated between multiple locations. Additionally, you should confirm that the stuff about disabling indexes is accurate - I don't like having our documentation saying "probably", when we could test it and find out for sure.

Also, you mentioned that you hadn't seen the documentation in CONFIGURE.md before creating this PR, so if you can think of any way to make that documentation more obvious, that would be great.

**Pull request closed without merging**
