### PR TITLE
Avoid using jsonp for GraphHopper

### PR DESCRIPTION
**Pull request by karussell**
`jsonp` should be avoided as error reporting is not always possible. The necessary magic should be done from jquery automatically. (is there a possibility to test this on an openstreetmap.org domain before going production?)

### CODE REVIEW

**Comment by tomhughes** [comment]
Well as far as I know we were only using jsonp because XHR wasn't possible - we certainly prefer not to use it. Is there a suitable cross domain policy in place that will allow access?

Also you will need to update https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/application_controller.rb#L411 to move graphopper from `script_src` to `connect_src`.

**Comment by karussell** [comment]
> Is there a suitable cross domain policy in place that will allow access?

Yes, it was reported it works for others :)

For https://graphhopper.com/api/1/info?key=_KEY_ you can see:

```
access-control-allow-origin=*
access-control-expose-headers=X-RateLimit-Limit,X-RateLimit-Remaining,X-RateLimit-Reset,X-RateLimit-Credits
```

And 
`
curl -v -XOPTIONS 'https://graphhopper.com/api/1/info?key=_KEY_'
`
reports some more Access-Control headers
> to move graphopper from script_src to connect_src

done

**Comment by karussell** [comment]
Thanks!

**Comment by karussell** [comment]
When will it be deployed so that I can test if it still works?

**Comment by tomhughes** [comment]
It's been tested, and has been deployed - it should be live by now.

**Comment by karussell** [comment]
Wow, that was fast. Thanks a bunch - also for removing the other jsonp parameter! Works :+1:

**Pull request closed without merging**
