### PR TITLE
Add user_<uid> class to diary entry div

### PR DESCRIPTION
**Pull request by systemed**
This adds a class containing the user ID to the div element enclosing a diary entry.

So, for example, a diary entry I write would get the class `user_165`.

This enables a site viewer to add basic killfile-like functionality with Firefox's usercontent.css or extensions like Stylus.

### CODE REVIEW

**Comment by tomhughes** [comment]
Actually adding per-user kill file rules might be reasonable, but adding something to the CSS that is not used by the site but exists just to support external kill files seems like a bad idea.

If only because some day somebody will notice it is "unused" and remove it...

**Comment by Nakaner** [comment]
I agree with @tomhughes. Some day people will have forgotten this feature. What about using a [data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) instead?

**Comment by tomhughes** [comment]
I'm not sure that makes the analysis any different...

**Comment by systemed** [comment]
A proper killfile would be great, but obviously a lot of engineering effort. I think this is a low-impact fix for a fairly niche case. If it breaks it breaks and I promise to re-add it when it does!

**Comment by mmd-osm** [comment]
uBlock Origin:

```
##div.diary_post:if( .clearfix.post_heading > .deemphasize > [href="/user/alexkemp"])
```

Good bye, my friend!

**Comment by gravitystorm** [comment]
@systemed Does the suggestion by @mmd-osm work for the tools you are using?

**Comment by systemed** [comment]
It's a great suggestion. Unfortunately I don't use uBO (the Safari port has been abandoned and was in any case slower than Safari's native content-blockers).

**Comment by gravitystorm** [comment]
I've ummed and aahhhed about this for weeks, since I both object to it ([for the same reasons as @tomhughes](https://github.com/openstreetmap/openstreetmap-website/pull/2266#issuecomment-502678401)) and also support it since it's pretty trivial and [nobody's going to mind if we break it in future](https://github.com/openstreetmap/openstreetmap-website/pull/2266#issuecomment-502684786). But it's not worth me considering it for any longer.

So it just comes down to having a slight bias for change. But if this gets stripped out again in a future refactoring, so be it.

**Pull request merged**
