### PR TITLE
do not allow anonymous users to comment on notes

### PR DESCRIPTION
**Pull request by woodpeck**
Implements #1543

### CODE REVIEW

**Comment by woodpeck** [comment]
Apparently the travis check for this PR failed due to some travis-internal error. Can I re-trigger the check without making an unnecessary dummy commit?

**Comment by woodpeck** [comment]
I noticed that LWG have suggested to make any acess to notes contingent on a login, including creating and reading notes. If implemented, that would make this pull request redundant.

**Comment by gravitystorm** [comment]
> I think the only question that remains is the policy one of whether we want to do this.

I think it should be merged. The evidence presented is convincing to me.

It's also a reversible change - if worst comes to worst and there's a compelling reason later on to allow anonymous comments again, we can easily do that.

**Comment by simonpoole** [comment]
And ..... what about announcing a significant behaviour change of the website?

**Comment by tomhughes** [comment]
It's not live yet.

**Comment by tomhughes** [comment]
That said we will obviously want to put it live soon so if people feel a communication strategy is necessary then now is the time to arrange it.

I'm not sure how many of the people impacted such a strategy might reach though - in reality I doubt many people other than deliberate abusers are going to be impacted at all.

**Comment by simonpoole** [comment]
I was more considering the "normal" OSM contributors as an audience for an announcement @harry-wood

**Comment by Zverik** [comment]
Awesome, thank you Andy and Tom! I will announce the change to the Russian part of the community at least :)

**Comment by mmd-osm** [comment]
Should we add a small one liner explanation that "you need to log on to comment on this note"?

**Comment by matkoniecz** [comment]
With "log on" being a link?

**Comment by RicoElectrico** [comment]
> Should we add a small one liner explanation that "you need to log on to comment on this note"?

As well as "log in to receive notifications about note status" if creating a note.

While we're at it, it'd be nice to link to the https://wiki.openstreetmap.org/wiki/Notes pages in the note creation view as well Something like: "Learn more about Notes".

**Pull request merged**
