### PR TITLE
Use https for links in e-mail notifications

### PR DESCRIPTION
**Pull request by tyll**

### CODE REVIEW

**Comment by tomhughes** [comment]
I think it's only really signup confirmation, email change confirmation and lost password where we need to do this right? In fact I'm not even sure about email change as I'm not sure if that logs you in or not.

**Comment by tomhughes** [comment]
Actually the other problem with this is that it breaks anybody deploying the code to a server without https support... So I guess we really need something in the config to say if https is available...

**Comment by tyll** [comment]
IMHO all links for registered/possible authenticated users should be https to make sure that they do not accidently use http and become a victim of a man-in-the-middle attack. Especially with openstreetmap I assume it is very common to use insecure wifi networks for example at conferences or in restaurants to contribute to it. Therefore it would be quite easy for attackers to read unencrypted traffic in these situations.
I do not know ruby on rails very good - does the notification code have access to the information about the request that triggered it so it can use the same protocol here?

**Comment by tyll** [comment]
Are there any deployments that do not use https? https://letsencrypt.org/ distributes valid certificates free-of-charge, therefore there is usually no good reason not to use https.

**Comment by bhousel** [comment]
> Are there any deployments that do not use https?

http://api06.dev.openstreetmap.org does not support it.

**Comment by tomhughes** [comment]
Yes our dev servers are a case in point, but the simple answer is that we have no idea who is using the code and in what configurations.

I also fail to see how you can MITM a link to a user from a friend message - it's a public link that anybody can visit! The links which matter are the ones that will automatically log you in, which is the signup confirmation and the password reset link and possibly the email change but I would need to check that.

I am not going to allow this PR to be used to pursue "https by default" by the backdoor. If you want to argue for that then it is a separate discussion and it's not a decision I'm going to make by myself as the primary maintainer of the code - it's a policy issue not a codign issue.

**Comment by gravitystorm** [comment]
I would suggest making this a configuration value, off by default, so that we can have it switched on for production and leave it off for e.g. api06.dev, local testing, other people's deployments etc.

From the feedback so far, the pull request is more likely to be accepted if it only affects registration-related links.

**Comment by tyll** [comment]
On Wed, Oct 26, 2016 at 08:38:58AM -0700, Tom Hughes wrote:
> Yes our dev servers are a case in point, but the simple answer is that we have no idea who is using the code and in what configurations.

Would you accept help to enable https for them by using letsencrypt
certificates?

> I also fail to see how you can MITM a link to a user from a friend
> message - it's a public link that anybody can visit! The links which
> matter are the ones that will automatically log you in, which is the
> signup confirmation and the password reset link and possibly the email
> change but I would need to check that.

AFAIU only registered users get these notifications. Therefore a MITM
attacker could include a login form in the response, keep the user on
plain http for all requests (an example attack tool is
https://moxie.org/software/sslstrip/ ) or directly read the user's
authentication cookie since it will be transmitted over plain HTTP.
Therefore if account security matters, the site should only use HTTPS.
If this is not yet possible, then it is important to make sure that
authenticated/registered users access the site only via secured HTTPS.

> I am not going to allow this PR to be used to pursue "https by
> default" by the backdoor. If you want to argue for that then it is a
> separate discussion and it's not a decision I'm going to make by
> myself as the primary maintainer of the code - it's a policy issue not
> a codign issue.

I do not want to sneak this in. Nevertheless I have the opinion that it
is the way it should be. From my point of view it is hard to understand
the criteria for which you agree that HTTPS makes sense.

**Comment by tomhughes** [comment]
Moving to letsencrypt is already on our to-do list, but it's a major project to do the necessary engineering to support it. They have raised our rate limits now which I think removes some of the problems but I still figuring out the exact design to allow us to automatically provision the required certificates.

Personally I would be quite happy to go https by default, but as you no doubt saw in the other thread where you commented we have users who don't like the idea, so our current policy on the main site is only to force https where it is actually necessary to protect user credentials.

**Comment by grischard** [comment]
Hi @tomhughes,

> I am not going to allow this PR to be used to pursue "https by default" by the backdoor. If you want to argue for that then it is a separate discussion and it's not a decision I'm going to make by myself as the primary maintainer of the code - it's a policy issue not a coding issue.

Absolutely right, and wise way of seeing things. Where do you think would be the right place to discuss https by default, or related issues like enabling HSTS?

> but as you no doubt saw in the other thread where you commented we have users who don't like the idea

For those of us who missed the beginning of the film, would you please have a link?

**Comment by tomhughes** [comment]
There are technical reasons which mean that enabling HSTS is not likely to be possible - we did try it once but it broke any site that was trying to use OAuth access to our API with http URLs because the client would sign an http URL but the browser would silently convert it to https meaning that the signature didn't match.

So we would only be able to enable HSTS once we had somehow persuaded every site that does OAuth against us to switch to HTTP URLs, and we don't even know how big that set is, let alone how to go about contacting them.

I don't think #939 is the one I was thinking of but there have been various discussions over the years where people have objected to forcing https because of the impact on people using lossy connections.

**Pull request closed without merging**
