### PR TITLE
Mark notes as important

### PR DESCRIPTION
**Pull request by OpenGreenStreet**
I would like to suggest that notes can be marked as important (high priority) in exceptional cases.

For example: a road has been closed due to construction. In my view, this is important information that should be added to OSM as soon as possible.

Background: 
I contribute to OSM mostly via StreetComplete. When things catch my eye, I leave a note. I then hope for someone with experience to implement it.

In my experience, a note can be edited very quickly but can also remain unedited for several months. (By then, the construction work may already be finished).

See also: https://github.com/streetcomplete/StreetComplete/issues/4237#issuecomment-1195414118

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
You want to open a new issue and not a pull request.

**Comment by OpenGreenStreet** [comment]
Hallo Holger,

ich konnte in Deiner Mail von eben keine Text finden.

Viele Grüße 

OpenGreenStreet

**Comment by gravitystorm** [comment]
Hi @OpenGreenStreet - as @HolgerJeromin suggests, please open an "Issue", not a "pull request", since you aren't proposing new code to implement this feature.

Or if you are proposing code, please rebase your work onto the current master branch, since this PR has somehow 294 commits in it, and I'm not going to check each one to figure out what is going on here!

**Comment by OpenGreenStreet** [comment]
Entschuldigung 

Sorry Sorry

---

Mit freundlichen Grüßen
 
Armin Krejsa
Tel.: +4933414200464
Mail: ***@***.***

Metasuchmaschine: Metager

_________________
Stromspeicherung (Power-to-X) und 100% Erneuerbare Energien für eine sichere, importunabhängige & brennstoffkostenfreie Energieversorgung | regionale Arbeitsplätze, Demokratie & Wertschöpfung | Frieden & Klimaschutz
-
100 Prozent Erneuerbare Energien so schnell als möglich: Eurosolar | Deutsche Gesellschaft für Sonnenenergie (DGS) | Solarenergie-Förderverein Deutschland (SFV)

Am 26.07.22 um 16:41 schrieb Andy Allan

Closed #3622.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/openstreetmap/openstreetmap-website/pull/3622#event-7065581704

**Pull request closed without merging**
