### PR TITLE
promote yourself to superuser

### PR DESCRIPTION
**Pull request by openbrian**
If your database already has this user you'll need to promote the user to superuser.

### CODE REVIEW

**Comment by tomhughes** [comment]
No, deciding whether to promote your main development user to a database user is a personal decision that should be made with an understanding of the issues involved and not one we should encourage people to make unthinkingly.

**Comment by woodpeck** [comment]
Perhaps we should then at least write something like "note, some automated tests that try to execute CREATE EXTENSION commands on the database will fail when not run as a privileged database user"?

**Comment by tomhughes** [comment]
Well we need to quantify the actual problem before we can formulate a solution - in other words under what circumstances in the permission required.

There probably aren't any good solutions sadly.

**Comment by openbrian** [comment]
Before I take a second stab at this can you tell me what you mean by "your current user".  For me that's brian@localhost on a debian system.  The problem was when I ran automated tests, they failed with the CREATE EXTENSION command.

Perhaps the issue is with these words "your current user".  Instead it should be "a newly created user that will own the openstreetmap database".  Thoughts?

Side note, you don't need superuser "so that we can create more databases".  That can be granted to a user.

**Comment by tomhughes** [comment]
Well the general point is that you shouldn't be throwing around postgres superuser privileges without understanding what you are doing.

Ideally there would be a single step that you could execute as the postgres user but as I say I'm not sure if that's actually possible.

It may be that we should recommend an initial run of `rake test:db` as a database superuser to populate the test database but as I say it needs some research to see if that is good enough or under what circumstances rails may try and recreate the test database from scratch.

**Comment by openbrian** [comment]
I found a way around this issue.  It's to use a template database.  PG 9.5 add the IS_TEMPLATE option to CREATE DATABASE.  If true, anyone with CREATEDB privilege can clone it.  If the template has the btree_gist extension, the new database will also have it.

**Comment by openbrian** [comment]
I've done just a little research and found that rails does have some support for this.  See activerecord-5.2.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb, line 30.  Though I'm not sure how easy this is to use.

**Pull request closed without merging**
