### PR TITLE
Upload profile picture with standard image formats

### PR DESCRIPTION
**Pull request by Revathyne**
I have made profile pictures to be uploaded only with PNG, JPG, GIF, and JPEG formats, before which images can be uploaded with any extension such as .rb, .pdf, etc.

### CODE REVIEW

**Comment by tomhughes** [comment]
Why? What's wrong with the other formats we support?

**Comment by Revathyne** [comment]
While adding images we can add files with all extensions. Sometimes while adding files with other extensions can affect the application security.

**Comment by tomhughes** [comment]
Do you have any evidence that this is creating a security hole? That we're somehow handling those files in a way that  is impacting security?

At the very least there are obvious extensions like BMP, TIFF and SVG missing, all of which I am pretty sure that people are using.

Better would be to ask the storage pipeline if it is able to handle the file as an image.

**Comment by tomhughes** [comment]
Ideally it should call https://api.rubyonrails.org/classes/ActiveStorage/Blob.html#method-i-image-3F but without trying it I don't know exactly how that will interact with validations in terms of when the blob object for the field is created.

**Comment by Revathyne** [comment]
Currently, I don't have any evidence about creating a security hole, but hackers can add vulnerable files with any extensions. Yes extensions like BMP, TIFF, and SVG can also be added. 
I agree with you that without trying we cannot make sure how things will work. Hope you will find some fix for this. Thanks.

**Comment by grischard** [comment]
We currently support a lot of crap that imagemagick does. Having a wide variety of formats open increases the possibility of having malicious javascript masquerading as an image file.

**Comment by tomhughes** [comment]
None of which changes the fact that this PR doesn't actually even work, because `image` is not a known attribute on the user model so you just get an exception when it tries to run the validations...

**Comment by tomhughes** [comment]
I pushed 3c4f32a76075e91d60efd82c91bd64ebff5b6082 which will hopefully do the job - it's a little tricky as there is no official way to work out if an attachment has changed.

**Comment by Revathyne** [comment]
3c4f32a works perfectly fine. :)

**Pull request closed without merging**
