### PR TITLE
Update to iD v2.17.3

### PR DESCRIPTION
**Pull request by quincylvania**
#### :mega: Release Highlights
* :mask: You can now specify when places are open during coronavirus lockdowns with the COVID-19 Pandemic Hours field

#### :boom: Breaking Changes
* Rename the default branch, previously `2.x`, to `develop`
* Rename the v3 beta branch, previously `master`, to `v3-prototype`
* Update links to iD's documentation on GitHub for the changed branch names ([#7453])
* Update iD's privacy policy to reflect the changed branch names

[#7453]: https://github.com/openstreetmap/iD/issues/7453

#### :sparkles: Usability
* Use custom line styling for non-asphalt, non-unpaved surfaces like cobblestone, sett, and metal ([#7466])
* Style pedestrian streets as wider and distinct from corridors ([#7058])
* Style `planned` but not `disused` features with a dashed stroke

[#7058]: https://github.com/openstreetmap/iD/issues/7058
[#7466]: https://github.com/openstreetmap/iD/issues/7466

#### :white_check_mark: Validation
* Upgrade `car` to `motorcar` on vehicle charging stations ([#7339], thanks [@nlehuby])
* Warn about ways crossing highway areas ([#7455])
* Don't suggest adding bridges or tunnels to ways crossing highway multipolygons ([#7472])
* Don't suggest adding tunnels to highways crossing waterways ([#7447])
* Deprecate `bicycle:oneway` key ([#7281])
* Deprecate `building:height` and `building:min_height` keys ([#7285])
* Deprecate tags: `bridge=1`, `building:material=Brick`, `disabled_spaces`, `man_made=telephone_exchange`, `tunnel=1`

[#7455]: https://github.com/openstreetmap/iD/issues/7455
[#7472]: https://github.com/openstreetmap/iD/issues/7472
[#7447]: https://github.com/openstreetmap/iD/issues/7447
[#7339]: https://github.com/openstreetmap/iD/issues/7339
[#7281]: https://github.com/openstreetmap/iD/issues/7281
[#7285]: https://github.com/openstreetmap/iD/issues/7285

[@nlehuby]: https://github.com/nlehuby

#### :bug: Bugfixes
* Fix issue where some labels could not be translated ([#7358])
* Don't insert generic values when focusing the Information Board, Bridge Area, or Tunnel Area Type fields ([#7265], [#7509])

[#7358]: https://github.com/openstreetmap/iD/issues/7358
[#7265]: https://github.com/openstreetmap/iD/issues/7265
[#7509]: https://github.com/openstreetmap/iD/issues/7509

#### :rocket: Presets
* Add Exhibition Center preset ([#7268], thanks [@hikemaniac])
* Add Spike Strip preset ([#7347], [#7354], thanks [@animesh-007])
* Add Mountain Rescue preset ([#7296], [#7323], thanks [@animesh-007])
* Add Kneipp Water Cure preset ([#7313], [#7332], thanks [@animesh-007])
* Add Historic Pillory preset ([#7274], [#7310], thanks [@animesh-007])
* Correct tags of Community Garden preset and add Garden Allotments preset ([#7501], thanks [@stragu])
* Add Garden Type field to Garden ([#7501], thanks [@stragu])
* Add more fields to advertising presets ([#7289], thanks [@ToastHawaii])
* Add Depth field to Ford ([#7400], thanks [@hikemaniac])
* Support `internet_access:fee=customers` tag ([#7442], thanks [@Lukas458])
* Add more fields to Wayside Cross ([#7521], thanks [@morray])
* Add more search terms for Research Office ([#7284], thanks [@ferdinand0101])
* Add a preset and field for accessible parking spaces ([#7465])
* Add Disused Shop preset ([#7407])
* Add Cycle & Foot Path preset ([#7321])
* Add Telecom Exchange preset ([#6780])
* Add Shrub preset ([#7482])
* Add Boardwalk preset and styling ([#7518])
* Add presets: Botanical Garden, Hanging Monorail, Heritage Railway Track, Household Linen Shop, Power Cable, Trampoline Park, Trolleybus Route
* Rename railway track presets to be more precise, e.g. "Subway" to "Subway Track" ([#7440])
* Add COVID-19 Pandemic Hours field to points of interest ([#7529])
* Add Mimics field to Mobile Phone Mast ([#7452])
* Add Tactile Paving field to Bus Stop presets ([#7307])
* Add Circumference field to Tree ([#7371])
* Add additional fields to Water Park ([#7488])
* Add Smoothness field to service road presets ([#7477])
* Add Operator Type field to the Kindergarten preset ([#7494])
* Add Stop Number field to transit stop presets ([#7492])
* Support multiple values in the `beauty` field ([#7215])
* Show Hours field by default on Recycling Container ([#7259])
* Improve placeholders for date fields ([#7270])
* Remove Level field from transit stopping location presets ([#7499])
* Remove Network Type field from transport route presets ([#7493])
* Remove Collection Times field from Letter Box ([#7487])
* Remove the Elevation field from arbitrary line, area, and relation features ([#7479])
* Don't add `building` tag to the Monastery Grounds preset by default ([#7287])
* Add search terms to Retail Building and Farm Building ([#7392], [#7394])
* Update icons for railway track presets ([#7255])
* Update icons for public transit presets
* Update Nail Salon icon ([#7476])
* Update Kebab Fast Food icon ([#7475])
* Update Power Pole icon ([#7516])
* Update icons for presets: Community Garden Plot, Bicycle Lockers, Parking Space, Quaker Meeting House, Police, RV Toilet Disposal, Town Hall, City Hall, Government Office, Bollard, Bollard Row, Border Control, Cycle Barrier, Trench, Hedge, Stile, Carport, Static Mobile Home, Caterer, Floorer, Parquet Layer, Plasterer, Scaffolder, Stonemason, Tiler, Disused Railway Feature, Golf Course, Golf Hole, Miniature Golf, Access Aisle, Motorsport Racetrack, Karting Racetrack, Racetrack (Non-Motorsport), Barracks, Naval Base, Military Obstacle Course, Military Range, Plant Nursery, Quarry, Field Hockey Pitch, Adit, Bunker Silo, Mineshaft, Observatory, Pumping Station, Survey Point, Water Works, Military Checkpoint, Military Trench, Cliff, Heath, Ridge, Saddle, Scrub, Valley, Rail Yard, Curtain Store, Deli, Fireplace Store, Pet Grooming Store, Spice Shop, Tattoo Parlor, Tile Shop, Weapon Shop, Speed Bump, Chicane, Speed Cushion, Speed Dip, Speed Hump, Rumble Strip, Speed Table, Power Feature, Railway Feature, Notice Board, Poster Box, Information Board, Information Terminal, Goods Aerialway, Airport, Apron, Airport Gate, Hangar, Aircraft Holding Position, Aircraft Parking Position, Taxiway, Windsock

[#7518]: https://github.com/openstreetmap/iD/issues/7518
[#7529]: https://github.com/openstreetmap/iD/issues/7529
[#7521]: https://github.com/openstreetmap/iD/issues/7521
[#7516]: https://github.com/openstreetmap/iD/issues/7516
[#7268]: https://github.com/openstreetmap/iD/issues/7268
[#7347]: https://github.com/openstreetmap/iD/issues/7347
[#7354]: https://github.com/openstreetmap/iD/issues/7354
[#7296]: https://github.com/openstreetmap/iD/issues/7296
[#7323]: https://github.com/openstreetmap/iD/issues/7323
[#7313]: https://github.com/openstreetmap/iD/issues/7313
[#7332]: https://github.com/openstreetmap/iD/issues/7332
[#7274]: https://github.com/openstreetmap/iD/issues/7274
[#7310]: https://github.com/openstreetmap/iD/issues/7310
[#7501]: https://github.com/openstreetmap/iD/issues/7501
[#7289]: https://github.com/openstreetmap/iD/issues/7289
[#7400]: https://github.com/openstreetmap/iD/issues/7400
[#7442]: https://github.com/openstreetmap/iD/issues/7442
[#7284]: https://github.com/openstreetmap/iD/issues/7284
[#7465]: https://github.com/openstreetmap/iD/issues/7465
[#7407]: https://github.com/openstreetmap/iD/issues/7407
[#7321]: https://github.com/openstreetmap/iD/issues/7321
[#6780]: https://github.com/openstreetmap/iD/issues/6780
[#7482]: https://github.com/openstreetmap/iD/issues/7482
[#7440]: https://github.com/openstreetmap/iD/issues/7440
[#7452]: https://github.com/openstreetmap/iD/issues/7452
[#7307]: https://github.com/openstreetmap/iD/issues/7307
[#7371]: https://github.com/openstreetmap/iD/issues/7371
[#7488]: https://github.com/openstreetmap/iD/issues/7488
[#7477]: https://github.com/openstreetmap/iD/issues/7477
[#7494]: https://github.com/openstreetmap/iD/issues/7494
[#7492]: https://github.com/openstreetmap/iD/issues/7492
[#7215]: https://github.com/openstreetmap/iD/issues/7215
[#7259]: https://github.com/openstreetmap/iD/issues/7259
[#7270]: https://github.com/openstreetmap/iD/issues/7270
[#7499]: https://github.com/openstreetmap/iD/issues/7499
[#7493]: https://github.com/openstreetmap/iD/issues/7493
[#7487]: https://github.com/openstreetmap/iD/issues/7487
[#7479]: https://github.com/openstreetmap/iD/issues/7479
[#7287]: https://github.com/openstreetmap/iD/issues/7287
[#7392]: https://github.com/openstreetmap/iD/issues/7392
[#7394]: https://github.com/openstreetmap/iD/issues/7394
[#7255]: https://github.com/openstreetmap/iD/issues/7255
[#7476]: https://github.com/openstreetmap/iD/issues/7476
[#7475]: https://github.com/openstreetmap/iD/issues/7475

[@morray]: https://github.com/morray
[@hikemaniac]: https://github.com/hikemaniac
[@animesh-007]: https://github.com/animesh-007
[@stragu]: https://github.com/stragu
[@ToastHawaii]: https://github.com/ToastHawaii
[@Lukas458]: https://github.com/Lukas458
[@ferdinand0101]: https://github.com/ferdinand0101

#### :hammer: Development
* Define the main package file as `dist/iD.min.js` ([#7449], thanks [@willemarcel])
* Scope iD's CSS to its container under the `ideditor` class ([#7437])
* Make embedded iD's container a local stacking context ([#7457])
* Fix combobox suggestion list placement when embedding iD ([#7458])
* Persist the changeset comment, hashtags, and sources from the URL through UI reloads ([#7504])

[#7449]: https://github.com/openstreetmap/iD/issues/7449
[#7437]: https://github.com/openstreetmap/iD/issues/7437
[#7457]: https://github.com/openstreetmap/iD/issues/7457
[#7458]: https://github.com/openstreetmap/iD/issues/7458
[#7504]: https://github.com/openstreetmap/iD/issues/7504

[@willemarcel]: https://github.com/willemarcel

### CODE REVIEW

**Comment by tomhughes** [comment]
Not sure what's going on but this seems to be totally broken as far as I can tell - most of the UI never appears at all and all I get is a mangled search box. Here's what it looks like in chrome:

Screenshot from 2020-04-26 18-42-47

There's nothing much in the way of errors in the console though to give a clue to what's going on :-(

**Comment by mmd-osm** [comment]
Confirmed, it's completely dead. No errors on the javascript console.

dead

**Comment by quincylvania** [comment]
@tomhughes @mmd-osm Oops, thanks for noticing this. We changed the CSS so iD itself won't style the `<html>` or `<body>` elements in case a client app is embedding iD without an iframe. I'll look into a workaround here.

**Comment by quincylvania** [comment]
In 4dd9ea34bc6675540c80b6cc186c77cd1f7b7f27 I updated `app/views/site/id.html.erb` to include the necessary document-level styling. This fixes the problem. Please adjust the implementation as necessary, I'm not familiar with the code patterns of the rails port.

**Comment by tomhughes** [comment]
Well inline styles are generally prohibited, though there is an exemption for some iD thing, so I'll probably move it to a style sheet but I'll have a look in a bit.

**Comment by tomhughes** [comment]
Specifically https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/stylesheets/id.css would be the place - currently that just pulls in the upstream iD style sheet but it could have it's own rules.

**Comment by quincylvania** [comment]
> Specifically https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/stylesheets/id.css would be the place

@tomhughes Thanks for the tip, I've moved the CSS there.

**Pull request merged**
