### PR TITLE
[Discussion] Refactors from RFG 2018

### PR DESCRIPTION
**Pull request by benreyn**
This PR contains all of our larger refactor efforts from Ruby for Good 2018. Just oppening this PR to discuss some of the changes. Anything that individually looks good to merge as is we can cheery pick onto master. 

Highlights indclude...

1. Renaming some `view` controller actions to the more Rails standard `show`
2. Rubocop fixes
3. Renaming `UserController` to more standard naming of `UsersController` 
4. Various other flattening of routes and steps toward a more resourceful routing strategy.

Ill answer as many questions about these changes as I can, but feel free to also ping the original authors.

### CODE REVIEW

**Comment by tomhughes** [comment]
This is so large I'm not sure there's really any meaningful way to analyse or review it...

One thing I can say is that whatever has changed all those language files will need to go - only `en.yml` should be changed and all other translations will then update via TranslateWiki.

**Comment by benreyn** [comment]
Understood on translation files, we weren't aware of the TranslateWiki workflow at the time. I assumed you would just view the diffs on individual commits. Would it be easier for me to cherry pick commits on to their own branches on our fork and submit individual PRs that way?

**Comment by gravitystorm** [comment]
@benreyn thanks for the PR, and all the work that everyone put in during RFG. Sorry for the radio silence recently - I've been busy with other OSMF tasks. 

There's a lot in here to look through and I'll make my way through it. There's some workflow changes needed to make these into PRs, in particular around the translations when renaming controllers and actions (see e.g. https://github.com/openstreetmap/openstreetmap-website/pull/1892 https://github.com/openstreetmap/openstreetmap-website/pull/1858  https://github.com/openstreetmap/openstreetmap-website/pull/1857 https://github.com/openstreetmap/openstreetmap-website/pull/1851 for how we notify i18n changes). But we can figure out how best to deal with them as we get there.

**Comment by gravitystorm** [comment]
There's was a lot of fixup commits, and branch merges seem to have confused either me or github or both. So I've gone through all the commits to make a summary of what different topics were covered in here:

- [ ]  Refactor api methods into their own namespaced controllers (e.g. app/controllers/api/nodes_controller.rb)
- [ ]  Rubocop numeric predicates (foo < 0  becomes foo.negative?)
- [ ]  Resourceful naming for nodes_controller
- [ ]  Rubocop if/unless modifier
- [ ]  Rename usercontroller to userscontroller
- [ ]  Resourceful naming for userscontroller
- [ ]  Rubocop safe navigation
- [ ]  Rubocop assignment in condition
- [ ]  Rubocop ambiguous regexp literal
- [ ]  Rubocop shadowingouterlocalvariable
- [ ]  Rubocop ambiguous operator
- [ ]  Guard against undefined CSP_ENFORCE constant

I plan to work through this list, split some straightforward things off into their own PRs and then see what we're left with!

**Comment by benreyn** [comment]
Hey @gravitystorm, wanted to pop in an thank you for helping move this forward. Ive been swamped with a combination of work and moving and havent had time to help out. Im starting to have some more availability recently, feel free to ping me to be helpful in anway that I can. If you want me to pick off something from this checklist I can do so this weekend, just let me know what you want me to grab.

**Comment by mmd-osm** [comment]
The GPX import part, or more specifically, generating animated gifs, would be a good topic with some FFI stuff involved: https://github.com/dark-panda/gd2-ffij/issues/18

**Comment by gravitystorm** [comment]
With #2118 we've now completed (almost) all the topics that were considered in RFG 2018. There's a couple of minor rubocop fixes that I'm going to leave for another time, and refactoring API controllers is on my TODO but will be another significant piece of work and might take a while to complete. So I'm happy to close this discussion for now!

My thanks go to everyone involved in RFG 2018, your work was very helpful and I hope we can get involved again in 2019.

**Pull request closed without merging**
