### PR TITLE
Add updated authentication logos

### PR DESCRIPTION
**Pull request by mxdanger**
Made changes to the authentication logos on the sign in screen:

* Replace previous outdated authentication logos with new SVG logos.
* Add border-radius for consistent shape between all logos.

Side by side difference between the SVG icons and the old PNG icons:
Windows File Explorer screenshot
Windows File Explorer screenshot

This pull request needs testing.

### CODE REVIEW

**Comment by tomhughes** [comment]
Is going SVG only safe from a compatibility point of view? Everywhere where we have used SVG to date we have done so using a `picture` element with a PNG fallback.

**Comment by mxdanger** [comment]
> Is going SVG only safe from a compatibility point of view? Everywhere where we have used SVG to date we have done so using a `picture` element with a PNG fallback.

You raise a good point, however, what exactly is the minimum browser target for the website so we can get an idea? Depending on what we need to support, is there really any reason to keep using png fallback?

Every major browser dating back ten or so years supports SVG and all of the xml data in the minified svg files.

**Comment by mxdanger** [comment]
> Is going SVG only safe from a compatibility point of view? Everywhere where we have used SVG to date we have done so using a `picture` element with a PNG fallback.

Going SVG only is very safe from a compatibility point of view. Browsers support for SVG is [99.82% on desktop and 100% on mobile](https://caniuse.com/svg). There's just no practical reason to need the fallback method as that would mean needing to maintain both the vector and raster image.

**Comment by mxdanger** [comment]
All that's left to do is wait for someone to test this branch and provide feedback on any potential issues.

**Comment by HolgerJeromin** [comment]
We should/could drop the `<picture>` elements in the future. Not really needed nowadays anymore.

**Comment by gravitystorm** [comment]
Merged in #3009, with just a small update to avoid using custom CSS and to use a bootstrap utility class instead.

**Pull request closed without merging**
