### PR TITLE
WIP: search forms redesign

### PR DESCRIPTION
**Pull request by mjourdan**
This branch is have an example of how #3123 could be implemented. Here is a screenshot:

image

### CODE REVIEW

**Comment by gravitystorm** [comment]
Thanks for the mockup. I didn't realise until reviewing that it's a mockup rather than a proposal (i.e. there's a hardcoded options list, none of the buttons work) so I've converted this to a draft.

I think this highlights that we need to change the secondary button colour, since it's quite a dark shade of grey compared to our blue and green colours.

I don't think primary is the correct choice for the type-of-route buttons, since that's not actually an action on the form, rather it's a toggle choice. I would like to keep the primary colour for the main action (i.e. "click here to make something happen now").

* Talking of which, there's no button to make the routing happen now. Is that deliberate?
* How do you propose to handle situations where there are either more or fewer types of routing available? Different engines might have different lists of options (e.g. off-road cycling, skating, only car etc).
* Where do the icons come from? There's no attribution afaict. 
* The icons seem a bit inconsistent e.g. the weight of the arrows compared to the weight of the cross symbol. Do they all come from the same icon set?

(For icon sets, perhaps https://icons.getbootstrap.com/ would be useful.)

**Comment by mjourdan** [comment]
Yes, this was meant as a prototype rather than a fully fledged implementation. Thanks for taking a look at it.

> Talking of which, there's no button to make the routing happen now. Is that deliberate?

Yes, filling in the two fields and pressing enter should be sufficient to get the results

> How do you propose to handle situations where there are either more or fewer types of routing available? Different engines might have different lists of options (e.g. off-road cycling, skating, only car etc).

The options would be updated according to the selected engine.

> Where do the icons come from? There's no attribution afaict.
> The icons seem a bit inconsistent e.g. the weight of the arrows compared to the weight of the cross symbol. Do they all come from the same icon set?

 It's true they are inconsistent. Arrows come from bootstrap, but I had to get the others from elsewere (ie gnome), as [evocated here](https://github.com/openstreetmap/openstreetmap-website/issues/3123#issuecomment-803141517).

Here is a small update after switchingfrom btn-primary to btn-light:

image

**Comment by gravitystorm** [comment]
@mjourdan Thanks for your design suggestions. I'm not sure what the next steps would be, since this is only a prototype and I don't know if anyone is going to attempt to implement it. We already have the issue open - do we need to keep this PR open too?

**Comment by mjourdan** [comment]
Closing this PR and keeping the issue open makes sense.

**Pull request closed without merging**
