### PR TITLE
Set minimum changeset size in pixels

### PR DESCRIPTION
**Pull request by jguthrie100**
Changed the minimum changeset width to be in pixels rather than degrees.

When zooming out, the minimum pixel width is maintained, so even when max-zoomed out, the pixel width will be 40px (width could be easily edited)

### CODE REVIEW

**Comment by jguthrie100** [comment]
image

image

image

image


To be honest, I'm not sure if its an improvement or not. It seems a bit unintuitive when zoomed out

**Comment by jguthrie100** [comment]
image

Its not so bad at distance actually when you consider how small the different changesets would be

**Comment by jguthrie100** [comment]
Actually, I take it back. There is a considerable improvement to the current implementation which shows just tiny dots!

image

**Comment by uswoods** [comment]
_To be honest, I'm not sure if its an improvement or not. It seems a bit unintuitive when zoomed out._

Indeed, sir! You should better revert this change.

**Comment by tomhughes** [comment]
I wasn't aware that two people in a forum thread were "the community". Is there anything else they'd like a veto on?

**Pull request merged**
