### PR TITLE
Renaming: "ku.json" --> "ckb.json"

### PR DESCRIPTION
**Pull request by Ghybu**
Renaming: The translation is in the  Sorani language ("ckb"). The code "ku" is currently used for the Kurmandji language which uses the Latin script.

### CODE REVIEW

**Comment by bhousel** [comment]
Hi @Ghybu,  this language is listed as `ku` because that is how it appears on Transifex:
https://www.transifex.com/ideditor/id-editor/language/ku/

If this is incorrect, you can try to contact whoever has supplied the `ku` translations there, or just fix them yourself by opening an account.  If you need to add `ckb` translation, Transifex is also the place to make that request.

iD just pulls the translated strings automatically from there, and includes them in our distribution, which gets later vendored into the openstreetmap-website.  So renaming the file won't help here as it will just get overwritten the next time we release a new version of iD.   Thanks!

**Comment by Ghybu** [comment]
Thanks for your quick reply! 
I just wanted to add that translations also do "translatewiki.net". And that the code "ku" was used for the Latin script.

PS: Can we add the file "ku.yml", here: https://github.com/openstreetmap/openstreetmap-website/tree/master/config/locales

Translations are done here:
https://translatewiki.net/w/i.php?title=Special:Translate&group=out-osm-0-all&language=ku-latn&filter=%21translated&action=translate

**Comment by tomhughes** [comment]
@Ghybu it will be added as soon as there are enough translations for Translatewiki to think it worth exporting. You'd have to ask them what threshold they use.

**Comment by nemobis** [comment]
The threshold is currently 35 %. Continuing at <https://translatewiki.net/wiki/Thread:Translating_talk:OpenStreetMap/Kurdish_Translation_(ku-latn)>

**Pull request closed without merging**
