### PR TITLE
Update to iD v2.20.4

### PR DESCRIPTION
**Pull request by tyrasd**
#### :bug: Bugfixes
* Fix rendering of HTML content in KeepRight and ImproveOSM issues ([#8928])
* Fix "local storage is exceeded" error message showing up multiple times ([#8930])

[#8928]: https://github.com/openstreetmap/iD/pull/8928
[#8930]: https://github.com/openstreetmap/iD/pull/8930

### CODE REVIEW

**Comment by cicku** [comment]
I was not able to see the imagery index updated to a recent level, would you please pull it again? 2.20.3 misses at least imageries added 2 weeks before 01/28.

**Comment by tyrasd** [comment]
Hmm… that's odd. I did run the necessary build instruction as documented in the [releasing checklist](https://github.com/openstreetmap/iD/blob/develop/RELEASING.md#release-checklist). But I will double-check it now. Thanks for the heads-up.

**Comment by tyrasd** [comment]
OK, I have re-released 2.20.4 now actually including fresh imagery data :crossed_fingers:

**Comment by cicku** [comment]
Thank you and I think it works. Not sure why previously it did not fetch from the HEAD.

**Pull request merged**
