### PR TITLE
Tab icon for Safari/Touchbar

### PR DESCRIPTION
**Pull request by thomersch**
In Safari (the browser) you can now pin tabs in the browser as in e.g. Chrome, which takes a special single-coloured SVG and a tint-color in order to display an icon for the pinned tab.
screen shot 2016-11-28 at 19 23 20

It even shows up as an icon on the touchbar. Yes, I know, fancy.
img_5205

As I haven't done anything with Rails before, I hope I did it right. Let me know if not :)

### CODE REVIEW

**Comment by tomhughes** [comment]
The code is fine, but I can't say I'm entirely happy about having a whole new version of the icon that will just get out of sync with the others... Not to mention yet another browser specific icon :-(

**Comment by tomhughes** [comment]
I'm also confused as you seem to say this is a Safari thing, but then you mention Chrome? Do they both make use of it?

**Comment by HolgerJeromin** [comment]
The term Chrome is often used for the browser gui. But I am not sure if Tom meant this.

**Comment by thomersch** [comment]
It's only for Safari. I referred to Chrome, because it had the "tab pinning" feature first.

Totally understand your feeling, if you say it's too much, I would be fine with that. It was just quick to build and I think it just looks nice.
I wouldn't be surprised though, if Safari/iOS would stop requiring all those crazy PNGs and use the SVG instead in the future.

**Pull request closed without merging**
