### PR TITLE
Bump copyright string version to force re-translation

### PR DESCRIPTION
**Pull request by simonpoole**
This should force re-translation of one section in the copyright page that didn't get its "version" bumped.

### CODE REVIEW

**Comment by simonpoole** [comment]
PS: note that I did this correctly in the original PR, it seems as if the translators simply C&P'd the old text back in, so we might be in for multiple iterations of this.

**Comment by tomhughes** [comment]
If we've already bumped it once and the text hasn't changed since then there is clearly no point in just bumping it again - people that do the right thing will just have to repeat work they've already done and people that don't still won't.

**Comment by simonpoole** [comment]
Well I originally thought it was my mistake, but the thing is that outside of getting people to actually look at the text again there is no way forward.

**Comment by simonpoole** [comment]
Maybe @translatewiki has a suggestion on how to deal with this.

**Comment by gravitystorm** [comment]
> This should force re-translation of one section in the copyright page that didn't get its "version" bumped.

Note that this definitely won't work as intended. Translatewiki now handles "translation key renames" automatically, which was partly driven by the refactoring work that we've been doing (e.g. renaming controllers leading to mass renaming of translation keys). So translatewiki will recognise this as a translation key rename, since the value hasn't changed, and automatically copy over all the existing translations from the old key to the new key.

**Comment by gravitystorm** [comment]
I'm going to close this PR, since it can't be merged, and to avoid confusion. I think that getting translators to re-translate an existing string needs to be managed through the translatewiki interface, ideally for only those translations that are known to be defective. If you want to open an issue to describe or discuss or track the progress in fixing the translations, that would be fine with me.

**Comment by simonpoole** [comment]
> 
> Note that this definitely won't work as intended. Translatewiki now handles "translation key renames" automatically, which was partly driven by the refactoring work that we've been doing (e.g. renaming controllers leading to mass renaming of translation keys). So translatewiki will recognise this as a translation key rename, since the value hasn't changed, and automatically copy over all the existing translations from the old key to the new key.

So this was likely the problem to start with? As in the translation system is now completely broken?

**Comment by tomhughes** [comment]
It's "broken" for this use case but "fixed" for some other use cases. So maybe we should all just calm down a bit and lets work out how we can address this instead of getting agro...

**Comment by mvl22** [comment]
As background: This arose from our request:

https://twitter.com/cyclestreets/status/1320462262440701955

**Comment by simonpoole** [comment]
@mvl22 the problem is that it effects all translations (~100) not just the, slightly comical, en-GB one, which could naturally be fixed manually as a one off.

**Comment by mvl22** [comment]
Could someone kindly clarify what the way forward is on getting the copyright statement updated? (I regret I wasn't totally clear from Andy's posting, not being familiar with how things are set up.) It seems pretty critical to me that the tiles are being advertised as the wrong license now.

(I know that reviewers at PLOS are still rejecting author maps unnecessarily because it states these are still the old license.)

**Comment by tomhughes** [comment]
The statement has been updated. I mean I know PLOS are idiots (or we wouldn't be here in the first place) but surely they aren't relying on the translated string on the web site instead of going and reading the actual license?

**Comment by tomhughes** [comment]
But basically if you want it "fixed" in a particular translation that head over to Translatewiki and fix it.

**Comment by mvl22** [comment]
> The statement has been updated.

Can you point me where?

https://www.openstreetmap.org/copyright
still says that the tiles are licensed under Creative Commons.

I am trying to help out a researcher who is dealing with PLOS, but sending them this discussion or the blog post isn't going to cut it, when the official copyright page says precisely the opposite.

Sorry that I don't understand the technicalities of how pages are generated so cannot update this myself, nor would I feel confident making any such a critical content change even if I did.

**Comment by tomhughes** [comment]
Right at the top of that page it gives you a link to the canonical english version (https://www.openstreetmap.org/copyright/en) if that's not the version you're looking at. That version says:

```
The map tiles in the “standard style” at www.openstreetmap.org are a Produced Work by the OpenStreetMap Foundation using OpenStreetMap data under the Open Database License. If you are using these tiles please use the following attribution: “Base map and data from OpenStreetMap and OpenStreetMap Foundation”. 
```

Which does not mention CC anywhere.

**Comment by mvl22** [comment]
> Right at the top of that page it gives you a link to the canonical english version (https://www.openstreetmap.org/copyright/en) if that's not the version you're looking at.

Thanks - that makes sense now.

I will point them to that.

**Comment by mvl22** [comment]
Well, guess what after all that...

"Please note, however, that the Open Database License is not compatible with PLOS ONE's copyright license either. [...]"

**Comment by simonpoole** [comment]
@mvl22 well I don't think we can provide a solution to people being wrong.

**Comment by simonpoole** [comment]
@mvl22 a good source (PLOS ONEs boss :-)) has now confirmed that the licence change for tiles has been reviewed by their lawyers and is now considered compatible with their licence. Naturally that doesn't mean that is going to trickle down to the reviewers any time soon.

**Comment by mvl22** [comment]
I see that PLOS ONE have now published the change of policy:

https://journals.plos.org/plosone/s/figures#loc-maps


> Several sites provide maps that are compatible with CC BY licensing, including:
> [...]
> OpenStreetMap: OpenStreetMap map tiles are free to use as long as they are accompanied by the following attribution statement: “Base map and data from OpenStreetMap and OpenStreetMap Foundation”. Maps created using OpenStreetMap data must be accompanied by the following attribution statement: "Contains information from OpenStreetMap and OpenStreetMap Foundation, which is made available under the Open Database License.”

which is great news.

**Pull request closed without merging**
