### PR TITLE
Sakthivel/#3910

### PR DESCRIPTION
**Pull request by Vel-12**
Issue/#3910 Fixed.

### CODE REVIEW

**Comment by Vel-12** [comment]
I have added in common.scss
[dir=rtl] {
  /* no-r2 */ text-align: right;
   
   .form-control {
   text-align: right;
  }
}

[dir=ltr] {
  /* no-r2 */ text-align: left;
}

**Comment by tomhughes** [comment]
You've also reformatted the entire file in the same commit - please don't mix reformatting in with functional changes but instead make it a separate PR or at least a separate commit.

**Comment by Vel-12** [comment]
ok

**Comment by tomhughes** [comment]
You didn't need to close this - you can just force push a fixed version of the branch and the PR will update.

**Comment by Vel-12** [comment]
Sry my bad, I have made a new PR with README.md updated

**Pull request closed without merging**
