### PR TITLE
Routing sprites to SVG

### PR DESCRIPTION
**Pull request by hiddewie**
Part of https://github.com/openstreetmap/openstreetmap-website/issues/850

Split off from https://github.com/openstreetmap/openstreetmap-website/pull/4775

This pull request replaces PNG icons for the routing to their minimized SVG variants, to ensure screens with high pixel densities can display the OpenStreetMap website with beautiful graphics.  

Tested on http://127.0.0.1:3000/directions?engine=fossgis_osrm_car&route=52.0991%2C4.2970%3B51.9244%2C4.4778#map=11/52.0130/4.3863&layers=N

image

### CODE REVIEW

**Comment by tomhughes** [comment]
Is there a good reason to minimize the source when we run them all through `svgo` before serving them in production?

**Comment by hiddewie** [comment]
> Is there a good reason to minimize the source when we run them all through svgo before serving them in production?

2 main reasons for me:
- For example https://www.openstreetmap.org/assets/sprite-e144d5cba10d95411535e0f63a538f760b299585fa9726c2ba8a37e3a6164300.svg and https://www.openstreetmap.org/assets/osm_logo-4afddaae0230a5a46687fdc751ed256dfdccde144118cb02a7d7960f207a4b92.svg (2 SVGs fetched from the frontpage): they contain unneeded attributes, whitespace and even some personal information like filenames. Minimizing them with a tool, and then by hand, makes the files smaller than can be achieved automatically. Maybe the tool can be configured better to remove unneeded attributes, but this also works.
- Reviewing changes is easier when the SVG content is much smaller. Although I must admit that having newlines instead of a single huge long line is easier to read. I might add in newlines again in all these SVGs.

**Comment by tomhughes** [comment]
Being able to review changes is something that definitely counts against full minimisation. I don't mind it being reduced to a nicely formatted handwritten SVG standard but full machine minimisation will make review of future changes hard.

**Comment by hiddewie** [comment]
Yes I agree. In the entire SVG series I have re-added all newline/indent whitespace to ensure the SVG itself looks somewhat nice to humans.

A simple diff should be reviewable code-wise, although the illustrations in e.g. https://github.com/openstreetmap/openstreetmap-website/pull/4793/files#diff-eac95d76558af100602bc5274b9b685530cba96ce5abb5fddeb5f3b3cfa5c215 will remain big blobs of SVG code.

**Comment by tomhughes** [comment]
That looks good to me now, thanks.

**Comment by hiddewie** [comment]
Thanks for all the reviews!

**Pull request merged**
