### PR TITLE
Add support for Mapzen's Valhalla routing engine

### PR DESCRIPTION
**Pull request by tomhughes**

### CODE REVIEW

**Comment by kevinkreiser** [comment]
looks great! thanks so much for doing this! :shipit:

**Comment by dgearhart** [comment]
thank you :+1:

**Comment by gknisely** [comment]
:shipit: thanks!

**Comment by dgearhart** [comment]
I am not seeing Mapzen in the direction engine pull down anymore

**Comment by ppawel** [comment]
Car (Mapzen) returns a lot of 400 Bad Request responses (which is quite a silly response code because there is nothing wrong with a request for a route between two largest cities in Poland and OSRM finds it properly anyway) and the result on the website is that the loading spinner is shown indefinitely - shouldn't there be a "error ocurred" or "couldn't find route" message?

**Comment by kevinkreiser** [comment]
indeed if it cant find a route, the body of the 400 will say as much. can you give the locations in the route so we can look into it?

**Comment by ppawel** [comment]
http://www.openstreetmap.org/directions?engine=mapzen_car&route=50.062%2C19.937%3B52.232%2C21.007

The request is:

http://valhalla.mapzen.com/route?api_key=valhalla-7UikjOk&json=%7B%22locations%22%3A%5B%7B%22lat%22%3A50.0619474%2C%22lon%22%3A19.9368564%7D%2C%7B%22lat%22%3A52.2319237%2C%22lon%22%3A21.0067265%7D%5D%2C%22costing%22%3A%22auto%22%2C%22directions_options%22%3A%7B%22units%22%3A%22km%22%2C%22language%22%3A%22en-US%22%7D%7D

**Comment by ppawel** [comment]
BTW Car (MapQuest) returns 403 Forbidden!?

http://open.mapquestapi.com/directions/v2/route?callback=jQuery111304347043437883258_1443644739994&key=wMq1ly0MVgGsb3vl6ZcBJFRRFU6rPLgU&from=50.062%2C19.937&to=52.232%2C21.007&routeType=fastest&manMaps=false&shapeFormat=raw&generalize=0&unit=k&_=1443644739995

**Comment by tomhughes** [comment]
Guys, can we stop using this bug as a dumping ground for every routing issue please...

**Pull request merged**
