### PR TITLE
Fix scroll layer choice problem on mobile

### PR DESCRIPTION
**Pull request by renziver**
Addressed Issue #1568 
screen shot 2017-06-29 at 10 05 38 am

### CODE REVIEW

**Comment by tomhughes** [comment]
There seem to be a lot of changes here which have nothing to do with scrolling the layer switcher?

You're changing the scroll attributes for a number of things which don't seem to be related to the layer switcher and the height of two things, neither of which seems to be related to the layer switcher?

**Comment by renziver** [comment]
@tomhughes tried to fix it again. thank you.

**Comment by padi** [comment]
This addresses #1551 instead of the one referenced in the description.

Since the fix is just a one-liner, you can fix your commit history by using using git's interactive rebase tool: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by padi** [comment]
This addresses #1551 instead of the one referenced in the description.

Since the fix is just a one-liner, you can fix your commit history by using using git's interactive rebase tool: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

@renziver

**Comment by tomhughes** [comment]
So @jidanni seems to think this is no longer a problem? Certainly I couldn't reproduce it...

**Comment by gravitystorm** [comment]
I've reopened #1551 since I've been able to reproduce the reported problem.

This PR does fix the problem. However, it does so by making the `map-ui` panel always 50% of screen height, even if it is the only open panel (Currently if the `map-ui` panel is shown alone, it is full height). For reference, the `sidebar` is always 50% height on small screens.

So it fixes the problem described, but with the downside that the `map-ui` panels are always smaller (and so need to be scrolled more often, and options on the layer switcher will be usually hidden). 

Perhaps there is an alternative approach that allows the `map-ui` to remain 100% when shown alone, but 50% when the sidebar is active? I'm not strong enough with CSS to know if that's feasible.

**Comment by gravitystorm** [comment]
> This PR does fix the problem. However, it does so by making the `map-ui` panel always 50% of screen height, even if it is the only open panel (Currently if the `map-ui` panel is shown alone, it is full height). For reference, the `sidebar` is always 50% height on small screens.
> 
> So it fixes the problem described, but with the downside that the `map-ui` panels are always smaller (and so need to be scrolled more often, and options on the layer switcher will be usually hidden).

Given the above mentioned limitations, I'm going to close this PR. Alternative solutions to #1551 are of course welcome.

**Comment by jidanni** [comment]
> So @jidanni seems to think this is no longer a problem? Certainly I couldn't reproduce it...

@jidanni won't get notified, as you have blocked him.

**Comment by gravitystorm** [comment]
> @jidanni won't get notified, as you have blocked him.

Nobody has blocked your notifications. We don't have control over the notifications sent to you, that's entirely between your own Github notification settings, and your junk mail filters.

**Comment by tomhughes** [comment]
Actually he may be right. It's true that I personally have blocked him but I have no idea what effect that has on notifications of comments I make to him.

**Comment by jidanni** [comment]
https://catless.ncl.ac.uk/Risks/31.46#subj35
https://catless.ncl.ac.uk/Risks/31.47#subj13

**Comment by jidanni** [comment]
It's a shame that so many relationships here are exacerbated simply due to GitHub's mistaken implementation of blocking. Making user A think user B is ignoring them when all along they don't get the notification in the first place, etc.. That's why I think OSM should inform its GitHub users of the problem, as GitHub is not going to fix it.

**Comment by gravitystorm** [comment]
@jidanni @tomhughes OK, thanks both for explaining the situation to me, now I understand what's going on.

**Pull request closed without merging**
