### PR TITLE
Add a paragraph on the rules in OSM or the lack of them.

### PR DESCRIPTION
**Pull request by simonpoole**
This is food for thought for now: what can we say in this paragraph without scaring off people, but still getting the proper message across (and keeping things short and to the point)? 

This PR was prompted in part by "overhearing" a mapper complaining bitterly about not being pointed at the guidelines before the "accident" happened and it shouldn't be thought of as import hostile, if at all it gives people a fighting chance to do things right.

And yes it would need an icon before being merged.

### CODE REVIEW

**Comment by gravitystorm** [comment]
I understand the intention but I think the opening statement - "OpenStreetMap has very little in the way of rules that should be followed" - gives entirely the wrong impression. As written it appears to give permission to do whatever you want, but the impression that we are aiming for is about consideration towards other people. Perhaps something like:

> OpenStreetMap has few formal rules but we expect all participants to collaborate
> with, and communicate with, the community. If you are considering 
> any activities other than normal editing, please read and follow the guidelines on 

I've also decided that all my interrobang-related comments are just bikeshedding. :-)

**Comment by systemed** [comment]
@gravitystorm: good suggestion.

That also means it can go as a second para under 'Community Driven' (because it's talking about community), rather than as a discrete 'Rules' item.

Perhaps replace "any activities other than normal editing" with "any ...manual editing" or (better still) "any editing other than by hand", because for some people taking a shapefile and uploading it to a datastore is indeed "normal".

**Comment by simonpoole** [comment]
RichardF is on the wrong page, something which happens once in a blue moon :-)

For reference



this is the page that gets shown to new sign ups once they have completed the process. I'm not against adding similar/the same text to the "About" page but I suspect we have a slightly different audience there.

@gravitystorm I agree the text is far better. I'm not really happy with the title and need to snore over it if nobody has a better suggestion.

**Comment by simonpoole** [comment]
et voilà!
welcome_rules

**Comment by danstowell** [comment]
(fwiw: looks good to me)

**Comment by tomhughes** [comment]
Merged as cf8a20962b2045f11f7cea0873e0d9eccc1e1145.

**Pull request closed without merging**
