### PR TITLE
Added RDFa support for browse/node

### PR DESCRIPTION
**Pull request by tommorris**
RDFa allows HTML to contain rich semantics. The RDFa added here allows for RDFa-aware processors to extract the latitude and longitude of points.

The vocabulary used is the [W3C's Basic Geo WGS84 vocabulary](http://www.w3.org/2003/01/geo/). This vocabulary is in widespread use (for instance, on dbpedia.org, an RDF version of Wikipedia).

RDFa works perfectly well with the existing geo microformat.

### CODE REVIEW

**Comment by gravitystorm** [comment]
I've spent some time looking into this. Overall I don't have strong views as to whether this is worthwhile either way (and I suspect that might be this PR has been open for almost 5 years now - it's just not a priority).

The browse pages are available to help mappers with their work. They are not intended to be a way to publish OSM data, and they are certainly not intended for wholescale scraping. Having them available in search engines is useful for mappers in various editing workflows (I've used search engines to find particular OSM features before, for example) but any other usage is of distant secondary concern. So any effort put into this should be seen in the right context.

I've been trying to rapidly learn about this topic but I find it all a little impenetrable. As far as I can tell, since this PR was opened:

* RDFa 1.1 has happened
* HTML5 has happened
* It's not clear to me if anything has superseded the 2003 "Basic Geo Vocabulary"

I'm not ready to merge the PR, since I'm not comfortable that it still follows best practices for 2017, or if other approaches to annotating the coordinates are more widespread now than back in 2012. If anyone has any experience with this please let me know.

**Comment by sabas** [comment]
I followed this conversation at the time when I was studying the topic but I haven't kept updated on it... Semantic annotations are important at least from SEO perspective (without focusing on the linked web).  We have already the OpenGraph tags, it could be useful to add those from Google?
https://developers.google.com/search/docs/guides/intro-structured-data

**Comment by CloCkWeRX** [comment]
Schema.org defining more vocabularies is probably the biggest change for 2017 best practices; and includes some Geo concepts.
 
Since the site has gone opengraph tags already (at a site level); the simplest approach is changing the node/way pages from outputting:
```
<meta property="og:site_name" content="OpenStreetMap" />
<meta property="og:title" content="Node: ‪Lake McKenzie‬ (‪5181438822‬) | OpenStreetMap" />
<meta property="og:type" content="website" />
<meta property="og:image" content="http://www.openstreetmap.org/assets/osm_logo_256-835a859acf0d378e1d14e88b15e7b4b95211ccd41a2c061b1629cfbbb8deb697.png" />
<meta property="og:image:secure_url" content="http://www.openstreetmap.org/assets/osm_logo_256-835a859acf0d378e1d14e88b15e7b4b95211ccd41a2c061b1629cfbbb8deb697.png" />
<meta property="og:url" content="http://www.openstreetmap.org/node/5181438822" />
<meta property="og:description" content="OpenStreetMap is a map of the world, created by people like you and free to use under an open licence." />
```
... which basically says "http://www.openstreetmap.org/node/5181438822 is a website, named 'Node: ‪Lake McKenzie‬ (‪5181438822‬) | OpenStreetMap' and it looks like (logo url)

to something like:
```
<meta property="og:site_name" content="OpenStreetMap" />
<meta property="og:title" content="‪Lake McKenzie" />
<meta property="og:type"                  content="place" /> 
<meta property="og:url" content="http://www.openstreetmap.org/node/5181438822" />
<meta property="og:description" content="{node description tags if relevant}" />
<meta property="place:location:latitude"  content="-25.4460683" /> 
<meta property="place:location:longitude" content="153.0497883" />
```
which would be 
 "http://www.openstreetmap.org/node/5181438822 is a Place, named 'Lake McKenzie' and at '-25.4460683,153.0497883' listed on OpenStreetMap"

Happy to do an updated version of the PR based on that approach

**Comment by gravitystorm** [comment]
@CloCkWeRX Thanks! It sounds like a good approach. I'd suggest making two separate PRs - one for adding the location information, and a separate one for changing the existing opengraph tags.

**Comment by gravitystorm** [comment]
I'm going to close this pull request, since we have an alternative way forward described in the comments above.

**Pull request closed without merging**
