### PR TITLE
Add banner for FOSSGIS 2016 conference

### PR DESCRIPTION
**Pull request by PedaB**
This was talked about on IRC that the FOSSGIS 2016 conference should get a banner, too as FOSSGIS is kind of a local chapter and the conference is the big OSM event for the German-speaking part of the world.

### CODE REVIEW

**Comment by bhousel** [comment]
Looks ok!  Though if it were me I would adjust the image to leave more room for the close 'X'

screenshot 2016-06-23 16 56 15

**Comment by bhousel** [comment]
👍  latest:

screenshot 2016-06-23 17 05 56

**Comment by SomeoneElseOSM** [comment]
How hard would it be to make these adverts not repeat per logged-in user?  Having to hide each one (of 3 current adverts) multiple times (at least once per browser per PC) is annoying.

**Comment by tomhughes** [comment]
Well the problem is where would you store that..

More to the point is that I fear it reduces the whole point of them, if you only give people one chance to see them as there's every chance it will barely register the first time it appears.

**Comment by gravitystorm** [comment]
We have a user prefs system that could be used to store banner view status, similar to the cookies. 

Then someone could win extra points by showing non-viewed banners within editors like JOSM too :-)

**Comment by tomhughes** [comment]
Well yes we do, but that means an extra database query on every page load, and as I say I fear that it may just make the banners utterly irrelevant.

**Comment by gravitystorm** [comment]
> it's important to continue to store the "seen" state of the banners in the browser's cookies

I don't think anyone is suggesting otherwise - just to add an additional mechanism of storing whether the banners have been seen for logged-in users who have multiple devices.

> it can get annoying - but in this scenario you are probably already used to needing to do things several times across your browsers and computers

I'm not particularly convinced by that line of reasoning! When you are logged into a website and you make an action that the developer consider worth remembering, it's probably worth remembering across all your sessions. When I add a friend on facebook^WOSM, for example, I don't need to add the same friend on every device that I own.

**Pull request merged**
