### PR TITLE
Use 5 meter radius for input locations in Valhalla

### PR DESCRIPTION
**Pull request by nilsnolde**
This will search for road segments within 5 meter radius of the input location and choose the best path from/to whichever segment gives the cheapest cost. It should be preferable in most scenarios compared to simply snapping to the closest segment.

I'll do the same PR for our web app at https://github.com/gis-ops/valhalla-app.

### CODE REVIEW

**Comment by tomhughes** [comment]
That change doesn't seem to make any difference to the route from https://github.com/valhalla/valhalla/issues/4419 for me?

**Comment by nilsnolde** [comment]
Yeah, you're right.. Sorry, didn't think that'd need testing, good that you did.. Not even 50 m makes a difference here. Urgh, that actually might need a bit of debugging, can't see why that wouldn't work. Only :rabbit: :hole: lately ;)

**Comment by nilsnolde** [comment]
I mean the change is still valid generally, IMO it's still good to merge, even the trigger doesn't seem valid atm.

**Comment by kevinkreiser** [comment]
> can't see why that wouldn't work

costing thing where sidewalks are favored more than shared access carriageways. basically the safety of the sidewalk is worth walking the extra distance. this would suggest a costing imbalance though, which is possible. or something else im not thinking of.

**Pull request merged**
