### PR TITLE
Document the step of building translations when installing

### LINKED ISSUE #2663: Asset was not declared to be precompiled in production errors
When running the installation steps in [INSTALL.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md) I get errors on `bundle exec rake test:db`

```
rails test test/system/issues_test.rb:25

.......................................................................................................................................
......................................E

Error:
UserCreationTest#test_user_create_submit_duplicate_username:
ActionView::Template::Error: Asset `i18n/ba.js` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.

  //= link i18n/ba.js
and restart your server
    app/views/layouts/_head.html.erb:8
    app/views/layouts/_head.html.erb:1
    app/views/layouts/site.html.erb:3
    app/controllers/users_controller.rb:247:in `create'
    config/initializers/compressed_requests.rb:27:in `call'
    config/initializers/cors.rb:9:in `call'
    test/integration/user_creation_test.rb:66:in `block (4 levels) in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:65:in `block (3 levels) in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:64:in `block (2 levels) in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:63:in `block in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:60:in `each'
    test/integration/user_creation_test.rb:60:in `test_user_create_submit_duplicate_username'



``

### PR DESCRIPTION
**Pull request by pnorman**
Fixes #2663

### CODE REVIEW

**Comment by tomhughes** [comment]
I think the reason we didn't document this was that it's only needed in production mode and the assumption is that most people using this repository will be in development mode.

**Comment by tomhughes** [comment]
Then again, the assets don't need building in dev either...

**Comment by tomhughes** [comment]
Hmm you got that error running tests... Not sure why that would be.

**Comment by tomhughes** [comment]
Oh I understand, it's confused because it thinks that file would be missing in production, because it doesn't recognise there is a glob that would match it if it existed, which it would if the translations had been built.

But there's no actual to build them in test/dev other than to allow it to recognise that there isn't a potential problem.

I think I need to think about this some more...

**Comment by pnorman** [comment]
Closing as abandoned.

**Pull request closed without merging**
