### PR TITLE
Update to iD v2.18.2

### PR DESCRIPTION
**Pull request by quincylvania**
#### :mega: Release Highlights
* :raised_hand_with_fingers_splayed: **Touchscreen support!** We've finally optimized iD for multi-touch mapping on tablets and 2-in-1 devices.<br/>
_Long-press on features to open the edit menu. Review the Help pane to see what else you can do._
* :card_index_dividers: **Multiselection editing** has been supercharged, so you can update many features together instead of one at a time.<br/>
_<kbd>⇧ Shift</kbd> + click to select multiple features. On touchscreens, tap-and-hold one feature, then tap others to select them too._
* :ballot_box_with_check: **[Osmose](http://osmose.openstreetmap.fr)** data quality issues can now be browsed and resolved within iD. Thanks, [@SilentSpike], for this integration!<br/>
_Press <kbd>F</kbd> to open the Map Data pane and toggle on Osmose Issues under Data Layers._

[@SilentSpike]: https://github.com/SilentSpike

#### :tada: New Features
You can now:

* Open the edit menu on touchscreens by long-pressing on features ([#7577])
* Create multiselections on touchscreens by holding one feature while tapping additional features ([#7590])
* Add nodes to ways on touchscreens by double-tapping and dragging midpoints ([#2677])
* Drag nodes to reposition them on touchscreens ([#7415])
* Map with a stylus, including when navigating, selecting, drawing, and dragging ([#1981], [#7396])
* Navigate the map with multi-touch in Edge and Internet Explorer 11 ([#6598])
* Use <kbd>Space</kbd> as an alternative to left-click for selecting and deselecting features ([#3843])
* Open the edit menu by long-clicking or holding down <kbd>Space</kbd> while hovering over features
* Nudge selected features with the arrow keys when holding <kbd>⇧ Shift</kbd> ([#7186])
* Copy and paste features via the edit menu, including on touchscreens ([#2508])
* Edit the fields and tags of multiple selected features all at once ([#1761], [#7262], [#7306])
* View the issues shared by multiple selected features ([#7324])
* Browse and resolve Osmose quality assurance issues ([#5682], [#7095], thanks [@SilentSpike])
* Add basic WMS endpoints as custom background layers ([#4977], [#7510], thanks [@1ec5])
* Get the latest brand presets and OSM community resources whenever you launch iD ([#4994])

[@SilentSpike]: https://github.com/SilentSpike
[@1ec5]: https://github.com/1ec5

[#7577]: https://github.com/openstreetmap/iD/issues/7577
[#7590]: https://github.com/openstreetmap/iD/issues/7590
[#2677]: https://github.com/openstreetmap/iD/issues/2677
[#7415]: https://github.com/openstreetmap/iD/issues/7415
[#1981]: https://github.com/openstreetmap/iD/issues/1981
[#7396]: https://github.com/openstreetmap/iD/issues/7396
[#6598]: https://github.com/openstreetmap/iD/issues/6598
[#3843]: https://github.com/openstreetmap/iD/issues/3843
[#7186]: https://github.com/openstreetmap/iD/issues/7186
[#7186]: https://github.com/openstreetmap/iD/issues/7186
[#2508]: https://github.com/openstreetmap/iD/issues/2508
[#1761]: https://github.com/openstreetmap/iD/issues/1761
[#7262]: https://github.com/openstreetmap/iD/issues/7262
[#7306]: https://github.com/openstreetmap/iD/issues/7306
[#7324]: https://github.com/openstreetmap/iD/issues/7324
[#5682]: https://github.com/openstreetmap/iD/issues/5682
[#7095]: https://github.com/openstreetmap/iD/issues/7095
[#4977]: https://github.com/openstreetmap/iD/issues/4977
[#7510]: https://github.com/openstreetmap/iD/issues/7510
[#4994]: https://github.com/openstreetmap/iD/issues/4994

#### :boom: Breaking Changes
* Pressing <kbd>Space</kbd> with features selected no longer opens the edit menu, since the spacebar can now be used to select and deselect things. You can use the [menu key](https://en.wikipedia.org/wiki/Menu_key) instead, or hold down <kbd>Space</kbd> with the cursor hovering over a feature
* :warning: There are numerous under-the-hood code changes. See the **Development** section below for details

###### Interactions
* Don't show tooltips for non-mouse interactions ([#6035])
* Flash feedback when tapping some buttons on touchscreens ([#7699])
* Use larger map targets for touch and stylus input to make interactions easier ([#7643])
* Prevent browser page navigation when swiping with a multi-touch trackpad or mouse in the map ([#5552], [#7659])
* Don't zoom the entire interface via double-tap or pinch-to-zoom on touchscreens ([#6049])
* Disable elastic page bouncing on standalone iD ([#7576])
* Make it easier to select features via clicking with a multi-touch mouse

[#6035]: https://github.com/openstreetmap/iD/issues/6035
[#7699]: https://github.com/openstreetmap/iD/issues/7699
[#7643]: https://github.com/openstreetmap/iD/issues/7643
[#5552]: https://github.com/openstreetmap/iD/issues/5552
[#7659]: https://github.com/openstreetmap/iD/issues/7659
[#6049]: https://github.com/openstreetmap/iD/issues/6049
[#7576]: https://github.com/openstreetmap/iD/issues/7576

###### Operations
* Support disconnecting multiple selected features from each other and from all connected features ([#7652])
* Support circularizing multiple selected areas and closed lines at once ([#7326])
* Make the Extract operation work immediately without an extra step to place the point ([#6674])
* Support the Extract operation on lines that could be mapped as points ([#7598])
* Support extracting points from multiple selected features at once ([#7600])
* Disable the Straighten operation for ways that are already straight ([#7658])

[#7652]: https://github.com/openstreetmap/iD/issues/7652
[#7326]: https://github.com/openstreetmap/iD/issues/7326
[#6674]: https://github.com/openstreetmap/iD/issues/6674
[#7598]: https://github.com/openstreetmap/iD/issues/7598
[#7600]: https://github.com/openstreetmap/iD/issues/7600
[#7658]: https://github.com/openstreetmap/iD/issues/7658

###### Sidebar
* Accept more formats when searching for nodes, ways, and relations by ID ([#7627], [#7282], [#7775], thanks [@blackboxlogic])
* Highlight the corresponding feature in the selection list when hovering on a feature in the map ([#2949], [#7628], thanks [@jgscherber])
* Don't discard tags with empty values when toggling from the text to table tag editor ([#7297], [#7363], thanks [@zengchu2])
* Improve sorting of lassoed points in the selected features list ([#7729])
* Make the selected features list a labeled, collapsible section of the inspector ([#7273])
* Add a label to the "change feature type" button ([#6811])
* Wrap long feature type labels to multiple lines ([#7722])
* Move the "Zoom to this" button to be with the other zoom buttons on the side of the map ([#6601], [#7391])
* Change misleading "Translate" tooltip to "Add multilingual name" ([#7486])
* Add "key=value" placeholder to the text tag editor
* Focus the relation role input when clicking its label ([#7690])
* Autofocus Description field when adding a new OSM note ([#7680])
* Prevent browsers from showing their own list of autocomplete values for fields ([#6444])

[@blackboxlogic]: https://github.com/blackboxlogic
[@jgscherber]: https://github.com/jgscherber
[@zengchu2]: https://github.com/zengchu2

[#7627]: https://github.com/openstreetmap/iD/issues/7627
[#7282]: https://github.com/openstreetmap/iD/issues/7282
[#7775]: https://github.com/openstreetmap/iD/issues/7775
[#2949]: https://github.com/openstreetmap/iD/issues/2949
[#7628]: https://github.com/openstreetmap/iD/issues/7628
[#7297]: https://github.com/openstreetmap/iD/issues/7297
[#7363]: https://github.com/openstreetmap/iD/issues/7363
[#7729]: https://github.com/openstreetmap/iD/issues/7729
[#7273]: https://github.com/openstreetmap/iD/issues/7273
[#6811]: https://github.com/openstreetmap/iD/issues/6811
[#7722]: https://github.com/openstreetmap/iD/issues/7722
[#6601]: https://github.com/openstreetmap/iD/issues/6601
[#7391]: https://github.com/openstreetmap/iD/issues/7391
[#7486]: https://github.com/openstreetmap/iD/issues/7486
[#7690]: https://github.com/openstreetmap/iD/issues/7690
[#7680]: https://github.com/openstreetmap/iD/issues/7680
[#6444]: https://github.com/openstreetmap/iD/issues/6444

###### Map
* Update the Locator Overlay ([#7025], thanks [@mikelmaron])
* Enable the Mapillary detected Map Features layer everywhere ([#7762], thanks [@nickplesha])
* Make way midpoint positions account for the taller toolbar ([#7640], [#7642], thanks [@jgscherber])
* Move corridors from the paths layer to the indoor features layer ([#7478], [#7548], thanks [@JamesKingdom])
* Render the focused feature at any zoom level during conflict resolution ([#7330])
* Support the `{@2x}` and `{r}` parameters for dynamic retina tiles in custom backgrounds ([#7712])

[@mikelmaron]: https://github.com/mikelmaron
[@nickplesha]: https://github.com/nickplesha
[@jgscherber]: https://github.com/jgscherber
[@JamesKingdom]: https://github.com/JamesKingdom

[#7025]: https://github.com/openstreetmap/iD/issues/7025
[#7762]: https://github.com/openstreetmap/iD/issues/7762
[#7640]: https://github.com/openstreetmap/iD/issues/7640
[#7642]: https://github.com/openstreetmap/iD/issues/7642
[#7478]: https://github.com/openstreetmap/iD/issues/7478
[#7548]: https://github.com/openstreetmap/iD/issues/7548
[#7330]: https://github.com/openstreetmap/iD/issues/7330
[#7712]: https://github.com/openstreetmap/iD/issues/7712

###### Tools
* Include contextual information in the page title ([#6209], [#7444], thanks [@CarycaKatarzyna])
* Point OSMCha links to the new site ([#7555], thanks [@willemarcel])
* Add toggle buttons for the History, Measurement, and Location panels ([#6397])
* Add <kbd>L</kbd> shortcut to toggle the display of the device's current location ([#7395])
* Style the "Show My Location" button as enabled while the location is being shown ([#7390])
* Flash error feedback when locating the device if the location is unavailable
* Show descriptive tooltips when Zoom In / Out buttons are disabled
* Show more calculations in the Measurement panel when multiple features are selected ([#7329])
* Flash error feedback when attempting to draw self-intersecting lines or areas
* Redact API tokens detected in custom background imagery sources ([#6801])

[@CarycaKatarzyna]: https://github.com/CarycaKatarzyna
[@willemarcel]: https://github.com/willemarcel

[#6209]: https://github.com/openstreetmap/iD/issues/6209
[#7444]: https://github.com/openstreetmap/iD/issues/7444
[#7555]: https://github.com/openstreetmap/iD/issues/7555
[#6397]: https://github.com/openstreetmap/iD/issues/6397
[#7395]: https://github.com/openstreetmap/iD/issues/7395
[#7390]: https://github.com/openstreetmap/iD/issues/7390
[#7329]: https://github.com/openstreetmap/iD/issues/7329
[#6801]: https://github.com/openstreetmap/iD/issues/6801

#### :white_check_mark: Validation
* Improve connection of "Almost Junctions" when the lines are nearly co-linear ([#7201], [#7309], thanks [@SilentSpike])
* Deprecate various `type` tag values related to utilities ([#7514], thanks [@guylamar2006])
* Deprecate `building=pavillion` misspelling ([#7749], thanks [@peternewman])
* Disable copy and paste of features that aren't mostly visible ([#7603])
* Disable straightening features that aren't mostly visible ([#7675])
* Disable merging lines when it would result in a line exceeding the maximum nodes-per-way of the API ([#6030])
* Enforce the maximum Unicode character length for tag keys and values, as well as relation roles ([#6817])
* Prevent self-intersection when drawing lines and areas on touch devices ([#7423])
* Fix tolerance when flagging very close nodes that are members of multiple ways ([#7379])
* Don't flag empty tag values as outdated
* Don't flag Google Drive as an incompatible data source ([#7545])
* Deprecate various `parking` tag values ([#7578])
* Deprecate various `tower:type` values for newly-approved `line_management` tag ([#7726])

[@SilentSpike]: https://github.com/SilentSpike
[@guylamar2006]: https://github.com/guylamar2006
[@peternewman]: https://github.com/peternewman

[#7201]: https://github.com/openstreetmap/iD/issues/7201
[#7309]: https://github.com/openstreetmap/iD/issues/7309
[#7514]: https://github.com/openstreetmap/iD/issues/7514
[#7749]: https://github.com/openstreetmap/iD/issues/7749
[#7603]: https://github.com/openstreetmap/iD/issues/7603
[#7675]: https://github.com/openstreetmap/iD/issues/7675
[#6030]: https://github.com/openstreetmap/iD/issues/6030
[#6817]: https://github.com/openstreetmap/iD/issues/6817
[#7423]: https://github.com/openstreetmap/iD/issues/7423
[#7379]: https://github.com/openstreetmap/iD/issues/7379
[#7545]: https://github.com/openstreetmap/iD/issues/7545
[#7578]: https://github.com/openstreetmap/iD/issues/7578
[#7726]: https://github.com/openstreetmap/iD/issues/7726

#### :bug: Bugfixes
* Fix issue where panning without zooming could become impossible on touchscreens ([#6745])
* Don't persist the hover styling after tapping buttons on touchscreens ([#7432])
* Fix issue where vertices may not disappear when deselecting lines and areas ([#7419])
* Fix issue where drawing features too quickly on touchscreens could zoom the map ([#2128])
* Fix issue where map data may not be selectable with a single tap on touchscreens ([#7380])
* Don't grey out the map during conflict resolution ([#6547])
* Fix issue with the feature type label not updating properly when combining features ([#7349])
* Fix issue where merging a point matching a fallback preset into an area could discard tag values ([#7446])
* Fix issue where the edit menu could persist even after deselecting the feature ([#7143])
* Fix cases where the Mapillary Image ID link button might appear disabled unexpectedly ([#7570])
* Fix cases where merging the endpoint of a looped way with an adjacent point could break the loop ([#7553])
* Don't add a value when focusing the Memorial Type field when it's empty ([#7569])
* Don't add default field values when upgrading to a replacement preset ([#7613])
* Don't autocapitalize custom multilingual name languages ([#7156])
* Properly show the delete button for filled multilingual names even if no `name` tag is present ([#7572])
* Fix issue where iD may overflow its container and cause scrollbars to appear while drawing ([#7560])
* Fix infinite recursion error when creating cyclical relations ([#7691])
* Prevent lasso from selecting hidden points ([#7728])

[#6745]: https://github.com/openstreetmap/iD/issues/6745
[#7432]: https://github.com/openstreetmap/iD/issues/7432
[#7419]: https://github.com/openstreetmap/iD/issues/7419
[#2128]: https://github.com/openstreetmap/iD/issues/2128
[#7380]: https://github.com/openstreetmap/iD/issues/7380
[#6547]: https://github.com/openstreetmap/iD/issues/6547
[#7349]: https://github.com/openstreetmap/iD/issues/7349
[#7446]: https://github.com/openstreetmap/iD/issues/7446
[#7143]: https://github.com/openstreetmap/iD/issues/7143
[#7570]: https://github.com/openstreetmap/iD/issues/7570
[#7553]: https://github.com/openstreetmap/iD/issues/7553
[#7569]: https://github.com/openstreetmap/iD/issues/7569
[#7613]: https://github.com/openstreetmap/iD/issues/7613
[#7156]: https://github.com/openstreetmap/iD/issues/7156
[#7572]: https://github.com/openstreetmap/iD/issues/7572
[#7560]: https://github.com/openstreetmap/iD/issues/7560
[#7691]: https://github.com/openstreetmap/iD/issues/7691
[#7728]: https://github.com/openstreetmap/iD/issues/7728

#### :hourglass: Performance
* Request JSON responses from the OpenStreetMap API for supported endpoints ([#7188], thanks [@mmd-osm])
* Improve performance considerably when editing some types of long lines ([#7656])

[@mmd-osm]: https://github.com/mmd-osm

[#7188]: https://github.com/openstreetmap/iD/issues/7188
[#7656]: https://github.com/openstreetmap/iD/issues/7656

#### :mortar_board: Walkthrough / Help
* Show touch-specific instructions in the walkthrough when the mapper is using a touchscreen ([#7692], [#7745])
* Include information about touch interactions in the help docs
* Use mouse/touch icons in the walkthrough and style shortcuts as keyboard keys
* Reference interface labels directly in the help docs to ensure they always correspond to what's onscreen

[#7692]: https://github.com/openstreetmap/iD/issues/7692
[#7745]: https://github.com/openstreetmap/iD/issues/7745

###### New Presets
* Add Model Shop preset ([#7776], [#7779], thanks [@nisargshh])
* Add Office Building, Pigsty, and Cowshed presets ([#7539])
* Add Covered Reservoir preset ([#7534])
* Add Shoe Repair Shop preset ([#7562])
* Add Orthodontist preset ([#7575])
* Add Bubble Tea Cafe preset ([#7632])
* Add Collectibles Shop preset ([#7588])
* Add Free Box preset ([#7574])
* Add Goods Conveyor preset ([#7637])
* Add Trophy Shop preset ([#7641])
* Add Vacuum Cleaning Station preset ([#7483])
* Add Emergency Room Entrance preset ([#7725])
* Add Destination Sign relation preset ([#6970])
* Add Coffeehouse and Courtyard presets

[@nisargshh]: https://github.com/nisargshh

[#7776]: https://github.com/openstreetmap/iD/issues/7776
[#7779]: https://github.com/openstreetmap/iD/issues/7779
[#7539]: https://github.com/openstreetmap/iD/issues/7539
[#7534]: https://github.com/openstreetmap/iD/issues/7534
[#7562]: https://github.com/openstreetmap/iD/issues/7562
[#7575]: https://github.com/openstreetmap/iD/issues/7575
[#7632]: https://github.com/openstreetmap/iD/issues/7632
[#7588]: https://github.com/openstreetmap/iD/issues/7588
[#7574]: https://github.com/openstreetmap/iD/issues/7574
[#7637]: https://github.com/openstreetmap/iD/issues/7637
[#7641]: https://github.com/openstreetmap/iD/issues/7641
[#7483]: https://github.com/openstreetmap/iD/issues/7483
[#7725]: https://github.com/openstreetmap/iD/issues/7725
[#6970]: https://github.com/openstreetmap/iD/issues/6970

###### Changed Presets
* Rename Metal Construction preset to Metalworker ([#7549], [#7568], thanks [@animesh-007])
* Don't add `seamark:type=light_major` to lighthouses by default ([#7621], thanks [@Eric-Sparks])
* Don't support using the Foot & Cycle Path preset in Germany ([#7703], thanks [@henry4442])
* Limit the Bail Bond Agent preset to the United States and the Philippines
* Rename Summit Cross preset to Cross ([#7678])
* Rename Road Closed preset to Closed Road
* Rename Organic Goods Store preset to Organic Supermarket and add Organic Products field ([#7714])
* Add "Play" to the names of several playground equipment presets ([#7730])
* Support Quarry features as points ([#7515])
* Support Marine Fuel Station features as vertices
* Add search terms to Lift Gate, Height Restrictor, and Storage Rental ([#7537], [#7538], [#7681])

[@animesh-007]: https://github.com/animesh-007
[@Eric-Sparks]: https://github.com/Eric-Sparks
[@henry4442]: https://github.com/henry4442

[#7549]: https://github.com/openstreetmap/iD/issues/7549
[#7568]: https://github.com/openstreetmap/iD/issues/7568
[#7621]: https://github.com/openstreetmap/iD/issues/7621
[#7703]: https://github.com/openstreetmap/iD/issues/7703
[#7678]: https://github.com/openstreetmap/iD/issues/7678
[#7714]: https://github.com/openstreetmap/iD/issues/7714
[#7730]: https://github.com/openstreetmap/iD/issues/7730
[#7515]: https://github.com/openstreetmap/iD/issues/7515
[#7537]: https://github.com/openstreetmap/iD/issues/7537
[#7538]: https://github.com/openstreetmap/iD/issues/7538
[#7681]: https://github.com/openstreetmap/iD/issues/7681

###### New Fields
* Add Support, Color, and Material fields to Post Box ([#7738], [#7777], thanks [@yyazdi13])
* Add Type field to Ruins ([#7507], thanks [@hikemaniac])
* Add Automated field to Car Wash ([#7580], [#7584], thanks [@animesh-007])
* Add Fee field to Nightclub ([#7579], [#7585], thanks [@animesh-007])
* Add Real Fire field to pub presets in Ireland and the United Kingdom ([#7630], thanks [@rory])
* Add Image field ([#7531])
* Add VHF Channel field to Marina ([#7622])
* Add Grades field to school presets ([#7571])
* Add Type field to Closed Road ([#7519])
* Add Line Management field to High-Voltage Tower and Power Pole ([#7726])
* Add Destination field to Waterway relation preset ([#7532])
* Add Total Ascent, Total Descent, and Forms Loop fields to route presets ([#7671])
* Add Phone and Website fields to commercial building presets ([#7541])
* Add Mount and Type fields to Street Lamp

[@yyazdi13]: https://github.com/yyazdi13
[@hikemaniac]: https://github.com/hikemaniac
[@animesh-007]: https://github.com/animesh-007
[@rory]: https://github.com/rory

[#7738]: https://github.com/openstreetmap/iD/issues/7738
[#7777]: https://github.com/openstreetmap/iD/issues/7777
[#7507]: https://github.com/openstreetmap/iD/issues/7507
[#7580]: https://github.com/openstreetmap/iD/issues/7580
[#7584]: https://github.com/openstreetmap/iD/issues/7584
[#7579]: https://github.com/openstreetmap/iD/issues/7579
[#7585]: https://github.com/openstreetmap/iD/issues/7585
[#7630]: https://github.com/openstreetmap/iD/issues/7630
[#7531]: https://github.com/openstreetmap/iD/issues/7531
[#7622]: https://github.com/openstreetmap/iD/issues/7622
[#7571]: https://github.com/openstreetmap/iD/issues/7571
[#7519]: https://github.com/openstreetmap/iD/issues/7519
[#7726]: https://github.com/openstreetmap/iD/issues/7726
[#7532]: https://github.com/openstreetmap/iD/issues/7532
[#7671]: https://github.com/openstreetmap/iD/issues/7671
[#7541]: https://github.com/openstreetmap/iD/issues/7541

###### Changed Fields
* Allow custom values in the Public Bath Specialty field ([#7481])
* Remove Both/All option from Yield Sign Direction field ([#7581])

[#7481]: https://github.com/openstreetmap/iD/issues/7481
[#7581]: https://github.com/openstreetmap/iD/issues/7581

#### :hammer: Development
* :warning: Add dedicated initialization step to `coreContext` ([#7304])
* :warning: Remove various convenience functions of `coreContext`
* :warning: Fetch JSON resources asynchronously at runtime using `coreFileFetcher` instead of bundling them ([#4994])
* :warning: Add `coreUploader` to manage programatic uploading of edits ([#7247], [#7333])
* :warning: Wrap localization functionality into global `localizer` singleton of `coreLocalizer`
* :warning: Replace `context.storage()` with global `prefs` singleton of `corePreferences`
* Add optimized `coreTree.waySegments` endpoint to return edges overlapping an area
* Resolve browser cookie warning by using `samesite=strict` ([#7596])
* :warning: Remove deprecated radial menu and "tail" behavior
* Add endpoints for setting the changeset parameters programmatically ([#7614])
* Add endpoints for customizing the page title behavior ([#7503])
* :warning: Switch to pointer events on supported browsers, with fallback to mouse events ([#5505])
* :warning: Namespace iD's `id` HTML attributes under `ideditor-` to avoid collisions
* Fix cases where iD might miscalculate element positions when embedded ([#7551])
* Replace Greenkeeper with Dependabot for keeping dependencies up-to-date ([#7430])

[#7304]: https://github.com/openstreetmap/iD/issues/7304
[#4994]: https://github.com/openstreetmap/iD/issues/4994
[#7247]: https://github.com/openstreetmap/iD/issues/7247
[#7333]: https://github.com/openstreetmap/iD/issues/7333
[#7596]: https://github.com/openstreetmap/iD/issues/7596
[#7614]: https://github.com/openstreetmap/iD/issues/7614
[#7503]: https://github.com/openstreetmap/iD/issues/7503
[#5505]: https://github.com/openstreetmap/iD/issues/5505
[#7551]: https://github.com/openstreetmap/iD/issues/7551
[#7430]: https://github.com/openstreetmap/iD/issues/7430

### CODE REVIEW

**Comment by tomhughes** [comment]
Bombs with `Uncaught TypeError: iD.Detect is not a function` when loading iD...

**Comment by quincylvania** [comment]
@tomhughes Thanks for catching that. I've updated the initialization steps for the new endpoints.

**Comment by tomhughes** [comment]
Still doesn't start I'm afraid. We get a load of 404s for `/iD/data/discarded.min.json` and similar and a blank space where iD should be...

**Comment by quincylvania** [comment]
@tomhughes Oh, we unbundled most of the data files in this release and have to copy them over separately.

Also, I was wondering if there's any reason not to use iD's minified JavaScript file?

**Comment by tomhughes** [comment]
OK so now it starts but there is something odd going on... I'm using my dev instance but it is fetching map data from the production site?

**Comment by tomhughes** [comment]
To answer the second question it's certainly possible but normal rails design is to have the original source so that in dev mode it will serve that and you can debug and then in production mode it will be passed through your chosen pipeline of compressors etc.

**Comment by quincylvania** [comment]
> I'm using my dev instance but it is fetching map data from the production site?

Hmm can you point to the file on the rails site where it should be requesting the dev database?

> To answer the second question it's certainly possible but normal rails design is to have the original source so that in dev mode it will serve that and you can debug and then in production mode it will be passed through your chosen pipeline of compressors etc.

Sounds good. I did switch the site to use the ES5-compatible version of iD.js since we started using ES6 features in this release. But it's fine for you all to continue handling the minification.

**Comment by tomhughes** [comment]
I was looking earlier and it's not clear to me that we provide an API endpoint explicitly but I do know that somehow in previous versions it was hitting the API for the site it was loaded from.

We can easily provide the URL if there's a parameter for it?

**Comment by tomhughes** [comment]
Maybe it was from the `urlroot` parameter that is passed to the `preauth` call?

**Comment by quincylvania** [comment]
> Maybe it was from the urlroot parameter that is passed to the preauth call?

Okay yes, this appears to be it. There was an issue with `preauth` not working, so iD was defaulting to the production database.

**Pull request merged**
