### PR TITLE
Add framework for system tests

### PR DESCRIPTION
**Pull request by tomhughes**
This is a first attempt at setting things up so we can run system tests, as previously discussed in #1570.

### CODE REVIEW

**Comment by gravitystorm** [comment]
I'm definitely pro system tests in general, but I found two issues with this PR to discuss:

* The screenshots appear as base64 output in my terminal (Ubuntu 16.04). From [a related pull request](https://github.com/rails/rails/pull/28185), it seems some rails devs are aware that the inline images aren't supported by certain terminals. Should we disable them here, or report upstream?
* The system tests aren't run by default. The [rails docs confirms this](http://guides.rubyonrails.org/testing.html#system-testing), but doesn't offer any way to change the behaviour. I think it's important that they are run alongside the model, controller and integration tests. What do you think?

Beyond these, all looks good to me.

**Comment by tomhughes** [comment]
I didn't see any screenshots, or rather I recall them being images that I had to view. I've never heard of a terminal that supports images anyway?

I agree about running them, but there doesn't seem to be a good solution as far as I could see - it seems to be entirely deliberate (presumably because system tests are relatively slow) that they aren't run by default. I'll investigate some more though...

**Comment by tomhughes** [comment]
The basic problem is https://github.com/rails/rails/blob/master/railties/lib/rails/test_unit/runner.rb#L44 which, after taking patterns from the command line (defaulting to all) and finding matching tests then explicitly removes the system tests.

So it's very hard to override - you would probably have to monkey patch the `load_tests` method to remove that exclude.

**Comment by tomhughes** [comment]
Ah actually it only excludes if there were no user patterns, so there might be some way...

**Comment by tomhughes** [comment]
Turns out you can append to a rake task, so it was pretty easy to make it run them as a separate step in the task...

**Comment by gravitystorm** [comment]
LGTM. I'll report the base64 screenshot upstream and see what they say, but we can merge this in the meantime.

**Comment by gravitystorm** [comment]
Added as 9e929de53091ab5db24be602546e525a72548dbd and  d581fbfaf12c21145985cbc98f41cd8ac4e0a88e and upstream bug report at https://github.com/rails/rails/issues/31159

**Pull request closed without merging**
