### PR TITLE
Add Twitter and GitHub authentication

### PR DESCRIPTION
**Pull request by tomhughes**
This adds support for Twitter and GitHub login - will need the normal legal review of terms.

### CODE REVIEW

**Comment by simonpoole** [comment]
@tomhughes do you happen to have links to the resp. policies handy? If not, I'll try and locate them tomorrow.

**Comment by tomhughes** [comment]
I've copy and pasted the terms twitter present when you signup to https://gist.github.com/tomhughes/ed7df58b5193974236f1.

GitHub don't seem to present any special terms when you create an app - the standard ones are at https://help.github.com/articles/github-terms-of-service/.

**Comment by simonpoole** [comment]
https://dev.twitter.com/overview/terms/policy#9.Update_Twitter_Login has the service specific terms for twitter

**Comment by pnorman** [comment]
> Once a user has authenticated via Connect with Twitter via your Service, you must clearly display the user’s Twitter identity via your Service. Twitter identity includes visible display of the user’s avatar, Twitter user name and the Twitter bird mark. (3.a)

I don't think we display how a user has authenticated or the details of that. Displaying the avatar from twitter rather than gravitar would be interesting, but a user might choose to have no avatar.

Sadly, it looks like Twitter isn't an option.

**Comment by pnorman** [comment]
@github are there any app-specific terms for using github for login authentication?

**Comment by M1dgard** [comment]
Fixes #977

**Comment by pnorman** [comment]
From GitHub support

> Hi Paul,

> Thanks for reaching out! Our API terms are included in our general terms of service and can be found here:

> https://help.github.com/articles/github-terms-of-service/#b-api-terms

> Does this help answer your question?

> Please let us know if we can help in any other way!

The section states

> Customers may access their GitHub account data via an API (Application Program Interface). Any use of the API, **including use of the API through a third-party product that accesses GitHub**, is bound by these Terms of Service plus the following specific terms:

> 1. You expressly understand and agree that GitHub shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if GitHub has been advised of the possibility of such damages), resulting from your use of the API or third-party products that access data via the API.

> 2. Abuse or excessively frequent requests to GitHub via the API may result in the temporary or permanent suspension of your account's access to the API. GitHub, in its sole discretion, will determine abuse or excessive usage of the API. GitHub will make a reasonable attempt via email to warn the account owner prior to suspension.

> 3. GitHub reserves the right at any time to modify or discontinue, temporarily or permanently, your access to the API (or any part thereof) with or without notice.

They've last updated their terms this year, and I believe the current terms clearly address API usage while the ones when this PR was started didn't.

Nothing jumps out with the terms as a problem. There's the standard may not use the service for illegal or unauthorized purpose clause, but we didn't have a problem with FB's clause, and GitHub's appears more reasonable. The restrictions on one login per person and not sharing login information might cause some operational issues getting a key.

Otherwise, I think the GH terms are ready to go to the LWG for review, while we throw out Twitter authentication, as we [don't meet their display requirements](https://github.com/openstreetmap/openstreetmap-website/pull/989#issuecomment-110209086).

**Comment by tomhughes** [comment]
I've now added wikipedia auth to this to address #1146.

Thanks to @timwaters for getting a new release of the omniauth-mediawiki gem out to help with that!

**Comment by simonpoole** [comment]
The LWG is OK with enabling Github accounts see https://docs.google.com/document/d/12jJw7qNGhQCIE4z0h33CH9yrtTIWnpNksAd86Pxiu1o/edit wikimedia needs some clarificatiosn with the WMF which we are in the process of doing.

**Comment by nemobis** [comment]
> wikimedia needs some clarificatiosn with the WMF which we are in the process of doing.

Note that Luis doesn't work for WMF any longer, you should ask legal@wikimedia.org. What is the question, by the way?

**Comment by Zverik** [comment]
I remember there was a long discussion about whether facebook verifies e-mail. I know twitter does, but what about github?

**Comment by pnorman** [comment]
Is picking out the github changes an option? We know Twitter won't work and there's no ETA on when we'll have the information to review Wikimedia's terms, let alone when the review will be done.

**Comment by tomhughes** [comment]
Well it is, though removing the twitter changes will mean changes to some tests in the patches that follow.

I was kind of assuming wikimedia would be reasonably quick, being a friendly organisation rather than a corporate that is impossible to contact!

We need to work out how/where to register the official credentials for the twitter one - against the @openstreetmap account I guess?

**Comment by simonpoole** [comment]
The WMFs lawyers said they would get back to us asap, that's all I can say.

**Comment by tomhughes** [comment]
Sorry, I meant official credentials for github of course!

**Comment by pnorman** [comment]
> Well it is, though removing the twitter changes will mean changes to some tests in the patches that follow.

But that needs doing anyways, right?

**Comment by tomhughes** [comment]
GitHub login has now been merged and enabled on the live site.

**Comment by simonpoole** [comment]
WMF: I prodded a bit last week, but haven't got a response yet.

**Comment by nemobis** [comment]
Simon Poole, 18/08/2016 18:58:
> WMF: I prodded a bit last week, but haven't got a response yet.

What address did you write to? The main correct address is 
legal@wikimedia.org.

**Comment by simonpoole** [comment]
@nemobis what isn't clear about

> The WMFs lawyers said they would get back to us asap, that's all I can say.

I am quite capable of determining if I'm talking to the right people or not, thanks.

**Comment by gravitystorm** [comment]
> and I am quite capable of determining if I'm talking to the right people or not, thanks.

No need to be rude. @nemobis was just trying to be helpful.

**Comment by simonpoole** [comment]
Actually reading back a bit would be helpful too.

**Comment by pnorman** [comment]
Is this PR still relevant?

**Comment by tomhughes** [comment]
Well GitHub has been merged and Twitter seemingly can't be so I guess not.

**Pull request closed without merging**
