### PR TITLE
Remove the arm pointing to the new user registration form

### PR DESCRIPTION
**Pull request by AntonKhorev**
There's a arm pointing to the new user form.
image

Unfortunately it has a shadow fading into white. This is going to stand out in dark mode.
image

The Microsoft redesign https://github.com/openstreetmap/openstreetmap-website/pull/4455 doesn't have the arm.
image

Instead of trying to fix the shadow, we might remove the arm even before switching to https://github.com/openstreetmap/openstreetmap-website/pull/4455.

image

### CODE REVIEW

**Comment by tomhughes** [comment]
There's overlap with #4455 here, though I think that actually already removes the down pointing arm?

**Comment by tordans** [comment]
> There's overlap with #4455 here, though I think that actually already removes the down pointing arm?

That is my understanding as well and I thing it would be better to focus on reviewing and merging #4455 and not add possible merge conflicts my cherry-picking changes.

**Comment by AntonKhorev** [comment]
> There's overlap with https://github.com/openstreetmap/openstreetmap-website/pull/4455 here

Of course there is, that's why I'm making this pull request. The third image in the PR description is from https://github.com/openstreetmap/openstreetmap-website/pull/4455 in dark mode.

> it would be better to focus on reviewing and merging https://github.com/openstreetmap/openstreetmap-website/pull/4455 and not add possible merge conflicts

Or you can look at this PR as a [thing that can be treated separately](https://github.com/openstreetmap/openstreetmap-website/pull/4455#issuecomment-1994918240), a smaller part of https://github.com/openstreetmap/openstreetmap-website/pull/4455.

**Comment by AntonKhorev** [comment]
This is still needed to remove the arm png.

**Comment by AntonKhorev** [comment]
There's one svg file with both the entire globe and the arm layer. Editing that svg is tricky because it requires to have a specific font for 1's and 0's to look the same.

`common.scss` shouldn't have references to the arm image now.

**Comment by tomhughes** [comment]
Ah yes my grep was a bit too generic.... Looks good then, thanks.

**Pull request merged**
