### PR TITLE
GraphHopper: Include roundabout

### PR DESCRIPTION
**Pull request by karussell**
We'll have special markers for roundabouts in the instructions in the next days.

Including a minor change to explicitly avoid elevation

> // TODO does graphhopper map instructions onto line indices?

BTW: what does the TODO mean? Maybe @systemed knows?

### CODE REVIEW

**Comment by systemed** [comment]
It means that, in the OSRM and MapQuest JS interfaces, you can click on a turn-by-turn instruction and it'll highlight the relevant section of polyline and bring up a bubble. At present the Graphhopper interface doesn't do that.

**Comment by karussell** [comment]
Ah, thanks. Yes, that would be possible via the instructions[i].interval ... maybe I'll have time to implement this in a separate PR

**Comment by tomhughes** [comment]
So are you saying that elevation is currently excluded implicitly?

**Comment by karussell** [comment]
Just excluded explicitly to make sure that the encoded polylines never get elevation information included as one would need a custom decoder that reads [lat,lng,ele] instead of [lat,lng]. Although it would be nice to show it like we do on GraphHopper Maps

**Comment by tomhughes** [comment]
Merged as 7bf86b7c4eb7c11beb114eb9a7b398ff4d48d495.

**Comment by karussell** [comment]
Thanks!

**Pull request closed without merging**
