### PR TITLE
Add gitattribute to fix line endings

### PR DESCRIPTION
**Pull request by Firefishy**
Force line endings using a `.gitattribute` file and and `.editorconfig` file

Likely fix for: #3312

### CODE REVIEW

**Comment by tomhughes** [comment]
I looked into that earlier but I couldn't figure out the correct settings for what we want, or even if there is actually a way to do it.

**Comment by tomhughes** [comment]
Naturally I didn't think of trying to enumerate everything that might be text because that would be crazy...

**Comment by Firefishy** [comment]
> Naturally I didn't think of trying to enumerate everything that might be text because that would be crazy...
`* text=auto eol=lf` would work reasonably well if everyone is using git >=2.10.0

**Comment by Firefishy** [comment]
https://github.com/git/git/blob/master/Documentation/RelNotes/2.10.0.txt#L248

**Comment by Firefishy** [comment]
Interesting example from Drupal: https://git.drupalcode.org/project/drupal/blob/HEAD/.gitattributes

**Comment by tomhughes** [comment]
I switched it to autodetection in b11957a3957282de3949fb80e4d6cf4576eadc1d as git 2.10 is five years old now so I doubt it's a significant issue.

**Pull request merged**
