### PR TITLE
Change comment link

### PR DESCRIPTION
**Pull request by starsep**
SVG from https://icons.getbootstrap.com/icons/link/

image

### CODE REVIEW

**Comment by tomhughes** [comment]
Please, don't just write "change comment link" as it tells us nothing.

Instead explain how you are changing the link and why - what you are aiming to achieve and why that is a good thing that we should want to merge.

**Comment by tomhughes** [comment]
It looks like you're actually adding a new link anyway, not changing one?

**Comment by starsep** [comment]
Sorry for being clear.
I am adding button (link with icon) to changeset comments.
It allows to easily copy link and reference it in external communication. It's useful when discussions get long.
At moment there is no easy way to get this link as explained in https://github.com/openstreetmap/openstreetmap-website/issues/2796

**Comment by AntonKhorev** [comment]
There's also a link icon in already existing sprites:
https://github.com/openstreetmap/openstreetmap-website/blob/77d495ccdc4c6d07cb7795177c73ba541afc44e0/app/assets/stylesheets/common.scss#L56C14

**Pull request closed without merging**
