### PR TITLE
Remove SWF gpx trackpoints feature for Potlatch1

### PR DESCRIPTION
**Pull request by mmd-osm**
This pull request removes the SWF gpx trackpoints feature which is only used to fetch gpx trackpoints in Potlatch 1. The code showed up in a static code check tool, and I was able to trigger segfaults.

Due to its limited use today, I didn't see much reason to even try and fix it. Potlatch1 would still continue to function, e.g. for people using with the Undelete function. However, the "G" (for gpx background) will cease to work. I think that's totally acceptable given the alternatives available.

### CODE REVIEW

**Comment by tomhughes** [comment]
Segfaults in what?

**Comment by mmd-osm** [comment]
One issue in the code is the lack of any input parameter sanitation. With the wrong parameter values, it will eat up all available memory, and then crashes with a segfault:

```
/home/osm/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/quad_tile-1.0.1/lib/quad_tile.rb:9: [BUG] Segmentation fault at 0x0000000200000000
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0083 p:---- s:0625 e:000624 CFUNC  :iterate_tiles_for_area
c:0082 p:0015 s:0620 e:000619 METHOD /home/osm/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/quad_tile-1.0.1/lib/quad_tile.rb:9
c:0081 p:0017 s:0612 e:000611 METHOD /home/osm/openstreetmap-website/lib/osm.rb:559
c:0080 p:0348 s:0605 E:001ab0 METHOD /home/osm/openstreetmap-website/app/controllers/api/swf_controller.rb:51


/home/osm/openstreetmap-website/lib/osm.rb:559:in `sql_for_area'
/home/osm/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/quad_tile-1.0.1/lib/quad_tile.rb:9:in `sql_for_area'
/home/osm/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/quad_tile-1.0.1/lib/quad_tile.rb:9:in `iterate_tiles_for_area'

[...]

-- Machine register context ------------------------------------------------
 RIP: 0x00007fc3631eeb85 RBP: 0x0000000080000000 RSP: 0x00007fc35cbdf750
 RAX: 0x0000000000000000 RBX: 0x000000000000ca2c RCX: 0x00000000ffffffff
 RDX: 0x000000007aec26d0 RDI: 0x0000000200000000 RSI: 0x000000007aec26d0
  R8: 0x0000000080000001  R9: 0x0000000000000000 R10: 0x0000000000000001
 R11: 0x0000000000000207 R12: 0x000000008000ca2d R13: 0x0000000000007e58
 R14: 0x0000000000000000 R15: 0x00000000ffc8f36a EFL: 0x0000000000010286

-- C level backtrace information -------------------------------------------
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7fc36fc90965) [0x7fc36fc90965]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7fc36fc90b9c) [0x7fc36fc90b9c]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7fc36fb5a884) [0x7fc36fb5a884]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7fc36fc209a2) [0x7fc36fc209a2]
/lib/x86_64-linux-gnu/libc.so.6(0x7fc36f720f20) [0x7fc36f720f20]
/home/osm/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/quad_tile-1.0.1/lib/quad_tile/quad_tile.so(tilelist_for_area+0x85) [0x7fc3631eeb85]
/home/osm/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/quad_tile-1.0.1/lib/quad_tile/quad_tile.so(0xcee) [0x7fc3631eecee]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7fc36fc79289) [0x7fc36fc79289]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7fc36fc877b3) [0x7fc36fc877b3]
```

**Comment by tomhughes** [comment]
Well the chances of anything other than Potlatch using it are minimal so that doesn't worry me too much, but just add a check against the maximum download area if you want.

**Comment by mmd-osm** [comment]
I see it more as an issue of abusing that endpoint outside of Potlatch (it's just a URL to call, after all). That's why I thought we'd be better off getting rid of it altogether.

**Comment by tomhughes** [comment]
Well it's a URL yes but doesn't it need to be called with crazy flash encoded arguments?

I don't see how we can remove it while Potlatch 1 is still a live thing.

**Comment by mmd-osm** [comment]
No, not at all. https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/api/swf_controller.rb#L9 even has an example on how to call it. 

As I said, it's non essential for Potlatch 1 to run.

**Comment by mmd-osm** [comment]
> I don't see how we can remove it while Potlatch 1 is still a live thing.

Maybe we could reach out to @systemed to sched some light on this.

My questions would be:
(1) Is the "Show GPS traces" feature really no longer functional as of today, as in my tests?
(2) Would anything else in Potlatch 1 be impacted apart from the GPS traces feature by implementing this pull request?
(3) Are there any other arguments to justify the effort to fix the code, rather than simply deleting it?
Thanks!

**Comment by systemed** [comment]
There's a few things in Potlatch 1 where the endpoints have gone away ("Find tag" points to tagstat.hypercube.telascience.org, "Find photos" points to openstreetphoto.org) so I wouldn't have an issue with the GPS call joining them. It doesn't seem to work for me either.

Anyone who really wants to load a GPS trace into Potlatch 1 can do so by uploading it to OSM, choosing 'edit' and then appending '&editor=potlatch' after the URL!

**Comment by gravitystorm** [comment]
I would normally fight tooth and nail against removing an API call without also bumping the API version number, allowing people time to upgrade etc. But I've been working for a long time on refactoring to allow us to support API version transition periods, with no end in sight in the near term. 

Given this is bust, has vulnerabilities, isn't going to be fixed, and nobody is really going to miss it, then I'm happy to see it removed now.

**Pull request merged**
