### PR TITLE
Add annotate gem and associated rake task. Annotate models. Accept new line changes in test/fixtures.

### PR DESCRIPTION
**Pull request by erictheise**
A pull request in response to @gravitystorm's [list of ideas](https://github.com/gravitystorm/openstreetmap-website/issues/2).

This
- adds the `annotate` gem
- introduces a rake task at `lib/tasks/auto_annotate_models.rake` via `rails g annotate:install`
- tweaks that task to annotate only models at the `bottom` of their `.rb`.

`annotate` polarizes developers, in my experience, and this approach is usually an acceptable intervention.

### CODE REVIEW

**Comment by tomhughes** [comment]
So of all the things on @gravitystorm's list I think this is the one I don't know anything about...

What does `annotate` do for us exactly?

**Comment by zerebubuth** [comment]
It appears to add comments into each model which explain the current schema. It seems like this would make it easier to look up that information than having to `psql` in the database, e.g: to remember what the column name is. I think this could be helpful, as this information is often hidden by Rails' "magic" and making it explicit means less frustration when the "magic" doesn't match expectations.

The `rake` task presumably maintains this information so that future migrations don't mean the comments have to be updated by hand.

**Comment by tomhughes** [comment]
Yes I did go and find the gem and figure it out after I wrote that.

I have to say I think I'd find it more annoying than helpful, but I realise that I'm probably not the target audience ;-) The flip side is that to be helpful to the people it is aimed it probably needs to be at the top although I realise @erictheise put it at the bottom to make it less annoying to people like me I fear that also makes it less useful to newcomers that aren't used to the schema.

Personally I suspect I would find the annotation of the routes (which isn't currently turned on) more useful than the annotation of the models!

I'd like to know how the auto update actually works - that didn't seem to be mentioned in the documentation I found. Does it just run when a migration is run?

**Comment by gravitystorm** [comment]
> I fear that also makes it less useful to newcomers that aren't used to the schema.

I'd prefer to see it at the top, but I'm not sure if that's just my familiarity. I use annotate on many other projects, all top-annotated, and when I'm not interested in the details, I find it easy to ignore (like ignoring big license blurbs at the top of files :-) ). Here's a large project that I use it with, for example: https://github.com/cyclestreets/cyclescape/tree/staging/app/models

But top or bottom is just a detail. Having it is, as @zere says, much easier than fishing around via psql to see what attributes are available on each model, especially given our confusing model vs table naming differences, and attributes that appear neither in the models nor the model tests.

**Comment by zerebubuth** [comment]
The code suggests it adds rake tasks automatically, but `bundle exec rake -T` doesn't show anything new. It's possible that they're automatically hooked into the migrations, or [as the wiki suggests](https://github.com/ctran/annotate_models/wiki) (see the last example) that extra work is needed for that.

**Comment by erictheise** [comment]
Like @gravitystorm, I usually top-annotate, but as @tomhughes guessed, bottom-annotation is a strategy to keep people who are already very familiar with the data model happy.

The rake task will re-annotate when running a migration, and I believe this to be a relatively new addition to the gem. Remembering to do that manually was always a weak link. See [their repo](https://github.com/ctran/annotate_models#configuration-in-rails). It's weird, as @zerebubuth points out, that the additional tasks, two of which I used in testing, don't appear when running `bundle exec rake -T`... oh, they've got [an open issue for that](https://github.com/ctran/annotate_models/issues/346).

**Comment by erictheise** [comment]
¯\_(ツ)_/¯

**Comment by gravitystorm** [comment]
@erictheise I just wanted to apologise for the way this PR was handled. Clearly leaving it for over a year isn't appropriate. At the SOTM-US hack day I considered rebasing it and making the change to top-annotate, and then I realised it was much less work for me to propose a fresh PR. So I'm sorry both that it took so long to deal with, and that it didn't build on top of your original PR.

I hope your next PR gets dealt with in a more timely fashion!

**Pull request closed without merging**
