### PR TITLE
Remove OPNVKarte as a featured layer

### PR DESCRIPTION
**Pull request by pnorman**
Part of https://github.com/openstreetmap/operations/issues/907.

People with bookmarked URLs will be directed to the standard layer

### CODE REVIEW

**Comment by mmd-osm** [comment]
Looks ok here, new cert was issued with valid from Tue, 31 Oct 2023 18:45:08 GMT

**Comment by tomhughes** [comment]
As there continue to be ongoing issues with this layer and no contact with the authors OWG are planning to go ahead with the removal.

**Comment by grischard** [comment]
@gravitystorm this is ready to go from OWG's point of view. Do you want to pull the trigger?

**Comment by tomhughes** [comment]
I can do it - the only reason I didn't do it after I rebased the other day was that we were still collecting votes on the ops channel. Did everybody weigh in with their opinion?

**Comment by pnorman** [comment]
I had thought we had already decided.

**Comment by tomhughes** [comment]
I did try and check the minutes but they weren't up, indeed they still aren't now.

**Comment by Firefishy** [comment]
@gravitystorm The OWG have approved removal. Feel free to merge.

**Pull request merged**
