### PR TITLE
Enforce Not Null Constraints on Redaction Title and Description

### PR DESCRIPTION
**Pull request by IshmeetSingh06**
Fixes: https://github.com/openstreetmap/openstreetmap-website/issues/2033

### CODE REVIEW

**Comment by tomhughes** [comment]
Just enforcing a database constraint is not very user friendly - there should be validations in the model as well.

**Comment by IshmeetSingh06** [comment]
> there should be validations in the model as well.



> Just enforcing a database constraint is not very user friendly - there should be validations in the mod

Hi @tomhughes validations are already present on the model

**Comment by tomhughes** [comment]
So how can #2033 happen then? How are the validations being bypassed?

**Comment by IshmeetSingh06** [comment]
> So how can #2033 happen then? How are the validations being bypassed?

Validations were added on November 6th 2018, while the issue was raised on October, I've checked and confirmed that even without the NOT NULL constraint we wont be able to create a redaction with empty title or description unless someone tries to create one through console, Since this is an very old issue (approx 5yrs) we can avoid adding the NOT NULL constraints (because Rails will handle that for us) and just update the test cases only.

**Comment by tomhughes** [comment]
Well if there are legacy records with null values then we may not be able to add constraints (without changing those records) but I will have to check that.

**Comment by tomhughes** [comment]
I take it all the complicated adding of check constraints and then adding null constraints and dropping the check constraints is something strong migrations insisted on?

Also you need to add the `structure.sql` changes when you add a migration as the test failure is showing.

**Comment by IshmeetSingh06** [comment]
> I take it all the complicated adding of check constraints and then adding null constraints and dropping the check constraints is something strong migrations insisted on?
Yes
> Also you need to add the `structure.sql` changes when you add a migration as the test failure is showing.
Sure will do, should I remove the block's which were backfilling the data on missing title's and descriptions?, as you've confirmed there are no such entries in the DB

**Comment by tomhughes** [comment]
> Sure will do, should I remove the block's which were backfilling the data on missing title's and descriptions?, as you've confirmed there are no such entries in the DB

I doubt that any other users of this code have redactions but it probably doesn't hurt to leave that in.

**Comment by IshmeetSingh06** [comment]
PR is ready @tomhughes

**Comment by tomhughes** [comment]
Thanks. I squashed together some of your commits to get a clean history but other than that it all looks good.

**Pull request merged**
