### PR TITLE
Update en.yml to mention how to unsubscribe

### PR DESCRIPTION
**Pull request by jidanni**
Email was missing unsubscribe link.

### CODE REVIEW

**Comment by tomhughes** [comment]
The idea is fine but the actual wording is not - it should be "unubscribe from" but in any case you're unsubscribing from the diary entry not the specific comment.

It really needs to be a separate clause rather than being wedged in with replying like that, and then it could have it's own link directly to the unsubscribe action (though that might need some server work to support GET from a mail client).

**Comment by tomhughes** [comment]
I'm kind of surprised Google thought they could show the email like that from a data protection point of view - certainly we can't though we could link to sending an OSM message.

The risk is that we wind up with developers being spammed by dozens of users demanding to know what's going on so I can't say I'm keen on it.

**Comment by gravitystorm** [comment]
> I'm kind of surprised Google thought they could show the email like that from a data protection point of view - certainly we can't though we could link to sending an OSM message.
> 
> The risk is that we wind up with developers being spammed by dozens of users demanding to know what's going on so I can't say I'm keen on it.

I think the above comment was intended for a different issue - https://github.com/openstreetmap/operations/issues/867#issuecomment-1925203709

**Comment by tomhughes** [comment]
Well the GET would redirect to the login page if necessary and then back to the original action like any other request?

It probably would need to then ask for confirmation before unsubscribing as we don't want accidental unsubscribes from things trying to "check" the URL.

**Comment by AntonKhorev** [comment]
I was going to say that with "Unsubscribe" [moved](https://github.com/openstreetmap/openstreetmap-website/pull/4518) the `#comments` link can serve as the unsubscribe link. But then I thought what if the user is not logged in? Then there would be no button.

**Comment by AntonKhorev** [comment]
I guess it should be a page like this one

image

when `/user/*/diary/*/unsubscribe` is opened with GET.

**Comment by AntonKhorev** [comment]
Is it done now with https://github.com/openstreetmap/openstreetmap-website/pull/4523 and https://github.com/openstreetmap/openstreetmap-website/commit/f0764d3ecae3aa9251eadff96990f4afe530924d for changesets?

**Comment by mmd-osm** [comment]
I think #4523 supersedes this pull request, and I don't see any follow up comments from OP except for some "eyes" emoji.
Closing here. Thanks!

**Pull request closed without merging**
