### PR TITLE
Notes: show first comment as marker tooltip

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by simon04** [comment]
Any comments on this suggestion?

**Comment by simon04** [comment]
What do you think of this enhancement?

**Comment by simon04** [comment]
I would still consider this a nice enhancement without any negative usability impact nor possible confusion … :smile:

**Comment by simon04** [comment]
@tomhughes, any comments on this?

**Comment by tomhughes** [comment]
Does it really need both those tests? Can a note not have any comments, or have a first comment that is null?

**Comment by tomhughes** [comment]
As far as I can see there are no notes in the production database which have no comments, and none where the first comment is null or blank, so I'm not convinced either test is needed.

**Comment by simon04** [comment]
Thanks for reviewing the change! I removed the two tests …

**Comment by tomhughes** [comment]
Apparently I accidentally merged the original version of this branch... I've remerged the updated version now anyway.

**Comment by HolgerJeromin** [comment]
A marker which has a sidebar open has no title tag (checked in source code). No real issue.

I really like this :-)

**Pull request closed without merging**
