### PR TITLE
Update xid_to_int4.c

### PR DESCRIPTION
**Pull request by dim3dro1**
Made changes to avoid error when executing "CREATE FUNCTION xid_to_int4(xid) RETURNS int4 AS '`pwd`/db/functions/libpgosm', 'xid_to_int4' LANGUAGE C STRICT".

### CODE REVIEW

**Comment by tomhughes** [comment]
More details please - what sort of error?

If you're referring to the error in postgres 9.7 in later then that is known about and can't be fixed by this or anything else which is why we are stuck on 9.6 until we re-engineer things.

**Comment by tomhughes** [comment]
Sorry I meant 9.6 or later - we are stuck on 9.5 as a result.

**Comment by pnorman** [comment]
Wouldn't the proposed changes substantially change xid_to_int4 and break it, no longer converting an xid to int4?

**Comment by tomhughes** [comment]
Well I have no idea what they do, but we know that function is doing is not a good idea anyway. Basically if you want to do incremental dumps (which is the only reason for needing that function) you need to stick to postgres 9.5 or earlier.

**Pull request closed without merging**
