### PR TITLE
Add "BBBike Extracts" to the list of export services in the left sidebar

### PR DESCRIPTION
**Pull request by wosch**
I'm the maintainer of the BBBike extract service. BBBike extracts
allows you to extracts areas from Planet.osm in OSM, PBF, o5m, Garmin,
Navit, Osmand, mapsforge CSV, SVG, maps.me, libosmium OPL, or Esri
shapefile format.

https://extract.bbbike.org/

I'm wondering if it is possible to add a link to the BBBike Extract service
on the main "OpenStreetMap | Export" page, in the left sidebar.

https://www.openstreetmap.org/export#map=12/49.0158/8.4093

thanks, Wolfram

### CODE REVIEW

**Comment by tomhughes** [comment]
I guess I can't refuse, but this is exactly why I hate linking to external services...

**Comment by pnorman** [comment]
I'd prefer to change the wiki link to https://wiki.openstreetmap.org/wiki/Planet.osm and fix the usability problems in that page instead of having `/export` become a laundry-list of extract providers.

**Comment by wosch** [comment]
Hi guys,

I'm wondering what the status of this pull request is - will you add the BBBike Extract service to the list of export services?

thanks, Wolfram

**Comment by mmd-osm** [comment]
No decision since 5 years and @pnorman has raised some objections.

**Pull request closed without merging**
