### PR TITLE
update jquery-rails to 4.1.0

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by tomhughes** [comment]
Why?

**Comment by nikolas** [comment]
Because jquery 1.12.0 contains many bugfixes

**Comment by tomhughes** [comment]
Which will get the next time the bundle is updated for any reason. If there's a concrete problem that this solves then fine, although it should be done by setting a requirement in the Gemfile in that case (Gemfile.lock should never be changed directly) but other than that I don't see any urgency to upgrade.

**Comment by nikolas** [comment]
I didn't change Gemfile.lock directly, I updated the gem via `bundle update jquery-rails`.

**Pull request closed without merging**
