### PR TITLE
Changed windowslive user strings to Microsoft login

### PR DESCRIPTION
**Pull request by konrad-wila**
#1828

### CODE REVIEW

**Comment by gravitystorm** [comment]
Thanks @konrad-wila for the PR! A couple of quick points:

1. For the translations files, please only make changes to the en.yml file.

    https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md#i18n

2. Your second commit will also need merging into the first, since it's just undoing the changes to the Gemfile.

    https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md#pull-requests (Avoid including "fixup" commits.)

**Comment by tomhughes** [comment]
You don't have to close a PR just because we ask for changes, it's much better to force push an update and keep all the history in once place than to open a new PR with the modified version.

**Comment by tomhughes** [comment]
I assume from your comment on #1828 that you're planning to change this again to only change the UI text?

**Comment by tomhughes** [comment]
Please don't delete `yarn.lock` and `Gemfile.lock`.

**Pull request closed without merging**
