### PR TITLE
Update OSGB date range for copyright

### LINKED ISSUE #3845: Ordnance Survey Dates on Copyright page(s) need updating
### URL

https://www.openstreetmap.org/copyright

### How to reproduce the issue?

The section:

"United Kingdom: Contains Ordnance Survey data © Crown copyright and database right 2010-19."

should read:

United Kingdom: Contains Ordnance Survey data © Crown copyright and database right 2010-**22**."

And from early in January should read "2010-23"

I believe in some language versions this is even more out-of-date (e..g, some files from Translate Wiki seem to contain "2010-2"), but these are less significant than the EN version.

I've corrected this in my fork, and will try and create a PR

### Screenshot(s) or anything else?

_No response_

### PR DESCRIPTION
**Pull request by SK53**
Change the date range for Ordnance Survey Open Data licensed under the Open Government Licence (OGL) from "2010-19" to "2010-22" to comply with OGL terms.

Fixes #3845

### CODE REVIEW

**Comment by gravitystorm** [comment]
I'm marking this as a draft, and adding the "Awaiting Upstream" label, since as @tomhughes explained in the related issue we can only make changes to this page with approval from LWG.

@SK53 Please contact LWG with your proposed changes, and we will wait for an LWG member to indicate on this PR that the proposed changes are approved.

**Comment by SK53** [comment]
@tomhughes The dates appear to be part of the standard licence requirement, although am having difficulty finding the rubric on the current OSGB downloads page. If dates are no longer required obviously that would be nice. I'm making further enquiries.

@gravitystorm Am writing to LWG as requested.

**Comment by gravitystorm** [comment]
> @gravitystorm Am writing to LWG as requested.

Has there been any progress with this? Any response from LWG?

**Comment by gravitystorm** [comment]
I'm going to close this PR for now, since it's been a few months without updates.

However, please feel free to reopen when you have received approval from LWG.

**Comment by mackerski** [comment]
LWG wishes to change the up-to date to 2023

**Comment by gravitystorm** [comment]
Thanks @mackerski and @SK53

**Pull request merged**
