### PR TITLE
Add link to more OSM renderings on the wiki

### PR DESCRIPTION
**Pull request by math1985**
This should make discovery of OSM applications beyond what is
displayed on the main website easier.

### CODE REVIEW

**Comment by tomhughes** [comment]
Why on earth does this belong in the layer switcher?

**Comment by math1985** [comment]
> Why on earth does this belong in the layer switcher?

That's the place where people look if they want to change the style of the map. Currently, it looks like there are only five map styles. A 'more' link would make it clear that the five styles we display are not the only ones, and that we offer more variety for users for which the five styles not suffice. It's also a bit of a compromise for the people who want to add even more styles to osm.org.

However, if you think the link fits better at a different place, or is not that useful in general, I'd be happy to change or close my PR.

**Comment by tomhughes** [comment]
Well I think the issue that you're characterising a link to a page that is just a massive collection of anything that has ever used OSM in any was as a link to a list of alternate map styles.

The location you've chosen might be a valid place for a link to a list of alternate map styles but that isn't what you're linking to.

In general I'm not a big fan of linking to the wiki from prominent locations on the main site because of the difficulty of knowing if the content will remain appropriate over time, and because the wiki is basically a massive cess pit.

**Comment by math1985** [comment]
Would maintaining a list of alternative map styles on the website be an option? It would eliminate most of the problems you mention, but it might be a significant maintenance effort.

**Comment by simonpoole** [comment]
The link to the wiki page is a definte nono IMHO there is just nothing on it that is going to help anybody. Something like http://mapstyle.petschge.de/ would be far better and could include licensing information and similar in a reasonably legible and modern form. .

From an UI pov if something along such lines is done I would however believe that is would be better (if the providers of the tiles are ok with it) to actually make the layer selector customizable aka the user could store his preferred layer config in the preferences for his account. This is obviously a lot more work that a simple link and I'm not volunteering right now.

**Comment by math1985** [comment]
Closing this as the proposal has no support in its current form, and I currently have no time to maintain or compile a list of alternative styles myself.

**Pull request closed without merging**
