### PR TITLE
Replace blogs.osm.org with blog.osm.org

### LINKED ISSUE #260: Replace blogs.osm.org with blog.osm.org
Right now there is a link to blogs.openstreetmap.org on the frontpage. Since we now have an "official" (?) blog, I don't think it's reasonable anymore to link to that aggregator, which often has spam posts at the top. On the other hand, blog.osm.org cannot be called a community blog, but there is diary link as well, so I guess that isn't a problem.

### PR DESCRIPTION
**Pull request by simon04**
Fixes #260.

### CODE REVIEW

**Comment by tomhughes** [comment]
They're two completely different things.

**Comment by simon04** [comment]
This is exactly the purpose of #260: `blogs.osm.org == osm.org/diary` and both links are currently placed next to each other. So the idea is to replace `blogs.osm.org` by a more helpful link.

**Comment by tomhughes** [comment]
No blogs.osm.org is not in any way equal to osm.org/diary.

It includes the diaries yes, but also many other feeds as well. One of them being blog.osm.org in fact!

**Comment by simon04** [comment]
If everything shall stay the same, then #260 can be closed (as has been done for #583).

**Comment by tomhughes** [comment]
I'm not saying we can't add it, but adding and replacing are two different things...

To be honest I'm not sure what the right answer is. I know blogs was known for getting lots of irrelevant stuff at one point but it's not something I've ever followed myself.

What do other people think?

My thought would be that blog.osm.org should be the first thing shown to the user, followed by blogs and/or diaries but I'm open to other people's thoughts on the exact solution.

**Comment by danstowell** [comment]
IMHO, I vote for the status quo. These entries are not on the homepage now, they're in the "about" section under "Community Driven", and those two things (user diaries and community blogs) are two good links, even though they overlap a lot. blog.osm.org is not relevant to the subheading "Community Driven"

**Comment by SomeoneElseOSM** [comment]
My 2p is that it'd be nice to have something that was an aggregation of OSM blogs (i.e. the current blogs.osm.org without the diary entries).  I really don't care what it's called.  That was essentially the point of #583 - that two links from the about page link to (mostly) the same content.

**Comment by gravitystorm** [comment]
There's definitely a lot of overlap between the aggregator and the diary entries + osm blog. But I don't think that the right solution is to remove the link to the aggregator, since that remove all links to the non-overlapping content, so I'm going to close this PR.

**Pull request closed without merging**
