### PR TITLE
Add Ascend/Descend when routing with GraphHopper

### PR DESCRIPTION
**Pull request by alkino**
Here is a little improvment by adding Ascend and Descend.

Really needed when routing for bike or foot.

I want to add an elevation plot but as it's my first patch I do it slowly.

Thanks for futures reviews.

### CODE REVIEW

**Comment by tomhughes** [comment]
Is this really useful? What is that number? Is is the height difference between start and end points or the total height climbed minus total heigh descended?

There's also the question of whether this is useful for the purpose that routing existing on OSM which is to say for debugging the map - we're not trying to provide an end user routing service.

**Comment by alkino** [comment]
The documentation of GraphHopper say it's `The total ascend/descend (uphill/downhill) of the route, in meter`.
It is really useful when we do bike or foot.
After if routing is not a feature, maybe it's not useful.

**Comment by alkino** [comment]
Bump?

**Comment by zerebubuth** [comment]
I think the question is whether this is something that's useful to a large number of people. Is it available from any of the other routing engines?

Seems like a minor change to the UI, and it doesn't seem like adding this would have much negative impact on usability or clutter. My conclusion would be "why not add it"?

**Pull request merged**
