### PR TITLE
Updated wiki links and script

### LINKED ISSUE #943: List of wiki pages (config/wiki_pages.yml) is outdated
Scraped list was last updated in june 2014, almost a year ago:
https://github.com/openstreetmap/openstreetmap-website/commits/master/config/wiki_pages.yml

Please re-run script/misc/update-wiki-pages.
Thanks

### PR DESCRIPTION
**Pull request by stefanb**
Cherry picked this time ti properly fix #943

### CODE REVIEW

**Comment by tomhughes** [comment]
Why do we need to allow the retries? If our wiki is not responding correctly first time we should fix that, not patch around it!

**Comment by pnorman** [comment]
Depending on the number of pages to fetch some failures are expected.

@stefanb was it the rare occasional failure, or a reasonable number of failures that you got?

**Comment by stefanb** [comment]
It happened every time, interestingly always in the same batch after 3200 fetched links (see committ comment for exact output). If it was a permenant problem in one particular wiki page retries wouldn't help. I also tried decreasing batch size to 100 links, with no difference.

**Comment by tomhughes** [comment]
I've merged the update of the links, but the script seems to work fine for me so I don't see any reason to add the retries - if somebody can reproduce the problem then I would rather investigate it on the wiki server.

**Pull request closed without merging**
