### PR TITLE
Pan to first Nominatim search result

### PR DESCRIPTION
**Pull request by simon04**
This implements #919.

### CODE REVIEW

**Comment by tomhughes** [comment]
I think `clickSearchResult` needs to be split, so that the "zoom to object" logic is in a separate function that is invoked both from the click handler and from the XHR success handler.

Otherwise if the first result does not have an OSM type and id (in other words if it's not from nominatim) then we will wind up invoking `preventDefault` etc on `false.

**Comment by pnorman** [comment]
@simon04 Any plans to integrate the above comments or is this PR abandoned?

**Comment by simon04** [comment]
Well, thanks for the remainder @pnorman and thanks for the feedback @tomhughes  – I forgot about this PR. e085977547051333e6d4fb4e46f2e8616a9614bb should do the trick.

**Comment by Zverik** [comment]
LGTM

**Pull request closed without merging**
