### PR TITLE
Update to iD v1.8.0

### PR DESCRIPTION
**Pull request by bhousel**
## 1.8.0
* Don't update the urlhash during the walkthrough
* Add surface type to parking preset 
* Make 100% background brightness the default 
* Use SVG for preset and feature icons
* Add "Help Translate" icon next to "Report a Bug"
* Update highway colors to match openstreetmap-carto
* Prefer suggested capitalization in autocomplete box 
* Better support for browser language preferences
* Disallow joining ways with conflicting tags 
* Add rugby union and rugby league presets 
* Add military presets 
* Discard yh:WIDTH tags
* Fetch proper tag references for relation types
* Proper perimeter calculation in infobox
* Fix bug creating points at edge of screen when panning 
* Add motorcycle parking preset 
* Better autocomplete suggestions in taginfo-sourced dropdowns 
* Add traffic signal type field
* Fix bug where pressing '1' triggered fullscreen 
* Improvements to translated preset terms
* Disable save button when changeset comment is empty 
* Better handling of multilingual `alt_name`, `old_name`, etc
* Add preset for Semi-Detached House

### CODE REVIEW

**Comment by tomhughes** [comment]
Something doesn't seem to he working - a lot of image seem to be missing or something:

screenshot from 2015-11-08 08-27-16

As you can see there are no image in the tool palette at the end of the selected road, or again the road type in the top left.

There don't appear to be any resources failing to load though...

**Comment by bhousel** [comment]
Very strange..

On http://dev.osm.compton.nu/  
* __Chrome 46.0.2490.80__ - I'm getting "This editor is supported in Firefox, Chrome, Safari, Opera, and Internet Explorer 9 and above. Please upgrade your browser or use Potlatch 2 to edit the map."  
* __Firefox 41.0.2__ - it looks like your screenshot, no icons.


However I'm running a local rails stack and everything looks good there in either browser:

screenshot 2015-11-09 00 52 22

**Comment by tomhughes** [comment]
So I am still seeing this, both on http://dev.osm.compton.nu/ and http://tomh.apis.dev.openstreetmap.org/ and using both Firefox 41 and Chromium 46 on Linux.

What I see, taking the undo and redo buttons as an example, is that in the previous version that are `<span class="icon undo"></span>` with the sprite SVG attached as background in the CSS.

In the new version they are `<svg class="icon "><use href="#icon-undo"></svg>` and the CSS rule that used to attach the sprite is deleted, and indeed the undo and redo icons no longer appear to be in the sprite.

So how should the image be getting attached now?

**Comment by tomhughes** [comment]
Think I've figured it out now... We running `svgo` on SVG images as part of the asset pipeline but I think that is discarding what appear to be unused symbols.

Of course they're not really unused because other parts of the DOM are referring to them...

**Comment by tomhughes** [comment]
I've opened https://github.com/toy/image_optim/pull/110 to add support for disabling svgo plugins so we can disable the `cleanupIDs` plugin...

**Comment by bhousel** [comment]
> Think I've figured it out now... We're running svgo on SVG images as part of the asset pipeline but I think that is discarding what appear to be unused symbols.

Yes good catch!  That's exactly the issue..

I turned on the asset caching and compilation in the development environment and now I'm seeing it too.  

Amusingly, this is what `maki-sprite.svg` looks like post-optimization:
```
<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="position:absolute" />
```


Setting `svgo: false` in `image_optim.yml` does fix the issue, but I don't think it's a great solution, as it changes the size of the osm logo from 11k to 170k (and who knows what else).

`svgo` does support a config file, I'm going to see if I can just put one somewhere and have the `svgo` binary use it.

**Comment by tomhughes** [comment]
Disabling the `cleanupIDs` plugin fixes it, but currently there is no way to do that via the `image_optim` gem that we use, hence my PR for it.

**Comment by bhousel** [comment]
Great thanks!  Yes `cleanupIDs` is the one - hope the PR is accepted quickly.

I just realized that I can also just edit my global `.svgo.yml` config file to say ` - cleanupIDs: false` to get the icons back.  But that is really hacky.

**Comment by bhousel** [comment]
Thanks @tomhughes!

**Pull request merged**
