### PR TITLE
Mention finishing application and database setup after vagrant ssh

### PR DESCRIPTION
**Pull request by geohacker**
Added a line to link INSTALL.md to complete application and database setup in case people are using vagrant to run the development environment.

### CODE REVIEW

**Comment by tomhughes** [comment]
I'm not familiar with the vagrant scripts, but I thought they did the setup for you?

**Comment by tomhughes** [comment]
Isn't https://github.com/openstreetmap/openstreetmap-website/blob/master/script/vagrant/setup/provision.sh suppose to take care of it?

**Comment by geohacker** [comment]
@tomhughes - thank you! I missed that - for some reason it didn't setup the database and application for me. Let me try setting up from scratch and see where it went wrong.

**Comment by geohacker** [comment]
I was wrong. The provisioning script failed so it didn't do rest of the steps:

```
   default: Done installing documentation for bundler after 3 seconds
    default: 1 gem installed
    default: /srv/openstreetmap-website /home/vagrant
    default: There was an error while trying to write to
    default: `/srv/openstreetmap-website/.bundle/config`. It is likely that you need to grant
    default: write permissions for that path.
```

This is probably unrelated and need a chmod in the provisioning script. Will move to a different PR. Thanks!

**Pull request closed without merging**
