### PR TITLE
JSON output added to changeset(s) endpoints

### PR DESCRIPTION
**Pull request by mmd-osm**
First draft to address missing JSON output for a number of different changeset(s) API endpoints. 

The JSON format probably still needs a bit of tweaking (happy to see some comments). Also, unit tests are still missing at this time.

Example for: http://localhost:3000/api/0.6/changesets.json?user=1

```json
{
  "version": "0.6",
  "generator": "OpenStreetMap server",
  "copyright": "OpenStreetMap and contributors",
  "attribution": "http://www.openstreetmap.org/copyright",
  "license": "http://opendatacommons.org/licenses/odbl/1-0/",
  "changesets": [
    {
      "id": 1874604,
      "created_at": "2022-02-02T17:35:00Z",
      "open": false,
      "comments_count": 0,
      "changes_count": 0,
      "closed_at": "2022-02-02T18:35:00Z",
      "uid": 1,
      "user": "mmd2",
      "tags": {
        "created_by": "JOSM/1.5 (18364)"
      }
    },
    {
      "id": 1874603,
      "created_at": "2022-01-29T14:41:11Z",
      "open": false,
      "comments_count": 0,
      "changes_count": 0,
      "closed_at": "2022-01-29T15:41:11Z",
      "uid": 1,
      "user": "mmd2",
      "tags": {
        "comment": "test",
        "created_by": "JOSM/1.5 (18364)"
      }
    }
  ]
}
```

Example for: http://localhost:3000/api/0.6/changeset/00...000.json

```json
{
  "version": "0.6",
  "generator": "OpenStreetMap server",
  "copyright": "OpenStreetMap and contributors",
  "attribution": "http://www.openstreetmap.org/copyright",
  "license": "http://opendatacommons.org/licenses/odbl/1-0/",
  "changesets": [
    {
      "id": 1874526,
      "created_at": "2020-07-25T20:47:51Z",
      "open": false,
      "comments_count": 1,
      "changes_count": 4,
      "closed_at": "2020-07-25T20:47:51Z",
      "min_lat": -4.2786786,
      "min_lon": -36.6031079,
      "max_lat": -4.2776831,
      "max_lon": -36.6021764,
      "uid": 1,
      "user": "mmd2",
      "tags": {
        "changesets_count": "1706",
        "comment": "some comment",
        "created_by": "iD 2.17.3",
        "host": "http://localhost:31900/edit",
        "imagery_used": "Bing aerial imagery",
        "locale": "en"
      }
    }
  ]
}
```

Example for: http://localhost:3000/api/0.6/changeset/1874526.json?include_discussion=true

```json
{
  "version": "0.6",
  "generator": "OpenStreetMap server",
  "copyright": "OpenStreetMap and contributors",
  "attribution": "http://www.openstreetmap.org/copyright",
  "license": "http://opendatacommons.org/licenses/odbl/1-0/",
  "changesets": [
    {
      "id": 1874526,
      "created_at": "2020-07-25T20:47:51Z",
      "open": false,
      "comments_count": 1,
      "changes_count": 4,
      "closed_at": "2020-07-25T20:47:51Z",
      "min_lat": -4.2786786,
      "min_lon": -36.6031079,
      "max_lat": -4.2776831,
      "max_lon": -36.6021764,
      "uid": 1,
      "user": "mmd2",
      "tags": {
        "changesets_count": "1706",
        "comment": "g",
        "created_by": "iD 2.17.3",
        "host": "http://localhost:31900/edit",
        "imagery_used": "Bing aerial imagery",
        "locale": "en"
      },
      "comments": [
        {
          "date": "2020-08-16T20:15:34Z",
          "uid": 1,
          "user": "mmd2",
          "text": "dfasdfasdfdfasdfasdf"
        }
      ]
    }
  ]
}
```

### CODE REVIEW

**Comment by mmd-osm** [comment]
I think it might be worthwhile comparing different options for a single changeset in `changeset.json.jbuilder`:

#### Option 1: Put single changeset in changesets array:

```ruby
json.partial! "api/root_attributes"

json.changesets([@changeset]) do |changeset|
  json.partial! changeset
end
```
(see example above)

#### Option 2: changeset element with single chageset

```ruby
json.partial! "api/root_attributes"

json.changeset do
  json.partial! @changeset
end
```

```json
{
  "version": "0.6",
  "generator": "OpenStreetMap server",
  "copyright": "OpenStreetMap and contributors",
  "attribution": "http://www.openstreetmap.org/copyright",
  "license": "http://opendatacommons.org/licenses/odbl/1-0/",
  "changeset": {
    "id": 1874552,
    "created_at": "2021-01-23T22:01:04Z",
    "open": false,
    "comments_count": 0,
    "changes_count": 260,
    "closed_at": "2021-01-23T22:01:13Z",
    "min_lat": -12.2373657,
    "min_lon": -45.9127416,
    "max_lat": 13.8360116,
    "max_lon": -25.2032019,
    "uid": 2,
    "user": "mmd3",
    "tags": {
      "created_by": "JOSM/1.5 (17473)"
    },
    "comments": []
  }
}
```

#### Option 3: Merge changeset attributes in higher level element:

```ruby
json.partial! "api/root_attributes"

json.partial! @changeset
```

```json
{
  "version": "0.6",
  "generator": "OpenStreetMap server",
  "copyright": "OpenStreetMap and contributors",
  "attribution": "http://www.openstreetmap.org/copyright",
  "license": "http://opendatacommons.org/licenses/odbl/1-0/",
  "id": 1874553,
  "created_at": "2021-01-23T22:01:41Z",
  "open": false,
  "comments_count": 2,
  "changes_count": 10000,
  "closed_at": "2021-01-23T23:05:28Z",
  "min_lat": -13.6479226,
  "min_lon": -62.78181,
  "max_lat": 22.8223133,
  "max_lon": -24.9335172,
  "uid": 2,
  "user": "mmd3",
  "tags": {
    "created_by": "JOSM/1.5 (17473)"
  }
}
```

Option 1 is the one currently implemented. I'm not sure which of those options would make most sense here.

**Comment by tomhughes** [comment]
Option 1 of a single entry array appears to be in line with what we do for nodes, ways and relations? Consider https://www.openstreetmap.org/api/0.6/node/1.json which gives:

```json
{
  "version": "0.6",
  "generator": "CGImap 0.8.6 (225879 spike-08.openstreetmap.org)",
  "copyright": "OpenStreetMap and contributors",
  "attribution": "http://www.openstreetmap.org/copyright",
  "license": "http://opendatacommons.org/licenses/odbl/1-0/",
  "elements": [
    {
      "type": "node",
      "id": 1,
      "lat": 42.7957187,
      "lon": 13.5690032,
      "timestamp": "2022-02-04T18:05:40Z",
      "version": 30,
      "changeset": 117017136,
      "user": "ilya_bohaslauchyk",
      "uid": 12070073,
      "tags": {
        "communication:microwave": "yes",
        "communication:radio": "fm",
        "description": "Radio Subasio",
        "frequency": "105.5 MHz",
        "man_made": "mast",
        "name": "Monte Piselli - San Giacomo",
        "tag": "111",
        "tower:construction": "lattice",
        "tower:type": "communication"
      }
    }
  ]
}
```
with an single entry array of elements.

**Comment by mmd-osm** [comment]
Right, I think we already have all three options in place in different parts of the API:

- Option 1: app/views/api/ways/show.json.jbuilder
- Option 2: app/views/api/users/show.json.jbuilder + app/views/api/users/_user.json.jbuilder
- Option 3: app/views/api/notes/show.json.jbuilder

For nodes/ways/relations (single or multiple ones) I deliberately used the same [OSM JSON](https://wiki.openstreetmap.org/wiki/OSM_JSON) format everywhere, to avoid any special case parsers for single objects.

Option 3 for notes follows some GeoJSON format, and seems to be a good fit for that particular use case.

Now for single changesets, I believe either option 1 or 2 would be reasonable.

**Comment by gravitystorm** [comment]
I think Option 2 is my preference. I mean, I gave a quick review of this PR and was about to question the whole Option 1 approach thing as being a bit weird, before realising it was what is done for nodes and ways already.

But on consideration, I think we made the wrong decision for nodes and ways. I think there's a difference between asking for an API call which might contain more than one node, but getting an array with only one node in it, versus asking for one specific object and getting an array back, which is unintuitive. I'd expect `get_changeset(1235)` to return a changeset, without having to do `get_changeset(1234).changesets.first` to get hold of it (and then having to wonder if empty arrays, or arrays with more than one object, could be valid responses). So my line of thinking is similar for the HTTP REST requests - if the client request is for one changeset, we should return a changeset object and not an array of changesets with one changeset inside.

I don't like Option 3 since it leads to namespace clashes e.g. on the version attribute, where objects can have a version as well as the response format having a version. The other document attributes are less likely to clash, but I still find it useful to separate them out.

Everything I write above is a bit subjective though so I'm not dead-set on anything.

**Comment by mmd-osm** [comment]
> But on consideration, I think we made the wrong decision for nodes and ways

Well, as I've written earlier, keeping the OSM JSON format in sync with what Overpass API was using for many years means less confusion for data consumers due to incompatible formats. (See https://overpass-turbo.eu/s/1gRL for a query returning a single node)

> I think Option 2 is my preference.

👍

**Comment by gravitystorm** [comment]
I'm happy to merge this as-is, but I'd just like to check with @tomhughes that he has no objections to the "Option 2 approach" first.

**Comment by tomhughes** [comment]
I don't care either way.

**Pull request merged**
