### PR TITLE
Add rotating banner for SotM Asia and remove FOSSGIS and SotM US

### PR DESCRIPTION
**Pull request by seav**

### CODE REVIEW

**Comment by tomhughes** [comment]
Please don't patch non-english locales - only config/locales/en.yml should be editied in git and all other translations should be done via TranslateWiki.

**Comment by tomhughes** [comment]
In fact english is the one locale you haven't edited, and it's the most important...

**Comment by tomhughes** [comment]
Hmm doesn't look like you did edit them, but there's something funky about your branch history...

**Comment by tomhughes** [comment]
My fault - I hadn't pulled the latest localisation change so wound up getting it from your branch. Now merged as c4c99bf413596a3fadcf2e1d54b00710001f7ab7.

**Comment by seav** [comment]
Thanks for the merge! (Although I am baffled why the Travis CI build failed.)

**Pull request closed without merging**
