### PR TITLE
Set color & background-color in searchbox

### PR DESCRIPTION
**Pull request by ximex**
Set color & background-color in searchbox for ubuntu gnome dark theme

### CODE REVIEW

**Comment by ximex** [comment]
This is how it looks like in Ubuntu Gnome - dark theme
searchbox_osm

**Comment by ximex** [comment]
ok nerly every input-box or textarea have this problem and should get a color and bg-color

**Comment by tomhughes** [comment]
Err, we're not going to change the whole web site based on what your desktop looks like!

**Comment by ximex** [comment]
it's not about changing the website. it's about set css values from some desktops they have different default values. it's like a normalize.css for input elements

**Comment by tomhughes** [comment]
Oh you mean that picture is how it looks now, not how you want it to look?

I have to say I'm surprised that a desktop theme is somehow infecting a browsers default style... It's not clear to me if it's reasonable to override that though - it depends whether that element wasn't explicitly styled because we wanted the browser default or just because the browser default generally looked good.

How did you choose the colours to use? Presumably you tried to use something close to what other browsers/desktops use? But which ones?

**Comment by ximex** [comment]
yes this is how it looks like yet.
The problem is that the browsers took the default design of the host system for input fields. only if you override this values it looks the same.
Here i found an example: http://formalize.me/assets/images/chrome_examples.png

I dont't know if there is this problem with other systems to. Maybe it looks different in mac osx or ubuntu, win7, win8, ... too

**Comment by tomhughes** [comment]
Well on my machine the input field appears to inherit the text colour from body (#222) and the background appears to be pure white - firebug doesn't show that as inherited from the body but checking the colour of a screenshot in gimp gives me #fff.

**Comment by tomhughes** [comment]
Certainly if it is needed that it should go in the reset section at the top of common.css so it applies everywhere.

**Comment by ximex** [comment]
yes i think this would be the best soloution. what i saw, it should only need to set color and background-color to all inputs (text, button, submit, ...) and textareas

maybe it is done with:
input, textarea {
  color: $somevalue;
  background-color: $somevalue;
}
and after that we have to look if this changes some style (i don't think so)

**Pull request closed without merging**
