### PR TITLE
Add MAPS.ME authentication

### PR DESCRIPTION
**Pull request by Zverik**
**Please do not comment "I support this", use the reaction button in the top right corner instead.**

We, as in maps.me, have published the first alpha version of our own authentication service, [passport.maps.me](https://passport.maps.me/accounts/login/) (does not have the front page yet). The plan is to use it instead of osm.org oauth to authenticate users, and then register them on osm.org using that account.

It would give us an independent profile storage and, more important, an option to use native SDKs for facebook and google on mobile devices. I could not negotiate that for osm.org (re: #1114 and mailing lists), so we decided to make an alternative service. It might be possible for other mobile apps to use the same service. That would be a benefit for other authors of OSM mobile editors, simplifying their sign-up workflow.

Until it is possible to link multiple social accounts to a profile (see #1274), we plan to use this only for new users, directing existing users to osm.org for all kinds of linked accounts, including facebook and google. Nothing is changed for the osm side, besides a new icon on the login page.

This pull requests adds two auth providers: `mapsme` for a regular web-based authentication via the passport site, and `mapsme_token` for a token-based authentication, which would allow skipping the passport site when logging in on a mobile device. The latter rewrites the provider string to `mapsme`, so there is no difference to the database which one of these is used.

You can test this at http://test.osmz.ru.

### CODE REVIEW

**Comment by woodpeck** [comment]
Please clarify "the plan is to use it instead of osm.org oauth to authenticate users, and then register them on osm.org using that account" - I'm not sure I understand this fully. Does this workflow still ensure that the human being operating the account will always see our sign-on page, contributor terms, and everything, or could this be sacrificed for a "simplified workflow"?

**Comment by Zverik** [comment]
Contributors are always directed to a proper OSM sign-up page: they check their e-mail and account name, read the terms and so on. Nothing is changed on that part. This PR only adds a new authentication provider, and the reason for that I tried to explain.

What I forgot is that e-mail addresses from passport.maps.me are considered verified: we take these only from verified source (google and facebook at the moment).

**Comment by tomhughes** [comment]
Hmm I'm surprised we are considering facebook provided emails as verified as I don't believe they are verified in any real sense - like most sites they will probably have verified it when the user signed up but that might have been years ago.

Google is different because they only provide gmail address and as they own those they know what is really valid at any given point in time.

**Comment by tomhughes** [comment]
Hmm apparently @Zverik did that ;-) Not sure how you got me to accept it though!

**Comment by tomhughes** [comment]
Before we go any further you're going to have to explain better what the second provider is all about - from a quick look at the patch it's defined as an extra omniauth provider but isn't hooked up to anything.

Can you give a detailed explanation of the flow that uses that, and why it needs to be a separate provider rather than piggybacking on the other one?

**Comment by Zverik** [comment]
> Hmm I'm surprised we are considering facebook provided emails as verified as I don't believe they are verified in any real sense - like most sites they will probably have verified it when the user signed up but that might have been years ago.

The same is true for OSM emails. In #1096 we found evidence that Facebook only provides verified emails, but if we take into account that all addresses become obsolete with time, then we should not treat anything to be verified, and even maybe ask users to re-verify their email addresess once a year.

> Can you give a detailed explanation of the flow that uses [`mapsme_token` provider], and why it needs to be a separate provider rather than piggybacking on the other one?

The provider is included in `omniauth-mapsme` gem. After a successful authentication it replaces the `:provider` field with `mapsme`, imitating a sign-in with that provider. It is built after the [omniauth-facebook-access-token](https://github.com/SoapSeller/omniauth-facebook-access-token), which is also invisible to the target app.

Regular OAuth2 flow from the `mapsme` provider is:
1. User goes to `%osm%/auth/mapsme`
2. User is redirected to `https://passport.maps.me/oauth/authorize?...&state=399whatever99`
3. User authorized against maps.me server, if not yet
4. User is redirected back to `%osm%/auth/mapsme/callback?code=...&state=399whatever99`
5. Server sends a request to `passport.maps.me` with the given code and receives as access token
6. Server uses that token to query the provider for user id and email
7. User is redirected to a relevant page, or `%osm%/user/new`.

Now, if we already have an access token, we would want to skip steps 2-5 and simply give the server the token. It is not bound to an application, so you can make requests even from a different country using the same token. Alas, we have no way of giving the token in that workflow: it has only intermediate steps.

The workflow with a prepared token is:

1. User goes to `%osm%/auth/mapsme_token/callback?access_token=123whatever456`
2. Server uses that token to query the provider for user id and email
3. User is redirected to a relevant page, or `%osm%/user/new`.

In theory I could merge these two strategies into one, checking in `callback_phase` whether the `access_token` parameter is specified, but it would be harder than just to make two separate strategies.

With a mobile app, when signing in to OSM via a facebook, the following workflow would be used:

1. Sign in to Facebook or Google using a Native SDK and get an fb_access_token
2. Use fb_access_token to sign in to passport.maps.me using a series of API calls, and get an access_token
3. Open a WebView for `https://www.openstreetmap.org/auth/mapsme_token/callback?access_token=...` and wait for it to return osm_access_token and osm_access_secret.

This way a user won't have to type their password for anything, since WebView doesn't have cookies from a native sdk or from sessions in a web browsing app. And even if that was okay, Google will start [blocking OAuth requests](https://www.theregister.co.uk/2016/08/23/google_to_block_web_views_from_using_its_oauth/) in a WebView starting this April.

**Comment by tomhughes** [comment]
So on the basis of that it seems to me that this is missing tests for the token based flow?

**Comment by tomhughes** [comment]
As far as "verified" emails go I understand what you're saying but we really want to be sure we can at least send a working welcome email, which means knowing that the email is working right now.

That's why I am surprised I agreed to make that change as my intention had been to ensure that whatever email we had was working at the time they signed up even if it later stopped working.

**Comment by Zverik** [comment]
> So on the basis of that it seems to me that this is missing tests for the token based flow?

Possibly. I'll see how to do them then.

> As far as "verified" emails go I understand what you're saying but we really want to be sure we can at least send a working welcome email, which means knowing that the email is working right now.

So why do we have verified email providers then? You can register in Google with your other, non-gmail email, which I did. Google does not send anything to that email, apart from rare google docs notifications. You could have registered in Yahoo Mail 20 years ago and use the account only for authentication. Verification flag for these was introduced in 104727f889aaf31f917c8243014b161732b6e351 in 2012. Are you saying we don't trust any third-party server now and the e-mail should be validated in all cases?

**Comment by Zverik** [comment]
Also, what's the point of testing the email address on registering, when it can be easily abandoned 5 minutes after that (re: mailinator)? We don't send any vital information to it. The best way to ensure email validity is to provide a user with a reason they should give a correct email, not by performing checks that can be easily circumvented.

Sending an email to the entered address serves only as a way of validation that the user has not made any typos when entering it. When you get a similarly validated email from a third-party service, there is no need to validate it again, since it was done before.

**Comment by tomhughes** [comment]
As far as I know the google auth provider always gives you back the gmail address which is guaranteed to exist. At least that was my assumption when I made it auto-verify.

The key point as I say isn't so much the test (that's mostly to stop you signing up somebody else) but the ability to send a welcome message, for which we only need to be able to send a message right now.

**Comment by Zverik** [comment]
But we don't send a welcome message, only "please click this link to verify" email. The welcome message is displayed after registering regardless of whether a user clicked a link or registered with a pre-verified email.

**Comment by Zverik** [comment]
> As far as I know the google auth provider always gives you back the gmail address which is guaranteed to exist. At least that was my assumption when I made it auto-verify.

Just tried to sign in with Google. It gave my old non-gmail address with which I registered in Google ages ago. It still works, but I doubt google tests its existence after the first time.

And even it's a gmail address that exists, you cannot verify that a user actually uses that email and not some other in other mailing service. I registered in google with my actual address just by chance, I have another google account with a proper gmail address which I check only once every 2-3 years.

**Comment by Zverik** [comment]
Added a test for `mapsme_token` provider. Since it basically mimics the `mapsme` provider, I decided to add just one.

What doubts do you have that prevent merging this request?

**Comment by zerebubuth** [comment]
If we don't currently verify email addresses before activating the account (i.e: allowing edits), then I think we should change the code to do that before adding any new authentication mechanisms. I think it's important that the website supports the community, and that can only happen if user messages and changeset comments actually reach the intended recipient.

As @Zverik points out, we might already be making a false assumption about the value of "guarantees" provided by large, established providers such as Google and Facebook. I think we should check our assumptions thoroughly before going any further.

**Comment by tomhughes** [comment]
We verify for everything except google and facebook.

In the case of google that was because I believed they were only giving us gmail accounts that were implicitly valid by virtue of coming from google. In the case of facebook I think I wasn't really thinking and bought into that claim of facebook having validated them.

Given the evidence presented here I think we should probably stop trusting both.

**Comment by tomhughes** [comment]
Correction, we also trust Yahoo, on the basis as Google, that I assumed they were only giving us Yahoo Mail accounts.

**Comment by iandees** [comment]
All of these providers verify that these emails exist: Facebook won't let you sign up without confirming the email you used to sign up with was valid (by clicking on it). Google will periodically ask if your backup email is valid, but I don't think there's a single provider out there that actively validates the email after initial signup (by periodically sending an email). That seems like an odd requirement.

**Comment by tomhughes** [comment]
Well that's exactly the point - we want the email to be valid at the point when they signup with us so we need to revalidate.

The logic in the case of Google and Yahoo was that there was no way to sign in with them without the mail being valid but we now know that Google don't always provide the gmail address and I know that I can sign in with Yahoo without having a Yahoo Mail address.

**Comment by Zverik** [comment]
What I am trying to say, is that

1) We don't need a working e-mail at the sign-up time. Yes we are checking it, by sending a confirmation letter, but after that a few month or even years can pass before a user receives their first e-mail from osm.org.

2) A belief that e-mail confirmation ensures a e-mail address is working, is not based on anything. It's like these security procedures in airports: they look complex, scary and effective, but when tested, they turn out to be much hassle for regular passengers and transparent for attackers.

For example, I have around 30 accounts on osm.org, most of which I made for teaching or for testing, and while all e-mails from the website are confirmed, I obviously don't check these e-mail accounts.

The only reason for confirmation e-mails is to validate the typed address. When we believe that a user _wants_ to receive e-mails and types his address _by hand_ in the relevant field, we send a confirmation e-mail to verify that they haven't made any typos. It is obviously redundant when we get an address from a third-party service, which has verified it the same way.

So even if you remove the line allowing for google, facebook and yahoo users to not use the confirmation link, you won't get better e-mail addresses or protect yourself from mailinator and similar services. Getting a proper e-mail address from a user is not a techical task, but a designer one. To make a user enter their actual working address, you have to show them the value of messages we will send them. The current registration page does not do that (e.g. we don't even assure that we won't send any spam), so we might get some fake e-mails. Again, the reason is not that we don't send confirmation e-mails for some registrations.

**Comment by tomhughes** [comment]
I'm sorry, but you're just wrong.

It is simply not true that "the only reason for confirmation e-mails is to validate the typed address" because our confirmation e-mail is also a welcome email with helpful links.

Even when we don't do confirmation we still send that email, just without the confirmation link, and we want to be sure they are getting it. The only way to be sure (if we don't trust that the email is valid when the auth provider says it is) is to require them to confirm.

**Comment by tomhughes** [comment]
Hmm actually the confirmation email says we will send the welcome email once they've confirmed, but the effect is the same.

That said I can't actually see where we send it!

**Comment by tomhughes** [comment]
Ah actually we stopped doing that in 2690342b08187db340afd6a6a1f4789f0f9564b7 and the reference in the confirmation email is actually to us redirecting to the welcome page when signup is complete.

I'm not sure that was a good idea though as I think there are lots of ways to signup that will avoid them ever seeing that welcome page..

**Comment by Zverik** [comment]
> ...our confirmation e-mail is also a welcome email with helpful links.

Could you please direct me to the code that sends that e-mail? I have never seen it, even when I tested registration from scratch a week ago.

In some countries users even set their welcoming services like [this one for Belgium](https://welcome.osm.be/), [for Italy](http://welcome.openstreetmap.it/) or [for Russia](http://welcome.osmz.ru/) just to send useful links to new users.

**Comment by Zverik** [comment]
> I'm not sure that was a good idea though as I think there are lots of ways to signup that will avoid them ever seeing that welcome page..

Could you name one please?

**Comment by tomhughes** [comment]
Well to start with probably anything that started as a link to a page that needs authentication and hence had a `referer` parameter attached to specify where to send the user when signup was complete.

**Comment by tomhughes** [comment]
In any case regardless of all that I'm still not really comfortable with the idea that people can signup and be completely uncontactable from the start.

Obviously they can change their email address down the line and it's hard for us to do anything about that, but new mappers are the ones that we are most likely to need to contact anyway.

**Comment by Zverik** [comment]
What I am trying to say, you cannot solve this with technical measures. It is an UI problem.

**Comment by Zverik** [comment]
> Well to start with probably anything that started as a link to a page that needs authentication and hence had a referer parameter attached to specify where to send the user when signup was complete.

Just tested it: the referer is lost after redirecting to the terms page.

**Comment by BushmanK** [comment]
The problem of being able to reach any particular user should be seen (and tested) as a system of real cases. From one, where a user honestly wants to receive all possible feedback, to an opposite, where a user does not want to be "bugged" - he just "wants to fix/add something". All these scenarios are real and there is no corresponding UX study (even very simple one) to back it. I'm insisting on UX, not UI as @Zverik suggests because user's intentions and general behavior should be taken into considerations in addition to his reactions on UI. UI might make it easier to do something, but it can never make someone do it if he doesn't want or wants to do it differently.

The current situation, as @tomhughes just said, is based on a whole bunch of assumptions. Obviously, it creates a ridiculous situation with people, trying to reach other people with a welcoming message, changeset comments or any other matters, actually sending it to nowhere.

**Comment by simonpoole** [comment]
I don't think that the arguments that boil down to "verifying e-mail at sign up isn't perfect so we shouldn't be doing it" hold any water at all. It does give the community a fighting chance to contact new mappers.

Now you could argue that we should allow users to configure additional (social media) communications means, but that is still not going to help with the people that "don't want to be bugged". 

I'll have a look at what happens with the editors a zero-hour block (or any matter of fact) and if that can be improved this weekend.

**Comment by BushmanK** [comment]
That is exactly what I'm pointing at. Currently, purpose and importance of having a valid email of a newly registered user do not seem to be clearly defined. However, it doesn't mean that we don't need it at all or that we need it whatever it takes (like, weekly revalidation).

**Comment by Zverik** [comment]
Okay, I suggest extracting the question about validity of facebook / google emails to a separate issue, since it may require more discussion that is not immediately relevant to this pull request. I'm ready to organize an IRC or Mumble meeting.

In the context of what is already present on the website, adding `mapsme`-provided emails to me are good, since we get these _only_ from facebook and google. And from OSM, when #1431 is merged. Are there any other outstanding issues?

**Comment by zerebubuth** [comment]
> In the context of what is already present on the website, adding mapsme-provided emails to me are good, since we get these only from facebook and google.

If the user already has a Facebook or Google account, can they use that to log in instead? I think we already support both of those.

> And from OSM, when #1431 is merged. Are there any other outstanding issues?

I would be against merging #1431. And, to be honest, against merging this PR as well. I don't understand the need for this as an alternative to the existing providers, and I worry that this is part of an effort to hide OSM rather than welcome new users into the community.

If people want to contribute fixes without being part of the community, then do we need to think about ways to stage anonymous "suggested edits" for community members to verify and "adopt" as their own?

**Comment by Zverik** [comment]
> If the user already has a Facebook or Google account, can they use that to log in instead? I think we already support both of those.

We don't support native sign-in on mobile device — you must remember a big discussion of a year ago, in which I tried to push that into the website. And as I said in [this comment](https://github.com/openstreetmap/openstreetmap-website/pull/1433#issuecomment-278684718), Google will start blocking webview authentication forms in less than two months. MAPS.ME is essentially making a way for mobile apps to authenticate in OSM using native social SDKs.

And please, MAPS.ME doesn't hide OSM. We show a user the complete registration process, every webpage. The name of the project is prominently displayed on each page. We mention OpenStreetMap in all our PR materials. We have links to OpenStreetMap on profile and about pages.

As for the community, I think that is the myth that became obsolete around 2012. We don't have a single community anymore, like e.g. Facebook does not have a community of facebook users. What matters is mappers answering e-mails, and this is a step in that direction.

**Comment by zerebubuth** [comment]
> Google will start blocking webview authentication forms in less than two months.

The fix that [Google suggest](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html) is to use "in-app tabs" instead:

> Modern “in-app browser tab” patterns available on some operating systems, such as Chrome Custom Tabs on Android and SFSafariViewController on iOS offer further UX improvements for browser-based OAuth flows.

The blog post goes on to say how "in-app tabs" are also an improvement for security. Would Google's suggestion be an easier (and possibly more secure) upgrade path for anyone currently doing OAuth in a WebView?

> As for the community, I think that is the myth that became obsolete around 2012. We don't have a single community anymore, like e.g. Facebook does not have a community of facebook users.

I wasn't suggesting that there is a single community. I was suggesting that we might look for alternative routes for people to contribute if they're not interested in becoming part of the wider OSM community or communities.

I think that it's important that we're able to audit the data in OSM, and contact members to ask whether they need help, start discussions about how to map things, or check what their original sources were.

> What matters is mappers answering e-mails, and this is a step in that direction.

Please could you explain how this PR helps? At the moment, I can't see how it adds anything we don't already have in our Google and Facebook integrations.

**Comment by simonpoole** [comment]
I don't see anything in https://www.theregister.co.uk/2016/08/23/google_to_block_web_views_from_using_its_oauth/ indicating that an OSM based app won't be able to use a webview for the the user to authorize a OAuth request on osm.org.

**Comment by Zverik** [comment]
> I don't see anything in [theregister article] indicating that an app accessing the OSM API won't be able to use a webview for the the user to authorize a OAuth request on osm.org.

This concerns only the Google authorization. You can log in or sign up to OSM with a Google profile, instead of typing a password.

> The blog post goes on to say how "in-app tabs" are also an improvement for security. Would Google's suggestion be an easier (and possibly more secure) upgrade path for anyone currently doing OAuth in a WebView?

The easiest solution would be not to use these in-app tabs (suppored only on Android 4.1+, while even maps.me supports 4.0.3+), but to use the Google Native SDK. Unfortunately, with OSM that is not an option now. With maps.me authentication it will be.

> >  What matters is mappers answering e-mails, and this is a step in that direction.
>
>Please could you explain how this PR helps? At the moment, I can't see how it adds anything we don't already have in our Google and Facebook integrations.

Our Google and Facebook integrations do not allow seamless login with mobile devices. Users have to retype their passwords — and I don't even know mine. As for the user feedback, this PR will help us better integrate the new profiles into the maps.me mapping experience, and I hope that later OSM would have better notifications API, and maps.me profiles will have these notifications prominently displayed.

**Comment by Zverik** [comment]
It's been almost a week, are there any further questions?

**Comment by zerebubuth** [comment]
I still think that the case hasn't been made for adding this extra authentication type. As I explained before, there's no technical need for it, given that we have working Google and Facebook methods. Google themselves recommend a method using "in-app tabs" which doesn't require any server-side changes.

I would support a proposal to simplify sign-up procedure which didn't obscure OSM, or wasn't tied to a particular mobile app. Especially if it can be done without leaking private information (e.g: email addresses) to whoever is running the mobile app.

**Comment by Zverik** [comment]
> I still think that the case hasn't been made for adding this extra authentication type. As I explained before, there's no technical need for it, given that we have working Google and Facebook methods. Google themselves recommend a method using "in-app tabs" which doesn't require any server-side changes.

Why should there be a case made for adding an extra authentication type? We added wikimedia recently without any technical need for it. I doubt there is one OSM member with wikimedia account and without an account on any other social services we had supported before.

Even if maps.me authentication type gave nothing new to OSM, this is still not a good reason to reject the pull request. It breaks nothing in OSM, and it allows more users to sign in with their preferred method.

I already explained why maps.me cannot use in-app tabs. They require a newer version of android than we support. Vespucci editor, for example, supports "all Android versions since 2.2" — not with in-app tabs, then require 4.1. And I doubt that browser-based authorization will have login and password pre-filled from the system auth module. Native authentication would be the best option for any mobile editor.

> I would support a proposal to simplify sign-up procedure which didn't obscure OSM, or wasn't tied to a particular mobile app. Especially if it can be done without leaking private information (e.g: email addresses) to whoever is running the mobile app.

Nope, when I tried to push exactly that, nobody in osmf working groups supported it. I've got a couple of "how can I help" calls from commercial companies, but in osmf it was all talk and maybes. You must remember all these emails a year ago.

**Comment by pnorman** [comment]
I had this typed out last night but forgot to hit post

-----

> What I forgot to mention is that e-mail addresses from passport.maps.me are considered verified

After reviewing the discussion here, 👎 to this, and we probably need to review what we're doing for other providers. I'd be comfortable skipping verification for Google for gmail emails because Google is the email provider there. In a case like this, or Google with a non-gmail email, I'm not comfortable with it and think we need to verify.

Most of the discussion so far has been about emails, but we need to be sure that we're satisfied that adding them is a good idea. In particular, we should check that

- [ ] we want to add them as a provider
- [ ] the alternate authorization workflow with the access token is sane
- [ ] their usage policy allows us to use them as an an authentication service

What else needs deciding?

I think this would be the first authentication service that is not a general-purpose identity provider.

**Comment by Zverik** [comment]
> 👎 to [verified emails]

If `mapsme` provider uses emails provided by only verified providers or verifies emails itself, why 👎?

>  their usage policy allows us to use them as an an authentication service

They don't have any usage policy in place now, but if needed, they can put there something in line of "this service can be used for authenticating in OpenStreetMap".

> not a general-purpose identity provider

Could you explain this bit? Anyone can register in the service. At the moment oauth client registration is manual, but so is in wikimedia.

**Comment by Zverik** [comment]
Okay, once again: this pull request differs from the previous provider-related in two ways:

* **All emails are considered verified.** Because the provider takes email addresses only from providers that give verified emails wrt OSM, that is, from Facebook and Google. I suggest postponing the discussion about this flag for a later time (maybe in person or in skype/mumble), because that has nothing to do with the maps.me provider, site security or authentication.
* **An access token authentication.** A GUI overpass for mobile devices: spares a request from the backend, providing a ready-made token instead. Does not alter the workflow for the website, just skips the maps.me website display.

Looking at previous pull requests for Wikimedia, Facebook, MS Live, I see only discussions on "how", not "why". The maps.me passport service will have millions of users in a year, so I don't see why we should not allow them for a simpler sign-in.

**Comment by pnorman** [comment]
> > not a general-purpose identity provider

> Could you explain this bit? Anyone can register in the service. At the moment oauth client registration is manual, but so is in wikimedia.

All the current third party authentication providers are ones which **currently** a potential user has a reasonable chance of having an account, either because they're large providers of authentication services, or, in the case of Wikipedia, a smaller one which is in a related field. You've talked about the users maps.me passports **will have**, not what they currently have.

Is there a reason why you're not opting to offer OpenID, which is already supported by many sites, including osm.org?

**Comment by Zverik** [comment]
> Is there a reason why you're not opting to offer OpenID, which is already supported by many sites, including osm.org?

I guess we could, but I doubt it would be useful. Since for the mobile sign-in we need a token to present to the website, so it can ask for user details from maps.me, and OpenID doesn't do tokens. Most, if not all, popular websites have abandoned their OpenID services, so I'm not sure anybody should set up one.

**Comment by Zverik** [comment]
I see this has stalled again. I'd like to see it discussed and resolved faster.

I understand that the sole word "MAPS.ME" in the title makes some people look into every symbol and search for any reason to reject it or reduce to something non-functional. We are not a trusting community, and seeing that a lot of mappers and developers do not trust even the OSMF Board, it's normal that even less people trust MAPS.ME. Even if I represent it, all of my experience in OSM showing that I care for its growth, usability and security.

Also it is obvious that only Tom makes decisions for merging anything into the website code. Replying to other people makes this whole thing harder for him to understand and decide on. While trying to make this change clearer, I actually make it harder to understand because of number of words.

Tom and anyone interested, could we please discuss this matter in any other channel, that does not make participants wait for weeks for an answer? Mumble or even IRC?

**Comment by Zverik** [comment]
After a brief discussion with Mikel, I decided to postpone the automatic email validation to a later pull request. I assume this addresses all major discussion points in this thread. Anything else I can do to make it merged?

**Comment by Firefishy** [comment]
It would be good to get feedback from someone additional voices @mikelmaron @gravitystorm @iandees @lonvia @systemed 

@Zverik maybe you can walk us briefly through 1) what the end user flow would be and 2) what would happen if another mapper tried to contact mapper from 1.

**Comment by Zverik** [comment]
Thanks Grant for updating this. The pull request simply adds an authentication method, it is not much different from facebook or wikimedia or github. For the OSM, the user flow would be exactly the same as before. The website would get an e-mail from the maps.me service and start the sign in or sign up process as usual. No pages would be skipped.

For the token authentication (that is new), only the login page is skipped: the user flow starts directly with the registration page (if they are new) or with the permissions granting page. Technically it means that the user starts with the `/auth/callback` page, where every other OAuth service redirects after the user has logged in there.

**Comment by tomhughes** [comment]
There is (to my mind) a key difference though - this is not an existing authentication provider that has set itself up as a general service and we have then chosen to offer to our users, rather it is an authentication provider that has been created specifically for the purpose of interacting with OpenStreetMap.

So the question is, if we accept this, are we then expected to do the same for every other mobile app that chooses to follow the same path? Where would that end?

That is the policy question that needs to be determined before we can consider technical questions, and that is the question which is out of scope for me to make as the main committer.

**Comment by Zverik** [comment]
> There is (to my mind) a key difference though - this is not an existing authentication provider that has set itself up as a general service and we have then chosen to offer to our users, rather it is an authentication provider that has been created specifically for the purpose of interacting with OpenStreetMap.

Actually, it is created for the purpose of better communicating with maps.me users. It will be included in maps.me soon, regardless of the state of this PR. And most our users, at least ten million (as we expect) will be registered there. If there is another application with millions of users, then why not add their service too (or connect them to ours).

The authentication endpoint in this request is created not because we want to route editors through our service, but because we want to minimize the hassle with two registrations, which means, to increase the number of people registering in OSM and editing it through our app.

**Comment by simonpoole** [comment]
> but because we want to minimize the hassle with two registrations, which means, to increase the number of people registering in OSM and editing it through our app.

That doesn't really seem to compute. -You- are adding an additional registration, and are generating the additional hassle. If you want to provide some additional services to registered maps.me users, simply ask them to sign up with OSM and use OAuth to authenticate them. Problem vanishes in a puff of smoke. :-)

**Comment by Zverik** [comment]
> So the question is, if we accept this, are we then expected to do the same for every other mobile app that chooses to follow the same path? Where would that end?

We do not have a precedent law here, each provider is decided on separately. And I assume, next time there will be a similar discussion. I'd be happy to see another OSM-based app with millions of users making pull requests to the website.

Now really, what it blocking this pull request? I removed the only non-technical blocking feature, I have tested the branch, this PR does not worsen the website or change any of the workflows. The service will be up next month, and we'd like to make the whole transition to the new sign-in process. How can I help with reviewing this? Is there something I can do?

**Comment by lonvia** [comment]
> Now really, what it blocking this pull request?

This issue is blocked because it requires a policy decision about who we should accept for OSM as an auth provider. This is not a technical issue but concerns the OSM project as a whole, so this issue tracker is the wrong place to discuss that. These policy decisions fall into the responsibility domain of the OWG. So I would recommend that you get in touch with OWG and ask them to start the process for a new policy for auth providers. You could also ask for special permission for this PR to be merged but a written policy would be more future proof and also put you as a provider in a better position as it would give you clear guidance about your rights and responsibilities.

**Comment by nomoregrapes** [comment]
I don't normally look at these pull requests, but I was invited here by [email](https://docs.google.com/document/d/1QUN3NaO6n1WU4mBa8pq2lyh5ga79UpJGSxAlzJGf2mQ/edit) (sent to an unknown number of people).

* I see nothing wrong with this pull request generally.
* It would be great to see a policy on what providers are given as OSM login options.
** Maybe differing policies for if they're OSM/map-related orgs(e.g. Maps.me) or not (e.g. Google, Wikimedia)
* I do not think a vote is acceptable for a technical pull request, especially one with such leading language on the options. I.e. the option "Not sure. I think OSM community can survive without millions of POI mappers." should be "Not sure."

I hope this discussion gets suitable attention so that it is easier to decide this pull request and future ones.

**Comment by simonpoole** [comment]
@nomoregrapes the good thing about the mail is that it makes the many times obfuscated actual goals of which this pull request clear again, and the answer can simply only be: no.

**Comment by vshcherb** [comment]
Hi All, 
I was also brought here by email. I feel a bit confused after I read description and looked at the pull-request. It was mentioning to let people login with their Facebook/Google account, though the changes are done for Maps.me account. It looks quite different than other providers, for other providers you can register on website and other providers exist for other services than OSM.  One of the main difference that people use OAuth to register on OSM website itself and here they will register only in Maps.me and will stay there.
Technically, it already happens, so having an extra OAuth provider should not impact at all, the only main concern whether you could trust this provider i.e. you can reach a real person (communicate with him).

I couldn't say if it's bad or good, it is different.

**Comment by simonpoole** [comment]
As a follow up to my previous comment, I just wanted to point to: https://www.mapillary.com/signup which allows you to sign up with your OSM login.

**Comment by mikelmaron** [comment]
> This issue is blocked because it requires a policy decision about who we should accept for OSM as an auth provider. This is not a technical issue but concerns the OSM project as a whole, so this issue tracker is the wrong place to discuss that. These policy decisions fall into the responsibility domain of the OWG.

Agreed @lonvia, this is a policy issue. In general, the (not very well documented) pattern for policy and guidance in the OSMF is that an issue is raised and discussed within membership, a working group, or elsewhere; is brought to the attention of the Board; Board decides on a policy process, usually driven by or in consultation with one or more working groups; Board votes to approve the policy or guideline. Naturally Conflict of Interest rules would apply as part of any formal decisions.

**Comment by mikelmaron** [comment]
In any case, no need to continue the policy (or meta-policy) discussion here, we can take that to the proper venues, and return here when that's resolved.

**Comment by Zverik** [comment]
I have made a [draft policy](https://github.com/openstreetmap/operations/issues/162) for new OAuth providers, please read it and leave a comment there.

**Comment by Zverik** [comment]
By the way, maps.me users now cannot login to OSM with Google on iOS devices: https://github.com/mapsme/omim/issues/6140
Suggested `SFSafariViewController` requires iOS 9+, and we target iOS 8+.
As far as I could find, no other OSM-related app (which cares for old devices) uses google sign-in on iOS.

**Comment by gravitystorm** [comment]
First I appreciate that a lot of work went into this pull request, both in writing the omni-auth plugin, and also in all the discussions here.

I'm also aware that OSMF/OWG having an "[identity provider policy](https://github.com/openstreetmap/operations/issues/162)" was identified as a way forward, and Ilya again worked on that, but that issue still remains unresolved.

In the meantime, this PR has bit-rotted, and now no longer merges, and needs to be reworked to move from fixtures to factories. However, if anyone is interested in resurrecting this task in the form of a new PR, I would strongly suggest that agreement is first reached on the principle of adding maps.me as an identity provider, before proposing the new code to implement it.

**Pull request closed without merging**
