### PR TITLE
Turn wikimedia_commons values into links

### PR DESCRIPTION
**Pull request by mstock**
This turns the value of the `wikimedia_commons` tag into a link to the respective page on `commons.wikimedia.org` (if it is a `File:` or `Category:` item) by enhancing the browse helper. See [1] for the tag description.

(Btw.: I have no hard feelings if this is rejected - I recently noticed this tag (which is not that popular yet, but the wiki page [1] is also fairly new), found it useful (since it seems to solve some of the issues of the `image` tag if images are available on Wikimedia Commons), and wanted to see how easy/hard it is to implement such a link.)

[1] http://wiki.openstreetmap.org/wiki/Key:wikimedia_commons

### CODE REVIEW

**Comment by matkoniecz** [comment]
Is there any chance for a review? I thought about implementing #2184 but I worry that it would end as PR waiting for years without a review.

**Comment by mstock** [comment]
I just rebased this old branch on the current `master` branch, it still seemed to work during a quick test, and this time, Travis and Coveralls also seem to be happy with it.

**Comment by pyrog** [comment]
Few items to check when your PR will be  merged:

* ` wikimedia_commons="Category:*"`
  *  node [2663278344](https://www.openstreetmap.org/node/2663278344)
  * way [129550864](https://www.openstreetmap.org/way/129550864)
  * relation [9104518](https://www.openstreetmap.org/relation/9104518)
* ` wikimedia_commons="File:*"`
  *  node [5073751343](https://www.openstreetmap.org/node/5073751343),
  * way [567537182](https://www.openstreetmap.org/way/567537182)
  *  relation [177044](https://www.openstreetmap.org/relation/177044)

**Comment by mstock** [comment]
Great, thanks for merging :)!

**Pull request merged**
