### PR TITLE
Revised road key and icons for data browser

### PR DESCRIPTION
**Pull request by AndrewHain**
These are a set of key entries and icons matching the new colours at gravitystorm/openstreetmap-carto#1736. The present entries for trunk, primary and secondary roads are replaced by one for main road (a new string that needs translating). The tertiary icon is wider to compensate for the pale colour.

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
The carto osm change is not live on the tile servers, as no release with this change had been tagged. 
So this PR should be merged not before the release on tile servers. 
Good that we have a adapted legend already for this big change!

**Comment by tomhughes** [comment]
So this is a rather more drastic change than I was expecting... I assumed it was just updating the colours, but it actually merges all the trunk/primary/secondary roads into one which I'm not sure is a good idea and on top that it means that key entry will look very different to all the others because it will have three samples beside it not one.

**Comment by tomhughes** [comment]
I've put a live site up at http://tomh.apis.dev.openstreetmap.org/ with this applied, if people could have a look and see what they think?

**Comment by SomeoneElseOSM** [comment]
Roads under construction in http://tomh.apis.dev.openstreetmap.org/ use the old colours?

**Comment by matkoniecz** [comment]
@SomeoneElseOSM 

Most likely it is result of rerender in progress - parts of map are displayed in new style, parts in the old.

**Comment by matkoniecz** [comment]
I am not sure is it intentional or not but road on map and road in legend are different - for example highway=secondary in legend has the same casing width as other roads but on map it is a bit smaller.

And for example secondary casing is #707d05 or 9eae23 (depending on zoom level) - it never is #AFBB62

> merges all the trunk/primary/secondary roads into one

It makes legend less consistent. But it may be the first steep to make legend shorter, hopefully it will be anyway obvious what kind of road is more important. And it makes translation easier (for example trunk roads have no equivalent meaning in Polish)

> Roads under construction in http://tomh.apis.dev.openstreetmap.org/ use the old colours?

Oh, right - it is about legend, where roads under construction are not changed to the new style.

**Comment by AndrewHain** [comment]
I have updated the image for construction and made the bottom roads the same width as the top two for main roads and under construction.

**Comment by polarbearing** [comment]
The roads from tertiary downwards are missing in the legend, and they were missing in the old-colour legend already.

**Comment by AndrewHain** [comment]
It is awkward to put tertiary in the key now that the main difference is width.

**Comment by polarbearing** [comment]
It's equally weird to leave the legend user guess what the slight grey road means. It might work to show the relative width difference. 

Some printed map have two symbols per legend line explained, maybe that might work for us as well, which also makes the legend shorter.

**Comment by HolgerJeromin** [comment]
Perhaps it is a good idea to merge this now for a start. The legend is needed perhaps now the most.

**Comment by tomhughes** [comment]
Merged as f9570c4f054411c92007a146683f9f4724c1f9db.

**Pull request closed without merging**
