### PR TITLE
using sprite.svg for high dpi devices

### PR DESCRIPTION
**Pull request by HolgerJeromin**
With this change the sprite.svg will be used for the icons.

btw the Chrome debugger can simulate hi dpi devices. :)

partial fix for #850

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
If SVGO changed to much for you, we could use another SVG minifier. But the bogus `filter:url` has to be eliminated from the file.

**Comment by HolgerJeromin** [comment]
Or we could use [this logic](http://www.sitepoint.com/a-farewell-to-css3-gradients/) without `@media` query:
```
.icon {
    background:url("sprite.svg"), url("sprite.png") ;
 }
```
Note: background instead of background-image is intentional.

But old safaris will probably not working: http://caniuse.com/#feat=svg-css thats why i used the `@media` way to hide the new stuff.

**Comment by tomhughes** [comment]
Isn't IE8 the bigger issue? It's only Safari 4 and older that don't do it by my reading?

To be honest I'm more curious about how the `background-position` works to select the right bit of the sprite when we're using an SVG image that doesn't have pixels as such!

**Comment by HolgerJeromin** [comment]
The first line `<svg xmlns="http://www.w3.org/2000/svg" width="300" height="200">` has the same quality of dimension as a png.
IE<9 should ignore the background with the two entries, or NOT choose the svg. Both is good.

yes, safari <=4. But caniuse says that has 0.2% usage... Perhaps piwik can help.

**Comment by tomhughes** [comment]
Yesterday we had 20 visits from Safari 4.1, 10 from Safari 4.0 and 1 each from Safari 3.1 and Safari 1.0 (if you believe that...) each of which is rounding to 0%.

**Comment by tomhughes** [comment]
@HolgerJeromin your alternate is not actually right - that loads the PNG with the SVG overlaid on top of it (the web page you reference is using it to overlay a gradient on a different image).

I think we actually just want a second background that specifies the SVG and that old IEs will hopefully ignore?

BTW you say it's deliberately `background` not `background-image` but you don't say why?

**Comment by HolgerJeromin** [comment]
Oh, yes. You are right with the multiple backgrounds. Thanks for pointing that out.

The linked blog states:
> Note I’m using the shorthand ‘background’ CSS property rather than ‘background-image’ as older IE’s seem to try to read multiple images as one long image when you use the more specific notation. 

I think with this logic we have no standard conform possibility to prevent old browsers from seeing the svg.
Except the hackish way:
`@media (-webkit-min-device-pixel-ratio: 1), (min-resolution: 10dpi){`
If a browser is new enough to recognize these new media querys they will render svg background without an error. But again Safari v4 knows min-device-pixel but is buggy with background-position. 

I would have no problem in dropping the twenty safari v4 user for a cosmetic thing. But this sprite contains the main interaction stuff. 
So IMO we have to reserve the SVG to the HiDPI devices.

**Comment by tomhughes** [comment]
I've put a test site up at http://tomh.apis.dev.openstreetmap.org/ if people could try it in older browsers especially and let us know if the icons work...

**Comment by tomhughes** [comment]
So I've tried it with IE8 and that seems to ignore the second `background-image` that specifies SVG and just use the PNG from the first `background` rule.

**Comment by tomhughes** [comment]
I've pushed a0aa5a174150f3d517fadfc732d3d54a3b028274 and 0d0498d303f36749cd48d8e6eadb1abafe3f828c now and I'm going to put that live and see if we get any complaints ;-)

**Pull request closed without merging**
