### PR TITLE
Add dark theme for OSM site and ID editor, depending on color theme 

### PR DESCRIPTION
**Pull request by bezdna**
image

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
109 values with `!important` feels very wrong.

**Comment by mmd-osm** [comment]
You probably want to do this via bootstrap, rather than uploading some CSS file than has been tweaked via userstyles.org.

**Comment by mmd-osm** [comment]
_dark_theme.scss will be basically unmaintainable. You should probably look into how this can be achieved via bootstrap instead.

**Comment by bezdna** [comment]
@HolgerJeromin if you know rules cascade,  you not say about this problem.
Because inline styles have highest specificity, and to implement other rules, need use important
button.bar-button.save[style="background: rgb(255, 255, 253);"] {
    background: #333332 !important;
 }

You can read more here https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by bezdna** [comment]
@mmd-osm this file change only colores, and this feather work if user set in system or in browser dark mode. I think it better if user waiting dark mode in site he get it.

**Comment by mmd-osm** [comment]
I’m thinking more about projects like https://github.com/ForEvolve/bootstrap-dark

Any additional line of css to support dark mode feels like unneeded extra effort.

**Comment by HolgerJeromin** [comment]
>  if you know rules cascade, you not say about this problem.

I know CSS pretty well. 
If this feature (which I really like) needs 109 hacks it is probably the wrong approach.

I know you got the code from userstyles, but they have no other ways to solve this problem. 
But here we should solve it maintainable.

**Comment by bezdna** [comment]
If take a closer look, you see that this project use all css style from original bootstrap, only use others colours. I suggest use extra css that change only colours.

OSM website not very flexible product, and not lot of changes in UI.  And i think not need a lot of time, to support dark mode.

**Comment by gravitystorm** [comment]
Thanks for the PR, but I'm going to decline this approach. This approach, of having lots of overrides and !important flags and so on is fine when a user style is the only available option. But that's not a good approach when we have full control over the CSS sent to the user.

Also, 1630 lines of CSS is not something I want to maintain. To implement a dark mode, I would ideally like to see out-of-the-box support from bootstrap itself. If that's not available, then maybe 10-20 lines of code to set some colour variables, but little more than that. Anything more complex will be too much to maintain for a low-priority feature like this.

**Pull request closed without merging**
