### PR TITLE
Remove whitespace on signup fields #4471

### PR DESCRIPTION
**Pull request by birante**

### CODE REVIEW

**Review by gravitystorm — CHANGES_REQUESTED** [review]
Hi @birante , thank you for this pull request.

First, I think there is a misunderstanding about the problem described in #4501. The issue described is for the login page (not the signup page), and it is for the situation where someone accidentally includes leading/trailing whitespace when trying to sign in.

Secondly, a PR to fix this issue will need tests, to prove that it works, and to prevent any future breakage if we ever refactor the code.

Finally, I would be interested to see if there is a rubygem that is already written to tackle this problem, so that we can easily apply the same solution to other forms on the website. For example, we could use something like https://github.com/holli/auto_strip_attributes

**Comment by tomhughes** [comment]
I don't think a gem that auto strips the model attributes is going to help here because the login code is not actually building a model at all - if it was the model would fail validation because we already have validations for this.

The problem basically is https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/sessions_controller.rb#L50 which creates (or rather looks up) the model using the provided username and password.

**Comment by gravitystorm** [comment]
> I don't think a gem that auto strips the model attributes is going to help here because the login code is not actually building a model at all

Good point.

**Comment by birante** [comment]
hello @tomhughes  @gravitystorm  thanks a lot for the feedback and sorry for the misunderstanding about the issue.

I will fix it write the test and push back.

Best.

**Pull request closed without merging**
