### PR TITLE
add öpnvkarte key/legend

### PR DESCRIPTION
**Pull request by swedneck**
this could use some more detail work to fill in missing zoom levels as well as road types, but it's most of the way finished.

### CODE REVIEW

**Comment by tomhughes** [comment]
This causes a test failure:

```
Error:
SiteControllerTest#test_key:
ActionView::Template::Error: translation missing: en.site.key.table.entry.water
    app/views/site/key.html.erb:10
    app/views/site/key.html.erb:4:in `each'
    app/views/site/key.html.erb:4
    app/views/site/key.html.erb:3:in `each'
    app/views/site/key.html.erb:3
    app/controllers/site_controller.rb:50:in `key'
    config/initializers/compressed_requests.rb:27:in `call'
    config/initializers/cors.rb:9:in `call'
    test/controllers/site_controller_test.rb:169:in `test_key'
```

**Comment by swedneck** [comment]
that commit should fix the errors, i noticed that spaces need to be replaced with underscores, as well as a spelling error on light rail.

**Comment by tomhughes** [comment]
No there's no need to add underscores to the image names - so long as the name of the name matched what you list in the configuration file you can use any name you like.

What you do need (and still don't have) is entries in the strings table (https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml#L2079) that match the names in your configuration file.

**Comment by swedneck** [comment]
oh i see how this works, thanks!

**Review by Mint-6263 — COMMENTED** [review]
Ok

**Comment by matkoniecz** [comment]
Is there a chance for review of that PR by maintainers?

**Comment by matkoniecz** [comment]
@swedneck Are you planning to continue working on this?

**Comment by swedneck** [comment]
@matkoniecz i don't think so, unfortunately

**Comment by pnorman** [comment]
Can we close this as abandoned?

**Pull request closed without merging**
