### PR TITLE
Add 404.png used by sites using old OpenLayers example

### PR DESCRIPTION
**Pull request by Firefishy**
Add a message in the old OpenLayer 404.png

### CODE REVIEW

**Comment by Firefishy** [comment]
We respond with around 8 million 410 - GONE responses for this 404.png tiles a day. Having the file available and responding with cache headers will hopefully reduce the number of requests.

**Comment by tomhughes** [comment]
The requests don't really cost anything, and this certainly doesn't belong here - it's an operational issue for osm.org not an issue for this repo.

**Comment by Firefishy** [comment]
8 million requests a day / 100 requests a second (>32 million fd stats and >16 million fs reads) does cost and is not insignificant. We already have legacy OpenLayers files in this repo, adding 1 static file will mostly get rid of the OpenLayers DDOS failure request loop that has been hitting us for years.

Would you prefer the 404.png file was dropped by chef?

**Comment by Firefishy** [comment]
~2.8GB of access.log logs per day just to store the 410 request responses.

**Comment by Firefishy** [comment]
This PR is now made redundant by updated to https://github.com/openstreetmap/chef/pull/325

**Pull request closed without merging**
