### PR TITLE
Holiday Apartment is more specific for tourism=apartment

### PR DESCRIPTION
**Pull request by polarbearing**
Holiday Apartment is more specific for tourism=apartment

### CODE REVIEW

**Comment by pnorman** [comment]
Anything that needs to be done to merge this? It seems like a better description and agrees with the wording on the wiki.

**Comment by gravitystorm** [comment]
Yep, looks good to me.

**Comment by tomhughes** [comment]
Doesn't all that text come from Nominatim, so it will just get reverted the next time @lonvia resyncs it?

**Comment by gravitystorm** [comment]
I didn't realise that there was anything in en.yml that came from elsewhere! Sorry about that. I guess it'll show up as a holiday apartment in the meantime, and we can figure out how to get this upstream then. I'll open an issue.

**Comment by tomhughes** [comment]
Last resync was #1724 a year ago so we're probably due a new one - not sure what the exact source is upstream though.

**Comment by lonvia** [comment]
I do update the list manually from time to time to reflect the actual tag usage in the Nominatim database. So if you add or remove lines then that might get reverted. But I don't change the descriptive text. Corrections are welcome.

**Pull request merged**
