### PR TITLE
Return an error when a disabled authentication mechanism is used

### PR DESCRIPTION
**Pull request by tomhughes**
This extends the previous work to allow authentication basic auth and OAuth 1 to be disabled to return an error message so that users have some chance of discovering what is going on.

I'll make this a draft for now as we may want to add more detail to the messages...

### CODE REVIEW

**Comment by mmd-osm** [comment]
Could this be implemented as Apache rewrite rule, to also cover CGImap without much extra effort?

**Comment by mmd-osm** [comment]
Assuming we set `basic_auth_support: false`, an API user would see one of these two error messages:

* HTTP 403 HTTP Basic Authentication is disabled 
* HTTP 403 Couldn't authenticate you

I'm wondering if this makes much of a difference for a user, when they can't use Basic auth anyway and need to switch to OAuth 2. Tbh, I'm struggling a bit to see the benefit of checking whether the credentials are valid.

**Comment by tomhughes** [comment]
To minimise the difference from normal behaviour, and hence the risk of breaking things in unexpected ways?

**Comment by tomhughes** [comment]
I've added a link to a stub wiki page in the error message so we have a way to provide extra information and cleared the draft flag as this is now ready for review.

Operationally to deal with the cgimap issues we could force anything with a basic auth header into rails instead of cgimap during the brownouts so they get the better error but that's hard for OAuth 1 as there are multiple ways of providing the signature I think and some may not be visible to apache, notably if they are in POST parameters.

**Comment by mmd-osm** [comment]
> Operationally to deal with the cgimap issues we could force anything with a basic auth header into rails instead of cgimap during the brownouts so they get the better error

I'm not sure this is really needed. Let's take a look at the different scenarios.

Out of the four endpoints to do changes on the database, only the changeset upload is handled by CGImap. As soon as there are no open changesets left anymore, they're stuck with the changeset create on Rails. The error message on Rails would suffice in this case.

The user based rate limiting for various fetch element endpoints is implemented on CGImap only. I suppose if we're diverting these calls to Rails, it would not trigger an error there.

If we want to make users aware that their rate limiting isn't working anymore, this would have to be done on Apache or CGImap then?

**Comment by tomhughes** [comment]
Can I give this a bump, given we're supposed to be doing brownouts like now, and disabling the old auth methods at the end of the month?

**Comment by gravitystorm** [comment]
OK, this looks fine to me. 

I had to do some reading as to the differences between OAuth 1.0 vs 1.0a, and also (re-)learning about how the rails filter chains work since it wasn't initially obvious to me that rendering in the filter was enough to stop the rest of the action from running too.

It's a little complex to understand how the `Settings.oauth_10_support` and `Settings.oauth_10a_support` interact, since the second also affects oauth 1.0 tokens, but hopefully we can clean this up soon. In reality, OAuth 1.0 is already turned off anyway.

With regards to Basic Auth, we'll need to do some work to remove usage of basic_auth in our tests in the near future.

**Pull request merged**
