### PR TITLE
Routing

### PR DESCRIPTION
**Pull request by systemed**
This is a basic routing interface for osm.org implemented in JavaScript. Routing is provided by external services (in this commit, OSRM, GraphHopper, and MapQuest Open).

The initial aim is to provide A-B routing functionality with a coherent UI. There is much more that could be implemented, of course, but the focus has been on the simplest possible service for now.

There are two obvious omissions:

- Routes do not have permalinks and the URL history is never changed.
- Directions are not translated.

Both of these are some way outside my knowledge / comfort zone and I suspect others would be more efficient at coding them! Translation is expected to be done by the external service, so should be largely a matter of the routing engine passing the current locale.

Otherwise this should largely be ready. Comments/suggestions *within the existing scope* welcome: "wouldn't it be nice if it did this..." requests are probably best left for after an initial launch.

Thanks hugely to @apmon, @danstowell and @karussell for patches and suggestions so far.

### CODE REVIEW

**Comment by danstowell** [comment]
Happy new year, @systemed @tomhughes and all! I found a small issue in the version currently running at http://jsrouting.apis.dev.openstreetmap.org/directions :

* Look up a route by any means (I typed "London" and "Manchester" then Enter)
* The route appears, all lovely and great :)
* But look, there's a "Close" box in the left-hand panel. Click it.

Expected behaviour: well, I guessed that the close-box would dismiss the route, or dismiss the whole panel. Not sure.

Actual behaviour: the directions panel doesn't close, it just sorta refreshes itself. (Tested on firefox 35 and chromium 39.)

I don't mind if the close-box is supposed to be there, or if it should just be removed, but at present it's a broken widget.

**Comment by pnorman** [comment]
@tomhughes what can be done to help move this along?

**Comment by zerebubuth** [comment]
I'll take a look at the "close-box" issue that @danstowell reported and see if I can't fix that tomorrow. And merge master back in. I don't know if there are any other issues waiting to be addressed.

**Comment by tomhughes** [comment]
@zerebubuth Looks like @danstowell already opened https://github.com/systemed/openstreetmap-website/pull/27 with a fix

**Comment by systemed** [comment]
It makes sense to me so I've merged it; @zerebubuth, shout if you disagree.

**Comment by tomhughes** [comment]
So I've spent a few minutes playing with the test site and I gave a few UI suggestions:

* When you open the routing panel the from and to boxes have whatever input they had last time it was used. I would suggest that from should start with whatever value is in the main search box (so if I enter something and hit the route button that transfers to the routiing input) and the to box should start empty each time the panel is opened.
* The spinner that appears when calculating a route is small and appears in the top panel in a way that causes it to expand and then contract again when the calculation finishes. My suggestion would that it should move into the result pain and use the same large one that query mode uses - when starting a route calculation clear the results panel and display the large spinner there, then replace it when the route is ready.
* The dropdown for choosing the engine is (at least in Firefox) unbalanced - the text has more space below than above. Suspect this is a result of forcing the size of the drop down to match the text boxes? Other places (like GPX trace edit) have thinner drop downs that are probably just the natural size but another option would be to equalize the top/bottom margin if that is possible.
* Is the "Go" button supposed to be alongside the drop down? Only on my firefox at least it is on the line below...
* Possibly irrelevant once if first point is fixed but when reopening the panel the route line reappears on the map but the end point markers don't.

**Comment by danstowell** [comment]
@zerebubuth @tomhughes no I didn't fix the issue I raised, actually! I fixed a different one. I didn't fix the [issue I raised here](https://github.com/openstreetmap/openstreetmap-website/pull/716#issuecomment-71314507) since I wasn't sure what would be best to do - remove that extra "x" (next to Directions" or make it do something sane?

**Comment by zerebubuth** [comment]
I've submitted a PR [here](https://github.com/systemed/openstreetmap-website/pull/28) to address some of these issues. The remaining ones:

> Is the "Go" button supposed to be alongside the drop down?

Yes, that appears to be the intention.

> When reopening the panel the route line reappears on the map but the end point markers don't.

I'm still trying to figure out how those parameters get into the URI. Will continue to look into it.

**Comment by tomhughes** [comment]
The GO button is on the next line because it's a separate div. That div probably needs removing and the drop and button putting in a single `div class=line` (not that I like a class with a name that generic...) or something. The align=right on that and other stuff should be CSS as well.

**Comment by danstowell** [comment]
Re the GO button: a quick HTML hack shows me that simply removing that `div` wrapper almost works, except that I also had to edit the CSS for `input[type="submit"]`and decrease min-width from 120px to 80px. Then, they sit nicely on a line together with no div wrapper needed. Tested in firefox at all zoom levels including the ones which trigger the small stylesheet. But I didn't check who else uses that CSS rule to check for unintended consequences.

**Comment by danstowell** [comment]
Oops just found another glitch: if you shrink your screen so that the "small" stylesheet is in operation, then the routing **uses the wrong search text**, because it grabs the text from the copy of the form which is shown to big-screeners!

This will fail silently if there's no text in the big-screener form: it simply looks like it silently decides not to give you any routing. But if you start in big-screen mode, enter text, then shrink to small-screen mode and try a *different* search, you'll see it return results for the old one.

I believe the reason is related to the fact that the site outputs two separate HTML blocks for the form in the two modes. I'd imagine the JS didn't expect that.

**Comment by zerebubuth** [comment]
Ah yes, I'd seen the two separate copies of the sidebar content tree. How annoying. I'll fix that.

**Comment by zerebubuth** [comment]
@danstowell: I think I fixed this in 1b2bfb6 - could you have another go and let me know if it's still an issue for you, please?

**Comment by danstowell** [comment]
@zerebubuth yes, fix works here, thanks!

**Comment by danstowell** [comment]
There's a typo in 1b2bfb6 however which prevents the directions close-box from working. Fixed in [PR 32](https://github.com/systemed/openstreetmap-website/pull/32)

**Comment by systemed** [comment]
This is looking great now, thanks to @zerebubuth, @tomhughes and @danstowell. Are there any blockers remaining?

**Comment by tomhughes** [comment]
There's a couple of things I want to look at still - can hopefully get them done this week.

Other than that, should we speak to the operators of the engines we are using before we go live?

**Comment by karussell** [comment]
From the GraphHopper operator +1 ;)

**Comment by DennisOSRM** [comment]
+1

**Comment by pnorman** [comment]
I believe we've either gotten explicit okays or we're meeting the terms of service for every routing engine we're launching with. A note in advance to those who haven't commented here would probably be good, more to make them aware if they want to do anything for their own communications channels.

Note: Not writing this as a MQ employee.

**Comment by HolgerJeromin** [comment]
surprisingly usable from mobile :-)
Problems:
if a routing is presented i can drag both markers. 
but on mobile the direction list is closed, so the position of my finger at the starting  ondrag is not at the point of the ontouch. 

If i enter the start point name and push enter on the soft keyboard the div with start and end is closed. I have to reopen it. When i leave the input (without enter) everything works nice.

**Comment by Zverik** [comment]
Are we discussing `jsrouting2` here? Follow [this link](http://jsrouting2.apis.dev.openstreetmap.org/directions?engine=graphhopper_foot&route=59.9644%2C30.2985%3B59.9546%2C30.3599) to a route, then try to get directions for another city.

**Comment by tomhughes** [comment]
No, http://jsrouting.apis.dev.openstreetmap.org/ is the current code.

**Comment by Zverik** [comment]
Ah, sorry. That one works fine.

**Comment by danstowell** [comment]
ok, fixed @HolgerJeromin 's second issue with that latest commit. I can't reproduce the first issue (neither on my shrunken web browser, nor on my firefoxos phone). It's possible that the commit also coincidentally affected the first one as well (i.e. the one about dragging markers with your finger)...

**Comment by HolgerJeromin** [comment]
The fist issue is still valid for my opera mobile classic (old presto engine). While dragging the markers the routing is updated live. So the number of entries in the direction view is changing. Thus the map view is moved under the finger. But this is no real blocker for me.

**Comment by danstowell** [comment]
:D

**Comment by ximex** [comment]
:+1:

**Comment by mkoniecz** [comment]
Thanks to all involved!

**Comment by ximex** [comment]
are there intermediate stops planed to support?
and where should i leave an issue if i found some strange routing with GraphHopper Cycle?

**Comment by tomhughes** [comment]
Well you should start by checking that the data is right - the main point of having routing there is to find errors in the data.

If you think the data is right and the engine is wrong then you should contact the Graphopper developers.

**Comment by karussell** [comment]
Nice! Thanks to @tomhughes & @systemed and others for all the coding work!

**Comment by devemux86** [comment]
:+1:

**Comment by JeanFred** [comment]
This is great, thanks to everyone involved.

**Pull request merged**
