### PR TITLE
Added (un)hide note comments API endpoint

### PR DESCRIPTION
**Pull request by mmd-osm**
Adding the API part to address #1934 to hide/unhide single note comments for moderators. The code is very closely following the existing changeset comment hide / destroy implementation.

NotesController `comment` method could be moved to the new NoteCommentsController, to more closely follow the overall design in ChangesetCommentsController. I left that for another request to keep this one as small as possible.

UI part is covered in #3441, providing  the familiar "hide" / "unhide" feature:

modnotecomment

- [ ] Resolve discussion in https://github.com/openstreetmap/openstreetmap-website/issues/3450#issuecomment-1034913872 on how to handle "opening" events

Previous discussion:

> An "opened" event is used exclusively when creating a new note. https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/api/notes_controller.rb#L76
> 
> I think what needs to be clarified first is whether we want the opening event to be hidden at all. Depending on this decision other parts of the code need to be adjusted to handle this case properly.

### CODE REVIEW

**Comment by gravitystorm** [comment]
One of the problems with special-casing the "opened" event is that it's not always the first visible comment. For example, if a user is deleted, the new first visible comment is then the original first reply, and so on as more comments are hidden and/or users deleted.

**Comment by mmd-osm** [comment]
Looking at https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/browse/note.html.erb#L38 I think, "opened" is never a visible comment. It seems to be some technical artifact to store additional data (like author_ip) for notes created by anonymous, as well as known users.

**Comment by mmd-osm** [comment]
I think, "opened" notes never qualify to be displayed, as they are used to store additional data for the note (like ip address or user id). The question what happens to other comments (even if they come from deleted users) is somehow unrelated, imho.

**Comment by AntonKhorev** [comment]
> One of the problems with special-casing the "opened" event is that it's not always the first visible comment.

Opening comment is either the first (description) one or is not shown. It can't be in any other place. What's possible is that the visible "description" is not the opening comment, but that's unrelated to the API changes here. And it won't happen once #3608 is merged.

The UI PR #3441 doesn't have a button to hide the description. If we want to be able to do this we can add it later.

**Comment by mmd-osm** [comment]
@AntonKhorev : I have no more plans to follow up on this pull request (as well as #3441). If you like you can cherry pick my changes and create a new pull request. As you've done a number of related changes, it makes most sense to have it all done by one dev. Closing here.

**Comment by gravitystorm** [comment]
I'd really rather these were left open, because I do mean to review them and if they are closed they will drift away into the void.

But you've closed them twice now, and so I'll respect that and leave them as you wish.

**Comment by mmd-osm** [comment]
The original issues are still around, and the topic is on the DWG wishlist. So it's unlikely that topic will disappear.

As I'm not following the repo much these days, and there's lots of related activity in other pull requests I can't keep up with at the moment, closing seemed unavoidable. I really hope @AntonKhorev can take over somehow.

**Comment by AntonKhorev** [comment]
Is there any related activity in pull requests other than https://github.com/openstreetmap/openstreetmap-website/pull/3608?

**Comment by mmd-osm** [comment]
The biggest challenge for me was that the discussion in #3450 and https://github.com/openstreetmap/openstreetmap-website/pull/3438#issuecomment-1044512922 was never resolved.

Then we have some related activity in #3608 as you've noted. There may be in one of your pull requests. I haven't looked through all of them, so may be missing some context here.

**Comment by AntonKhorev** [comment]
https://github.com/openstreetmap/openstreetmap-website/pull/3438#issuecomment-1044512922 - see https://github.com/openstreetmap/openstreetmap-website/pull/3438#issuecomment-1193133163

https://github.com/openstreetmap/openstreetmap-website/pull/3608 is a fix for both https://github.com/openstreetmap/openstreetmap-website/issues/3450 and https://github.com/openstreetmap/openstreetmap-website/pull/3438#issuecomment-1044512922

There's no "lots" of related activity.

**Comment by AntonKhorev** [comment]
All I can do here is wait for https://github.com/openstreetmap/openstreetmap-website/pull/3608 to get merged and if that happens, do https://github.com/openstreetmap/openstreetmap-website/pull/3608#issuecomment-1191269573 in a new pull request.

**Comment by kmpoppe** [comment]
> All I can do here is wait for https://github.com/openstreetmap/openstreetmap-website/pull/3608 to get merged and if that happens, do https://github.com/openstreetmap/openstreetmap-website/pull/3608#issuecomment-1191269573 in a new pull request.

@Anton, #3608 was closed due to being superseded, are you interested in continuing from here?

**Pull request closed without merging**
