### PR TITLE
Use new OSRM API

### PR DESCRIPTION
**Pull request by TheMarex**
This addresses issue https://github.com/openstreetmap/openstreetmap-website/issues/1161

Currently this is not working yet and mostly the result of an long-ish train ride.

- [x] Fix query code
- [x] Add sprites icons for new instructions (almost done)
- [x] Make sure there are translations for each new instruction type

### CODE REVIEW

**Comment by TheMarex** [comment]
Rebased this against master and adapted other routing plugins to also use the new icons.

@tomhughes would be much obliged if you could review this so we can get this up to production, since we want to shut down the OSRM 4.9 server soon. :bow:

**Comment by tomhughes** [comment]
Well it would be a lot easier if you hadn't gratuitously changed all the icons instead of just adding the new ones... I'm a little concerned to that the new ones appear to be somewhat less bold, using thinner lines and things that will effect the visual appearance.

I don't have much time this weekend and I'm away all next week but I'll see what I can do.

**Comment by tomhughes** [comment]
Presumably I need to change the endpoint we are hitting for this to work? Currently I just get an error for any route I try...

**Comment by tomhughes** [comment]
So some specific issues with the new icons:

* Icon 16 has bad the direction of the arrows reversed - admittedly I don't think it's actually used but we should either remove it or keep it the same.
* Icons 8 (start) and 14 (end) are the same, which made sense when it was just a blob but doesn't now you've added an arrow, though you seem to be using 9 for start with OSRM anyway.

In general terms as I said I'm not a great fan of the thinner lines, shorter arrows and generally more anguiar forms compared to the old icons.

Some of the new ones are also very complicated though I understand it's hard to visualise such things in such a small space. Icons 20 and 21 in particular are hard to understand, though I'm not really sure where they would be used anyway - there are very few places where roads "merge" other than on ramps and those have other icons anyway (well actually they don't, they use slight-right and slight-left!).

**Comment by tomhughes** [comment]
Oh, and there are jshint warnings being reported by travis.

**Comment by tomhughes** [comment]
Hmm you have got mapzen using 20 for on ramps, but OSRM is using 2 and 6 which just seems wrong - that isn't even slight left and right, it's full 90 degree left and right.

**Comment by TheMarex** [comment]
> I need to change the endpoint we are hitting for this to work? 

I'm not sure how to configure this. I modified `config/application.yml` on my local test setup. The new URL is `//router.project-osrm.org/route/v1/driving/`. Maybe you can point me to the location where I can fix this.

> Icon 16 has bad the direction of the arrows reversed

Good catch.

> Icons 8 (start) and 14 (end) are the same

Agreed, fixed.

> you have got mapzen using 20 for on ramps, but OSRM is using 2 and 6 

I don't see that. Github let's you comment on the exact lines in the changes of a PR, maybe that helps.

You will note that the new icons come with a vector source unlike the old ones. I'm sure some more experienced designers can improve them.

**Comment by tomhughes** [comment]
You should update the URL in `config/example.application.yml` which is the example config.

**Comment by tomhughes** [comment]
Not sure if this is a bug in OSRM or in the javascript, but http://dev.osm.compton.nu/directions?engine=osrm_car&route=50.9580%2C-2.7590%3B50.9465%2C-2.7696#map=15/50.9523/-2.7660 is telling me to a right turn when it's clear a left at the bottom of the slip road!

**Comment by TheMarex** [comment]
> telling me to a right turn when it's clear a left at the bottom of the slip road!

Good catch, the maneuver simplification had a small big.

**Comment by tomhughes** [comment]
Merged as 311acad0c43401fe3d7651d021154af2efbedff5 with a few fixed for icon mapping in the other engines as 078dc1a5266f11e94150a36eec87bc680609ee68.

**Pull request closed without merging**
