### PR TITLE
Add FAQ and information about creating a banner image

### PR DESCRIPTION
**Pull request by bhousel**
This tells people how to create a pull request to add a banner image for their event.

### CODE REVIEW

**Comment by tomhughes** [comment]
Is creating a new top level FAQ file just for this really appropriate? Not sure what the answer is, but it seems odd to me.

**Comment by Zverik** [comment]
I think this should be made into a banner policy, with instructions at the bottom.

**Comment by bhousel** [comment]
> Is creating a new top level FAQ file just for this really appropriate?

Yes!  I'm sure people would want to see more things in here than how to make a banner pull request, but I just started with that because it's conference season again.

**Comment by bhousel** [comment]
Just a friendly ping - can this be merged?  It's just a really useful documentation for creating an event banner.  It was great to have handy when putting together #1651

**Pull request merged**
