### PR TITLE
Mobile layout is triggered not by JS, but by media queries, now some map…

### LINKED ISSUE #2349: Tiles not loading properly when opening notes link on phone
Hey, usually I do not have issues with the website, but the tiles, *never* load as they should on my phone. On my Mac, they loas fine.

Using Chrome Beta on a One Plus 5 with Android 9.

When loading the page, only the tiles at the left load. The right stays gray. Panning around the map does not load tiles. When going to another tab in chrome and then revisiting the OSM tab, all tiles load properly.

Example: https://www.openstreetmap.org/note/1885992#map=14/38.5414/-0.1020

Screenshot_20190817-102808

### PR DESCRIPTION
**Pull request by bezdna**
… bugs have gone away themselves

fix #2349 #2035 #1864 #1663

**no blank space:**
image

### CODE REVIEW

**Comment by gravitystorm** [comment]
I agree with the general approach here. I hadn't realised until now, but the switch to mobile layout (for the whole page) is based on the rendered width of the menus. If you change one of the menu labels to be really long, you can see that we move the sidebars around even on really wide screens.

I think we should decouple this, and switch the layout based only on the width of the screen, and change only the menus based on the rendered width of the menus.

I can't merge this PR yet, because there's two things that we need to address:

* Choice of breakpoint width. This PR uses a width of 640px, but that's not one of [the breakpoints used by bootstrap](https://getbootstrap.com/docs/4.4/layout/overview/). It would be good to align them, for consistency.
* There's a problem where the secondary nav reappears when the window is shrunk. The aim is that there are three stages - all menus fully shown, then 'compact' mode where the 'more' dropdown appears, and then 'small' where all three menus are combined into one hamburger. But with this PR, there's a width of screen (640px-720px) where the small rules are not applied (because the window is greater than 640), but there's not yet enough width for the compact menu, and so the menus are broken:

Screen Shot 2020-02-26 at 16 37 14

So I would suggest expanding this PR slightly, to fix the menu issue. It's likely fixable just by finding the menu-related style rules that are now inside the `@media` section, and moving them back into a `body.small` section.

It might also be worth moving the javascript-applied classes off of the `<body>` element and onto the `<header>` (in app/views/layouts/_header.html.erb) since they are only going to affect the menu display from now on.

**Comment by bezdna** [comment]
@gravitystorm recent spot changes do not fix the problem well enough?

**Comment by bezdna** [comment]
@gravitystorm two things that you said took into account.
why don't you want to accept pull request?

**Comment by gravitystorm** [comment]
> why don't you want to accept pull request?

No reason, just a lack of time. I don't get much time to work on this each week, and I'm juggling a lot of different topics and trying to make progress on each. I'll get to this soon.

**Comment by gravitystorm** [comment]
Great, I've reviewed this and it works well now. It fixes some, but not all, of the linked issues, so thank you very much for this!

**Pull request merged**
