### PR TITLE
Prefer keyword arguments when method has optional boolean arguments

### PR DESCRIPTION
**Pull request by gravitystorm**
This PR fixes some cases where we are using optional boolean parameters, to use keyword arguments instead.

 I think this is particularly useful where the method definition lies elsewhere, since it's not obvious what an isolated 'true' or 'false' means.

https://docs.rubocop.org/rubocop/1.0/cops_style.html#styleoptionalbooleanparameter

### CODE REVIEW

**Comment by tomhughes** [comment]
Looks like you missed something:

```
Error:
DiaryEntryTest#test_diary_entry_validations:
ArgumentError: wrong number of arguments (given 2, expected 1)
    test/models/diary_entry_test.rb:51:in `diary_entry_valid'
    test/models/diary_entry_test.rb:13:in `test_diary_entry_validations'


rails test test/models/diary_entry_test.rb:9
```

**Comment by tomhughes** [comment]
Maybe that test failure wasn't down to this as travis has passed and I've just seen that failure in a checkout without this merged.... Guess there me some non-deterministic failure :-(

**Comment by tomhughes** [comment]
No it is from this branch - my checkout was messed up.

**Comment by tomhughes** [comment]
Ah and you had fixed it anyway.

**Comment by gravitystorm** [comment]
> Ah and you had fixed it anyway.

Sorry! I force-pushed, and then I was waiting to double-check that travis passed before commenting, but I got distracted and forgot to come back.

**Pull request merged**
