### PR TITLE
Invert routing direction icons in dark mode

### PR DESCRIPTION
**Pull request by AntonKhorev**
image

image

### CODE REVIEW

**Comment by AntonKhorev** [comment]
Either merge in #4653, then enabling dark mode in Firefox is going to work.

Or manually add `data-bs-theme="dark"` to the root `<html>` element.

**Comment by tordans** [comment]
Should we add a user profile setting that overwrites the system preferences and allows testing? This would also be a feature flag for testing. We could deploy that disabled so more users can test live over time...

**Comment by AntonKhorev** [comment]
```js
document.documentElement.dataset.bsTheme='dark'
```

**Comment by tomhughes** [comment]
Looks good to me, thanks.

**Pull request merged**
