### PR TITLE
Adds key to cyclemap

### PR DESCRIPTION
**Pull request by emersion**
Related to #982.

Adds key to cyclemap.

WIP: not finished yet, I just want to know if I do it the right way :-P

### CODE REVIEW

**Comment by tomhughes** [comment]
Well the "right way" at some point will hopefully be to use @gravitystorm's automatic key generator thing...

**Comment by emersion** [comment]
Are you talking about [mapnik_legendary](https://github.com/gravitystorm/mapnik-legendary)?

I thought cycle and transport map styles were not public, so I gave up (it's said on the wiki).

**Comment by tomhughes** [comment]
Well sure, but that doesn't mean that @gravitystorm couldn't run it and generate the output.

Don't let that stop you for now anyway, unless you'd prefer to get involved with making that solution work ;-)

**Comment by emersion** [comment]
All right, I just added key from http://www.opencyclemap.org/docs/, I think all major entities are here.

**Comment by pnorman** [comment]
Anything else that needs to be done on this PR that is preventing it from being merged?

**Comment by tomhughes** [comment]
I made one small fix in b40e01bce232073a9b7ae898d88adc3d46f8f288 to add a missing translation.

**Comment by emersion** [comment]
Yay, thanks!

**Pull request merged**
