### PR TITLE
Update en.yml alerting user that they will need to later login to comment on 

### PR DESCRIPTION
**Pull request by jidanni**
For https://github.com/openstreetmap/openstreetmap-website/issues/2303#issuecomment-2184116004 .

(Yes, actually later login.)

### CODE REVIEW

**Comment by AntonKhorev** [comment]
You'll be able to comment a note even if you create it anonymously.

**Comment by jidanni** [comment]
Well then https://github.com/openstreetmap/openstreetmap-website/issues/2303#issuecomment-2184116004 is wrong.

**Comment by AntonKhorev** [comment]
You can create a note anonymously, then log in, then comment it. If you didn't log in before commenting, you'll see a link telling you to log in.

You can't comment a note anonymously.

**Comment by jidanni** [comment]
Fine. All this is getting over my head. Beyond my capacity to understand. I'll just abandon this issue.

**Comment by mmd-osm** [comment]
Alight, I’m closing here.

**Pull request closed without merging**
