### PR TITLE
Password fields with show/hide functionality

### PR DESCRIPTION
**Pull request by kcne**
### Implementation Details

This PR introduces functionality that allows users to toggle the visibility of password fields in signup and login forms. This enhancement improves both usability and accessibility.

### Changes Made

1. **Add `password_field_with_toggle` partial**
   - Integrated a reusable Ruby component that can be utilized within both login and signup forms.

2. **Add Show/Hide JavaScript Helpers**
   - Implemented JavaScript functionality to toggle the visibility of password fields using the `addTogglePasswordEventListener` function.

### Screenshots

Screenshot 2024-07-04 at 23 41 05

Signup Page

Screenshot 2024-07-05 at 17 02 56

Signup Page with validation errors

Screenshot 2024-07-05 at 17 04 23

Login Page

### CODE REVIEW

**Comment by AntonKhorev** [comment]
Right click > Reveal password in Firefox

**Comment by HolgerJeromin** [comment]
ref #4543

**Comment by AntonKhorev** [comment]
Anyone who wants this functionality probably wants it not just for openstreetmap website. They are using a browser that has it or install an extension.

**Comment by mmd-osm** [comment]
Right, Edge doesn't need this code, the browser would automatically add it, unless you disable it using some CSS code: https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal

Since I didn't find any special CSS for edge, I was wondering, if adding this button would interfere with what Edge is doing.

**Comment by kcne** [comment]
I'll try and test this with Edge. I can try to conditionally render this buttons according to the browser being used.

**Comment by HolgerJeromin** [comment]
> according to the browser being used

Browser sniffing is and was always bad. Please try to avoid it.

**Comment by kcne** [comment]
According to [docs](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal) it can be disabled using CSS only. Amended the changes to the commit.

**Comment by AntonKhorev** [comment]
> According to [docs](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal) it can be disabled using CSS only

According to docs you shouldn't do this.

**Comment by stalker314314** [comment]
I agree that it can be said that we are fiddling with what could be work of "user agent" (in original sense). Put that way - this PR is not needed. However, I think that #4543 should be closed too (or at least rephrased), just that it doesn't give impression this is something it needs to  be implemented

**Pull request closed without merging**
