### PR TITLE
Fix "Report a problem" link in embedded map

### PR DESCRIPTION
**Pull request by floscher**
You can find a demo of the problem here: http://floscher.github.io/openstreetmap-website/demo.html
The first map is the current `embed.html`, the second map incorporates my proposed change.

Previously when you embedded a map with the HTML from the share-menu on http://osm.org, the link "Report a problem" was broken, because some browsers (at least Firefox 43 and Chromium 47) denied to open that link.

In Firefox the map is turning invisible and I get the following error message in the developer console:
```
Load denied by X-Frame-Options: http://www.openstreetmap.org/fixthemap?lat=0&lon=1.40625&zoom=0 does not permit cross-origin framing.
```

In Chromium simply nothing happens and the developer console shows:
```
Refused to display 'http://www.openstreetmap.org/fixthemap?lat=-1.1449996853268662e-13&lon=0&zoom=0' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

I fixed that problem by setting the attribute `target="_blank"` for that link, so it now opens in a new tab.

I also added the text of this link to the translatable strings.

### CODE REVIEW

**Comment by tomhughes** [comment]
Surely the correct fix is to stop denying embedding, not to force it to open in a popup?

**Comment by HolgerJeromin** [comment]
Do we want to fix a problem in the small embedded view? 
Perhaps both is needed / useful

**Comment by floscher** [comment]
I think it's useful to open a new tab for that to make it clear to the user, that he/she is reporting the problem to openstreetmap.org and not to the website where the map is embedded.

Additionally these embedded maps are sometimes quite small, and it wouldn't be very pleasant to browse http://openstreetmap.org/fixthemap and the following sign up process in a small iframe embedded inside another page.

**Comment by floscher** [comment]
My opinion is still, that opening in a new tab is the desired behaviour. Nobody wants to report a problem in a small embedded iframe and creating a new OSM account in order to fix the problem is probably even more unpleasant.

Is there anything I can do to improve this PR, so that it is merged?

**Comment by floscher** [comment]
@tomhughes By the way, you have done the very same change that I propose here to the copyright link right next to the "Report a problem" link: https://github.com/openstreetmap/openstreetmap-website/commit/33bcb2e08807ac6f3cb80ff7969dfdc705ded899#diff-04a887e53025b45e717150bdb931aa5aR8

**Comment by floscher** [comment]
Any news on this?

That link is broken and needs some fix, either my proposed addition of `target="_blank"` or a change in the X-Frame-Options.

**Comment by tomhughes** [comment]
On reflection I think opening a new tab is probably the right thing to do.

The change to make the text translatable isn't going to work though, both because you haven't exported that resource to javascript by listing it in `config/i18n-js.yml` and because in any case I'm pretty sure the locale is not set by the embed page.

**Comment by tomhughes** [comment]
In fact the client side I18n code isn't even loaded in that page...

**Comment by tomhughes** [comment]
Ah that resource is being exported, so it's just I18n initialisation that needs fixing, and 544ed362472f4e5504b1fc4c51ad7bd3fa16afae should take care of that.

Otherwise all merged.

**Pull request closed without merging**
