### PR TITLE
add banner for state of the map 2020

### PR DESCRIPTION
**Pull request by tyrasd**
it's this weekend already [:see_no_evil:](https://github.com/openstreetmap/openstreetmap-website/pull/2428#issuecomment-552148969) , but since the conference is online anyway, it's still relevant perhaps?

### CODE REVIEW

**Comment by tomhughes** [comment]
Merged as d49771ba95766b62534c607d2ab28a1a41aae14b.

**Comment by tyrasd** [comment]
Thanks. Is it already online? Asking because I assumed the banner would be displayed when opening osm.org right now… :thinking:

**Comment by tomhughes** [comment]
I believe I pushed it live yes.

**Comment by tomhughes** [comment]
Yep it's live - check your ad blocked isn't killing it.

**Comment by tyrasd** [comment]
ah yes, it was ad blocked. sorry for the noise.

**Pull request closed without merging**
