### PR TITLE
Changed open_note_marker from red 'X' to yellow '!'

### PR DESCRIPTION
**Pull request by nlaratta**
Addresses issue #2882 
Before: 
open_note_marker@2x
After:
open_note_marker@2x

### CODE REVIEW

**Review by gravitystorm — CHANGES_REQUESTED** [review]
Looks good! Can I ask for a few small changes:

* There is a file NoteMarker.svg in the same directory, which contains the SVG sources for the note markers. Could you please add your new marker to that file too, that way it's easier in future if more changes need to be made.
* Have you tried with a slightly more vibrant colour? I found this particular yellow hard to see when I tested it locally. The markers are translucent so the map background shines through - this means that markers need to be strongly coloured to really stand out.
* The .png files here are much much bigger (10x) than the originals. It looks like photoshop has added large amounts of metadata to the files. If you can remove that, great, but if not we'll do that ourselves. (e.g. `pngcrush -rem text open_note_marker.png test.png` reduces from 19170 to 2274 bytes, original was 1883).

**Comment by gravitystorm** [comment]
image

**Comment by dieterdreist** [comment]
sent from a phone

> On 11. Nov 2020, at 15:11, Andy Allan <notifications@github.com> wrote:
> 
> ﻿
> 
> 

the shadow is missing, it will make it easier to spot with a drop shadow

**Comment by matkoniecz** [comment]
> Have you tried with a slightly more vibrant colour? I found this particular yellow hard to see when I tested it locally.

Also, it is a bit sad/dead/depressing/dirty. I would support more vibrant also for that reason.

**Comment by mnalis** [comment]
@nlaratta are you still interested on working on this PR to change Note marker for OSM?

**Comment by mmd-osm** [comment]
https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/images/NoteMarker.svg hasn't been updated as requested by @gravitystorm - also no user feedback since two years.

Closing this PR seems inevitable.

**Comment by mmd-osm** [comment]
Closing now, as suggested in previous comment.

**Pull request closed without merging**
