### PR TITLE
Have user ID as part of user block detail

### PR DESCRIPTION
**Pull request by bkowshik**

### CODE REVIEW

**Comment by bkowshik** [comment]
Closes #1222

**Comment by tomhughes** [comment]
Please don't open an issue and then immediately create a PR with no description to address it - if you have a PR ready then just open the PR and explain the issue there.

**Comment by tomhughes** [comment]
Also, writing "Closes #1222" here does nothing - that needs to be in the commit comment to work.

**Comment by tomhughes** [comment]
So as far as I can see this doesn't actually display the ID but rather it just embeds it as a data attribute in the HTML page? What is the point of that?

**Comment by bkowshik** [comment]
Hey @tomhughes, thank you for pointing me to good practices while contributing to OpenStreetMap, FOSS in general. 😃 

I have seen Github close the issue automatically when the PR is merged if it has a comment like `Closes #xxxx` in it.

Users on OpenStreetMap have an option to change their `display name` but their `user ID` remains the same. So, when a user is blocked, it would help to know what the `user ID` is.

Let me know if there is a better approach to doing this.

**Comment by tomhughes** [comment]
I didn't realise auto-close worked with PR comments but I guess it might.

I understand what it is you want, though I'm not sure why you're so interested in tracking who is blocked? It's only ever a tiny number of people...

I still don't understand how hiding the number away in the HTML achieves that though? Are you going to do "view source" every time to find it?

**Comment by pnorman** [comment]
> I didn't realise auto-close worked with PR comments but I guess it might.

iirc, it doesn't work in replies, only the original message

-----
:-1: to this - the user ID is belongs in an API, not a user-facing HTML page.

**Comment by iandees** [comment]
[More info on the keywords in GitHub](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by woodpeck** [comment]
I think that there's a clear separation between web pages made for human consumption, and API calls made for programs to access. There should be no programs scraping the web pages, at all, ever. If someone desires to programmatically process user blocks then an API call should be added that lists them - if it is considered something that we *want* programmatically processed.

**Comment by bkowshik** [comment]
@tomhughes: I want to learn if there is a relationship between user blocks and changes to display names.
@pnorman, @iandees: Thank you for the Github note.

Very clear explanation @woodpeck. I now understand how this is better on an API vs on a page for human consumption. Thank you everybody for your helpful comments. :+1:

No further actions here. Closing.

**Pull request closed without merging**
